#!/usr/bin/env python3
"""Generate the standalone replay C header from the versioned HLS golden JSON."""
from __future__ import annotations
import argparse
import hashlib
import json
from pathlib import Path

def c_array(values: list[int], indent: str = "    ") -> str:
    rows=[]
    for i in range(0,len(values),16):
        rows.append(indent + ", ".join(str(v) for v in values[i:i+16]))
    return ",\n".join(rows)

def main() -> None:
    ap=argparse.ArgumentParser()
    ap.add_argument("json_path", type=Path)
    ap.add_argument("header_path", type=Path)
    ap.add_argument("manifest_path", type=Path)
    args=ap.parse_args()
    raw=args.json_path.read_bytes()
    data=json.loads(raw.decode("utf-8"))
    cases=data["cases"]
    if len(cases) != 3:
        raise ValueError(f"expected three cases, got {len(cases)}")
    digest=hashlib.sha256(raw).hexdigest()
    out=[]
    out += ["/* Generated by scripts/export_golden_to_c.py; do not edit manually. */", "#ifndef SNN_GOLDEN_VECTORS_Q12_6_H", "#define SNN_GOLDEN_VECTORS_Q12_6_H", "", "#include <stdint.h>", "", "#define SNN_GOLDEN_CASE_COUNT 3", "#define SNN_GOLDEN_FEATURE_WORDS 1536", "#define SNN_GOLDEN_WEIGHT_WORDS 64", "#define SNN_GOLDEN_BIAS_WORDS 2", "#define SNN_GOLDEN_LOGIT_WORDS 2", "#define SNN_GOLDEN_COUNT_WORDS 32", f'#define SNN_GOLDEN_JSON_SHA256 "{digest}"', "", "typedef struct {", "    const char *name;", "    int16_t feature_current_q[SNN_GOLDEN_FEATURE_WORDS];", "    int16_t weight_q[SNN_GOLDEN_WEIGHT_WORDS];", "    int16_t bias_q[SNN_GOLDEN_BIAS_WORDS];", "    int32_t expected_logits_q[SNN_GOLDEN_LOGIT_WORDS];", "    uint8_t expected_counts[SNN_GOLDEN_COUNT_WORDS];", "} snn_golden_case_t;", "", "static const snn_golden_case_t snn_golden_cases[SNN_GOLDEN_CASE_COUNT] = {"]
    for idx,c in enumerate(cases):
        features=[v for row in c["feature_current_q"] for v in row]
        weights=[v for row in c["weight_q"] for v in row]
        bias=c["bias_q"]
        logits=c["logits_q"]
        counts=c["spike_count"]
        out += ["    {", f'        "{c["case_name"]}",', "        {", c_array(features), "        },", "        {", c_array(weights), "        },", "        {", c_array(bias), "        },", "        {", c_array(logits), "        },", "        {", c_array(counts), "        }", "    }" + ("," if idx < len(cases)-1 else "")]
    out += ["};", "", "#endif /* SNN_GOLDEN_VECTORS_Q12_6_H */", ""]
    args.header_path.parent.mkdir(parents=True, exist_ok=True)
    args.header_path.write_text("\n".join(out), encoding="utf-8", newline="\n")
    manifest={"source":str(args.json_path).replace("\\","/"),"sha256":digest,"case_names":[c["case_name"] for c in cases],"schema_version":data.get("schema_version"),"generated_header":str(args.header_path).replace("\\","/")}
    args.manifest_path.parent.mkdir(parents=True, exist_ok=True)
    args.manifest_path.write_text(json.dumps(manifest, ensure_ascii=False, indent=2)+"\n",encoding="utf-8",newline="\n")

if __name__ == "__main__":
    main()
