// ==============================================================
// Generated by Vitis HLS v2025.1
// Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// Copyright 2022-2025 Advanced Micro Devices, Inc. All Rights Reserved.
// ==============================================================

`timescale 1 ns / 1 ps 

module hybrid_lif_head_q12_6_run_hybrid_lif_head_Pipeline_VITIS_LOOP_66_5 (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_idle,
        ap_ready,
        weight_q_address0,
        weight_q_ce0,
        weight_q_q0,
        weight_q_address1,
        weight_q_ce1,
        weight_q_q1,
        conv_i104_i,
        conv_i104_1_i,
        conv_i104_2_i,
        conv_i104_3_i,
        conv_i104_4_i,
        conv_i104_5_i,
        conv_i104_6_i,
        conv_i104_7_i,
        conv_i104_8_i,
        conv_i104_9_i,
        conv_i104_10_i,
        conv_i104_11_i,
        conv_i104_12_i,
        conv_i104_13_i,
        conv_i104_14_i,
        conv_i104_15_i,
        conv_i104_16_i,
        conv_i104_17_i,
        conv_i104_18_i,
        conv_i104_19_i,
        conv_i104_20_i,
        conv_i104_21_i,
        conv_i104_22_i,
        conv_i104_23_i,
        conv_i104_24_i,
        conv_i104_25_i,
        conv_i104_26_i,
        conv_i104_27_i,
        conv_i104_28_i,
        conv_i104_29_i,
        conv_i104_30_i,
        conv_i104_31_i,
        bias_q_address0,
        bias_q_ce0,
        bias_q_q0,
        logits_q_address0,
        logits_q_ce0,
        logits_q_we0,
        logits_q_d0
);

parameter    ap_ST_fsm_pp0_stage0 = 16'd1;
parameter    ap_ST_fsm_pp0_stage1 = 16'd2;
parameter    ap_ST_fsm_pp0_stage2 = 16'd4;
parameter    ap_ST_fsm_pp0_stage3 = 16'd8;
parameter    ap_ST_fsm_pp0_stage4 = 16'd16;
parameter    ap_ST_fsm_pp0_stage5 = 16'd32;
parameter    ap_ST_fsm_pp0_stage6 = 16'd64;
parameter    ap_ST_fsm_pp0_stage7 = 16'd128;
parameter    ap_ST_fsm_pp0_stage8 = 16'd256;
parameter    ap_ST_fsm_pp0_stage9 = 16'd512;
parameter    ap_ST_fsm_pp0_stage10 = 16'd1024;
parameter    ap_ST_fsm_pp0_stage11 = 16'd2048;
parameter    ap_ST_fsm_pp0_stage12 = 16'd4096;
parameter    ap_ST_fsm_pp0_stage13 = 16'd8192;
parameter    ap_ST_fsm_pp0_stage14 = 16'd16384;
parameter    ap_ST_fsm_pp0_stage15 = 16'd32768;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
output   ap_idle;
output   ap_ready;
output  [5:0] weight_q_address0;
output   weight_q_ce0;
input  [11:0] weight_q_q0;
output  [5:0] weight_q_address1;
output   weight_q_ce1;
input  [11:0] weight_q_q1;
input  [6:0] conv_i104_i;
input  [6:0] conv_i104_1_i;
input  [6:0] conv_i104_2_i;
input  [6:0] conv_i104_3_i;
input  [6:0] conv_i104_4_i;
input  [6:0] conv_i104_5_i;
input  [6:0] conv_i104_6_i;
input  [6:0] conv_i104_7_i;
input  [6:0] conv_i104_8_i;
input  [6:0] conv_i104_9_i;
input  [6:0] conv_i104_10_i;
input  [6:0] conv_i104_11_i;
input  [6:0] conv_i104_12_i;
input  [6:0] conv_i104_13_i;
input  [6:0] conv_i104_14_i;
input  [6:0] conv_i104_15_i;
input  [6:0] conv_i104_16_i;
input  [6:0] conv_i104_17_i;
input  [6:0] conv_i104_18_i;
input  [6:0] conv_i104_19_i;
input  [6:0] conv_i104_20_i;
input  [6:0] conv_i104_21_i;
input  [6:0] conv_i104_22_i;
input  [6:0] conv_i104_23_i;
input  [6:0] conv_i104_24_i;
input  [6:0] conv_i104_25_i;
input  [6:0] conv_i104_26_i;
input  [6:0] conv_i104_27_i;
input  [6:0] conv_i104_28_i;
input  [6:0] conv_i104_29_i;
input  [6:0] conv_i104_30_i;
input  [6:0] conv_i104_31_i;
output  [0:0] bias_q_address0;
output   bias_q_ce0;
input  [11:0] bias_q_q0;
output  [0:0] logits_q_address0;
output   logits_q_ce0;
output   logits_q_we0;
output  [17:0] logits_q_d0;

reg ap_idle;

(* fsm_encoding = "none" *) reg   [15:0] ap_CS_fsm;
wire    ap_CS_fsm_pp0_stage0;
reg    ap_enable_reg_pp0_iter0;
reg    ap_enable_reg_pp0_iter1;
reg    ap_idle_pp0;
wire    ap_CS_fsm_pp0_stage10;
wire    ap_block_pp0_stage10_subdone;
reg    ap_enable_reg_pp0_iter0_reg;
reg   [0:0] icmp_ln66_reg_2096;
reg    ap_condition_exit_pp0_iter0_stage10;
wire    ap_loop_exit_ready;
reg    ap_ready_int;
wire    ap_CS_fsm_pp0_stage15;
wire    ap_block_pp0_stage15_subdone;
reg  signed [11:0] reg_671;
wire    ap_CS_fsm_pp0_stage1;
wire    ap_block_pp0_stage1_11001;
wire    ap_CS_fsm_pp0_stage8;
wire    ap_block_pp0_stage8_11001;
reg  signed [11:0] reg_676;
wire    ap_CS_fsm_pp0_stage9;
wire    ap_block_pp0_stage9_11001;
wire    ap_block_pp0_stage10_11001;
wire    ap_CS_fsm_pp0_stage11;
wire    ap_block_pp0_stage11_11001;
wire    ap_CS_fsm_pp0_stage13;
wire    ap_block_pp0_stage13_11001;
reg  signed [11:0] reg_681;
wire    ap_CS_fsm_pp0_stage2;
wire    ap_block_pp0_stage2_11001;
wire    ap_CS_fsm_pp0_stage12;
wire    ap_block_pp0_stage12_11001;
reg  signed [11:0] reg_686;
reg  signed [11:0] reg_690;
wire    ap_CS_fsm_pp0_stage3;
wire    ap_block_pp0_stage3_11001;
reg  signed [11:0] reg_695;
reg  signed [11:0] reg_699;
wire    ap_CS_fsm_pp0_stage4;
wire    ap_block_pp0_stage4_11001;
wire    ap_CS_fsm_pp0_stage14;
wire    ap_block_pp0_stage14_11001;
wire   [17:0] conv_i104_31_i_cast_fu_703_p1;
reg   [17:0] conv_i104_31_i_cast_reg_1931;
wire    ap_block_pp0_stage0_11001;
wire   [17:0] conv_i104_30_i_cast_fu_707_p1;
reg   [17:0] conv_i104_30_i_cast_reg_1936;
wire   [17:0] conv_i104_29_i_cast_fu_711_p1;
reg   [17:0] conv_i104_29_i_cast_reg_1941;
wire   [17:0] conv_i104_28_i_cast_fu_715_p1;
reg   [17:0] conv_i104_28_i_cast_reg_1946;
wire   [17:0] conv_i104_27_i_cast_fu_719_p1;
reg   [17:0] conv_i104_27_i_cast_reg_1951;
wire   [17:0] conv_i104_26_i_cast_fu_723_p1;
reg   [17:0] conv_i104_26_i_cast_reg_1956;
wire   [17:0] conv_i104_25_i_cast_fu_727_p1;
reg   [17:0] conv_i104_25_i_cast_reg_1961;
wire   [17:0] conv_i104_24_i_cast_fu_731_p1;
reg   [17:0] conv_i104_24_i_cast_reg_1966;
wire   [17:0] conv_i104_23_i_cast_fu_735_p1;
reg   [17:0] conv_i104_23_i_cast_reg_1971;
wire   [17:0] conv_i104_22_i_cast_fu_739_p1;
reg   [17:0] conv_i104_22_i_cast_reg_1976;
wire   [17:0] conv_i104_21_i_cast_fu_743_p1;
reg   [17:0] conv_i104_21_i_cast_reg_1981;
wire   [17:0] conv_i104_20_i_cast_fu_747_p1;
reg   [17:0] conv_i104_20_i_cast_reg_1986;
wire   [17:0] conv_i104_19_i_cast_fu_751_p1;
reg   [17:0] conv_i104_19_i_cast_reg_1991;
wire   [17:0] conv_i104_18_i_cast_fu_755_p1;
reg   [17:0] conv_i104_18_i_cast_reg_1996;
wire   [17:0] conv_i104_17_i_cast_fu_759_p1;
reg   [17:0] conv_i104_17_i_cast_reg_2001;
wire   [17:0] conv_i104_16_i_cast_fu_763_p1;
reg   [17:0] conv_i104_16_i_cast_reg_2006;
wire   [17:0] conv_i104_15_i_cast_fu_767_p1;
reg   [17:0] conv_i104_15_i_cast_reg_2011;
wire   [17:0] conv_i104_14_i_cast_fu_771_p1;
reg   [17:0] conv_i104_14_i_cast_reg_2016;
wire   [17:0] conv_i104_13_i_cast_fu_775_p1;
reg   [17:0] conv_i104_13_i_cast_reg_2021;
wire   [17:0] conv_i104_12_i_cast_fu_779_p1;
reg   [17:0] conv_i104_12_i_cast_reg_2026;
wire   [17:0] conv_i104_11_i_cast_fu_783_p1;
reg   [17:0] conv_i104_11_i_cast_reg_2031;
wire   [17:0] conv_i104_10_i_cast_fu_787_p1;
reg   [17:0] conv_i104_10_i_cast_reg_2036;
wire   [17:0] conv_i104_9_i_cast_fu_791_p1;
reg   [17:0] conv_i104_9_i_cast_reg_2041;
wire   [17:0] conv_i104_8_i_cast_fu_795_p1;
reg   [17:0] conv_i104_8_i_cast_reg_2046;
wire   [17:0] conv_i104_7_i_cast_fu_799_p1;
reg   [17:0] conv_i104_7_i_cast_reg_2051;
wire   [17:0] conv_i104_6_i_cast_fu_803_p1;
reg   [17:0] conv_i104_6_i_cast_reg_2056;
wire   [17:0] conv_i104_5_i_cast_fu_807_p1;
reg   [17:0] conv_i104_5_i_cast_reg_2061;
wire   [17:0] conv_i104_4_i_cast_fu_811_p1;
reg   [17:0] conv_i104_4_i_cast_reg_2066;
wire   [17:0] conv_i104_3_i_cast_fu_815_p1;
reg   [17:0] conv_i104_3_i_cast_reg_2071;
wire   [17:0] conv_i104_2_i_cast_fu_819_p1;
reg   [17:0] conv_i104_2_i_cast_reg_2076;
wire   [17:0] conv_i104_1_i_cast_fu_823_p1;
reg   [17:0] conv_i104_1_i_cast_reg_2081;
wire   [17:0] conv_i104_i_cast_fu_827_p1;
reg   [17:0] conv_i104_i_cast_reg_2086;
reg   [1:0] class_index_1_reg_2091;
wire   [0:0] icmp_ln66_fu_839_p2;
wire   [0:0] trunc_ln66_fu_851_p1;
reg   [0:0] trunc_ln66_reg_2100;
reg  signed [11:0] weight_q_load_15_reg_2184;
wire    ap_CS_fsm_pp0_stage5;
wire    ap_block_pp0_stage5_11001;
reg  signed [11:0] weight_q_load_17_reg_2199;
reg  signed [11:0] weight_q_load_19_reg_2204;
wire    ap_CS_fsm_pp0_stage6;
wire    ap_block_pp0_stage6_11001;
reg  signed [11:0] weight_q_load_21_reg_2219;
reg  signed [11:0] weight_q_load_23_reg_2224;
wire    ap_CS_fsm_pp0_stage7;
wire    ap_block_pp0_stage7_11001;
reg  signed [11:0] weight_q_load_25_reg_2244;
reg  signed [11:0] weight_q_load_27_reg_2249;
reg  signed [11:0] weight_q_load_30_reg_2269;
wire  signed [18:0] grp_fu_1804_p3;
reg  signed [18:0] add_ln72_16_reg_2314;
wire   [19:0] add_ln72_17_fu_1215_p2;
reg   [19:0] add_ln72_17_reg_2339;
wire  signed [18:0] grp_fu_1819_p3;
reg  signed [18:0] add_ln72_18_reg_2364;
wire   [20:0] add_ln72_21_fu_1322_p2;
reg   [20:0] add_ln72_21_reg_2389;
reg  signed [11:0] weight_q_load_22_reg_2409;
wire  signed [18:0] grp_fu_1834_p3;
reg  signed [18:0] add_ln72_22_reg_2419;
wire    ap_block_pp0_stage15_11001;
reg  signed [11:0] weight_q_load_24_reg_2444;
reg  signed [11:0] weight_q_load_26_reg_2449;
wire   [19:0] add_ln72_24_fu_1415_p2;
reg   [19:0] add_ln72_24_reg_2454;
wire   [63:0] zext_ln66_fu_1421_p1;
reg   [63:0] zext_ln66_reg_2459;
reg  signed [11:0] weight_q_load_28_reg_2474;
reg  signed [11:0] weight_q_load_29_reg_2479;
wire  signed [18:0] grp_fu_1849_p3;
reg  signed [18:0] add_ln72_25_reg_2484;
wire   [21:0] add_ln72_29_fu_1489_p2;
reg   [21:0] add_ln72_29_reg_2504;
reg   [11:0] bias_q_load_reg_2509;
wire  signed [18:0] grp_fu_1864_p3;
reg  signed [18:0] add_ln72_7_reg_2524;
wire   [19:0] add_ln72_9_fu_1533_p2;
reg   [19:0] add_ln72_9_reg_2539;
wire  signed [18:0] grp_fu_1879_p3;
reg  signed [18:0] add_ln72_10_reg_2554;
wire   [20:0] add_ln72_13_fu_1588_p2;
reg   [20:0] add_ln72_13_reg_2569;
wire  signed [18:0] grp_fu_1894_p3;
reg  signed [18:0] add_ln72_3_reg_2584;
wire   [19:0] add_ln72_5_fu_1627_p2;
reg   [19:0] add_ln72_5_reg_2594;
wire  signed [18:0] grp_fu_1909_p3;
reg  signed [18:0] add_ln72_1_reg_2604;
wire   [0:0] negative_fu_1696_p3;
reg   [0:0] negative_reg_2609;
wire   [16:0] quotient_2_fu_1770_p3;
reg   [16:0] quotient_2_reg_2614;
wire   [63:0] zext_ln71_2_fu_863_p1;
wire    ap_block_pp0_stage0;
wire   [63:0] zext_ln71_4_fu_876_p1;
wire   [63:0] zext_ln71_6_fu_893_p1;
wire    ap_block_pp0_stage1;
wire   [63:0] zext_ln71_8_fu_905_p1;
wire   [63:0] zext_ln71_10_fu_917_p1;
wire    ap_block_pp0_stage2;
wire   [63:0] zext_ln71_12_fu_929_p1;
wire   [63:0] zext_ln71_14_fu_941_p1;
wire    ap_block_pp0_stage3;
wire   [63:0] zext_ln71_15_fu_953_p1;
wire   [63:0] zext_ln71_17_fu_965_p1;
wire    ap_block_pp0_stage4;
wire   [63:0] zext_ln71_19_fu_977_p1;
wire   [63:0] zext_ln71_21_fu_989_p1;
wire    ap_block_pp0_stage5;
wire   [63:0] zext_ln71_23_fu_1001_p1;
wire   [63:0] zext_ln71_25_fu_1013_p1;
wire    ap_block_pp0_stage6;
wire   [63:0] zext_ln71_27_fu_1025_p1;
wire   [63:0] zext_ln71_30_fu_1037_p1;
wire    ap_block_pp0_stage7;
wire   [63:0] zext_ln71_31_fu_1049_p1;
wire   [63:0] zext_ln71_fu_1065_p1;
wire    ap_block_pp0_stage8;
wire   [63:0] zext_ln71_1_fu_1077_p1;
wire   [63:0] zext_ln71_3_fu_1093_p1;
wire    ap_block_pp0_stage9;
wire   [63:0] zext_ln71_5_fu_1105_p1;
wire   [63:0] zext_ln71_7_fu_1134_p1;
wire    ap_block_pp0_stage10;
wire   [63:0] zext_ln71_9_fu_1146_p1;
wire   [63:0] zext_ln71_11_fu_1175_p1;
wire    ap_block_pp0_stage11;
wire   [63:0] zext_ln71_13_fu_1187_p1;
wire   [63:0] zext_ln71_16_fu_1228_p1;
wire    ap_block_pp0_stage12;
wire   [63:0] zext_ln71_18_fu_1240_p1;
wire   [63:0] zext_ln71_20_fu_1269_p1;
wire    ap_block_pp0_stage13;
wire   [63:0] zext_ln71_22_fu_1281_p1;
wire   [63:0] zext_ln71_24_fu_1335_p1;
wire    ap_block_pp0_stage14;
wire   [63:0] zext_ln71_26_fu_1347_p1;
wire   [63:0] zext_ln71_28_fu_1376_p1;
wire    ap_block_pp0_stage15;
wire   [63:0] zext_ln71_29_fu_1388_p1;
reg   [1:0] class_index_fu_184;
wire   [1:0] add_ln66_fu_845_p2;
wire    ap_loop_init;
reg   [1:0] ap_sig_allocacmp_class_index_1;
reg    weight_q_ce1_local;
reg   [5:0] weight_q_address1_local;
reg    weight_q_ce0_local;
reg   [5:0] weight_q_address0_local;
reg    bias_q_ce0_local;
reg    logits_q_we0_local;
wire   [17:0] add_ln78_fu_1797_p2;
reg    logits_q_ce0_local;
wire   [5:0] tmp_5_fu_855_p3;
wire   [5:0] tmp_7_fu_868_p3;
wire   [5:0] tmp_9_fu_886_p3;
wire   [5:0] tmp_1_fu_898_p3;
wire   [5:0] tmp_10_fu_910_p3;
wire   [5:0] tmp_12_fu_922_p3;
wire   [5:0] tmp_14_fu_934_p3;
wire   [5:0] tmp_15_fu_946_p3;
wire   [5:0] tmp_17_fu_958_p3;
wire   [5:0] tmp_19_fu_970_p3;
wire   [5:0] tmp_21_fu_982_p3;
wire   [5:0] tmp_23_fu_994_p3;
wire   [5:0] tmp_25_fu_1006_p3;
wire   [5:0] tmp_27_fu_1018_p3;
wire   [5:0] tmp_30_fu_1030_p3;
wire   [5:0] tmp_31_fu_1042_p3;
wire   [5:0] tmp_3_fu_1058_p3;
wire   [5:0] tmp_4_fu_1070_p3;
wire   [5:0] tmp_6_fu_1086_p3;
wire   [5:0] tmp_8_fu_1098_p3;
wire   [6:0] product_32_fu_1114_p1;
wire  signed [17:0] product_32_fu_1114_p2;
wire   [5:0] tmp_s_fu_1127_p3;
wire   [5:0] tmp_2_fu_1139_p3;
wire   [6:0] product_fu_1155_p1;
wire  signed [17:0] product_fu_1155_p2;
wire   [5:0] tmp_11_fu_1168_p3;
wire   [5:0] tmp_13_fu_1180_p3;
wire   [6:0] product_3_fu_1196_p1;
wire  signed [17:0] product_3_fu_1196_p2;
wire  signed [18:0] grp_fu_1811_p3;
wire  signed [19:0] sext_ln72_17_fu_1212_p1;
wire  signed [19:0] sext_ln72_16_fu_1209_p1;
wire   [5:0] tmp_16_fu_1221_p3;
wire   [5:0] tmp_18_fu_1233_p3;
wire   [6:0] product_5_fu_1249_p1;
wire  signed [17:0] product_5_fu_1249_p2;
wire   [5:0] tmp_20_fu_1262_p3;
wire   [5:0] tmp_22_fu_1274_p3;
wire   [6:0] product_7_fu_1290_p1;
wire  signed [17:0] product_7_fu_1290_p2;
wire  signed [18:0] grp_fu_1826_p3;
wire  signed [19:0] sext_ln72_20_fu_1309_p1;
wire  signed [19:0] sext_ln72_19_fu_1306_p1;
wire   [19:0] add_ln72_20_fu_1312_p2;
wire  signed [20:0] sext_ln72_21_fu_1318_p1;
wire  signed [20:0] sext_ln72_18_fu_1303_p1;
wire   [5:0] tmp_24_fu_1328_p3;
wire   [5:0] tmp_26_fu_1340_p3;
wire   [6:0] product_9_fu_1356_p1;
wire  signed [17:0] product_9_fu_1356_p2;
wire   [5:0] tmp_28_fu_1369_p3;
wire   [5:0] tmp_29_fu_1381_p3;
wire   [6:0] product_11_fu_1397_p1;
wire  signed [17:0] product_11_fu_1397_p2;
wire  signed [18:0] grp_fu_1841_p3;
wire  signed [19:0] sext_ln72_24_fu_1412_p1;
wire  signed [19:0] sext_ln72_23_fu_1409_p1;
wire   [6:0] product_13_fu_1429_p1;
wire  signed [17:0] product_13_fu_1429_p2;
wire   [6:0] product_16_fu_1445_p1;
wire  signed [17:0] product_16_fu_1445_p2;
wire  signed [18:0] grp_fu_1856_p3;
wire  signed [19:0] sext_ln72_27_fu_1466_p1;
wire  signed [19:0] sext_ln72_26_fu_1463_p1;
wire   [19:0] add_ln72_27_fu_1469_p2;
wire  signed [20:0] sext_ln72_28_fu_1475_p1;
wire  signed [20:0] sext_ln72_25_fu_1460_p1;
wire   [20:0] add_ln72_28_fu_1479_p2;
wire  signed [21:0] sext_ln72_29_fu_1485_p1;
wire  signed [21:0] sext_ln72_22_fu_1457_p1;
wire   [6:0] product_18_fu_1499_p1;
wire  signed [17:0] product_18_fu_1499_p2;
wire   [6:0] product_20_fu_1515_p1;
wire  signed [17:0] product_20_fu_1515_p2;
wire  signed [18:0] grp_fu_1871_p3;
wire  signed [19:0] sext_ln72_9_fu_1530_p1;
wire  signed [19:0] sext_ln72_8_fu_1527_p1;
wire   [6:0] product_22_fu_1542_p1;
wire  signed [17:0] product_22_fu_1542_p2;
wire   [6:0] product_24_fu_1557_p1;
wire  signed [17:0] product_24_fu_1557_p2;
wire  signed [18:0] grp_fu_1886_p3;
wire  signed [19:0] sext_ln72_12_fu_1575_p1;
wire  signed [19:0] sext_ln72_11_fu_1572_p1;
wire   [19:0] add_ln72_12_fu_1578_p2;
wire  signed [20:0] sext_ln72_13_fu_1584_p1;
wire  signed [20:0] sext_ln72_10_fu_1569_p1;
wire   [6:0] product_26_fu_1597_p1;
wire  signed [17:0] product_26_fu_1597_p2;
wire   [6:0] product_28_fu_1612_p1;
wire  signed [17:0] product_28_fu_1612_p2;
wire  signed [18:0] grp_fu_1901_p3;
wire  signed [19:0] sext_ln72_5_fu_1624_p1;
wire  signed [19:0] sext_ln72_4_fu_1621_p1;
wire   [6:0] product_29_fu_1636_p1;
wire  signed [17:0] product_29_fu_1636_p2;
wire  signed [18:0] grp_fu_1916_p3;
wire  signed [19:0] sext_ln72_2_fu_1648_p1;
wire  signed [19:0] sext_ln72_1_fu_1645_p1;
wire   [19:0] add_ln72_2_fu_1651_p2;
wire  signed [20:0] sext_ln72_6_fu_1661_p1;
wire  signed [20:0] sext_ln72_3_fu_1657_p1;
wire   [20:0] add_ln72_6_fu_1664_p2;
wire  signed [21:0] sext_ln72_14_fu_1674_p1;
wire  signed [21:0] sext_ln72_7_fu_1670_p1;
wire   [21:0] add_ln72_14_fu_1677_p2;
wire  signed [22:0] sext_ln72_30_fu_1687_p1;
wire  signed [22:0] sext_ln72_15_fu_1683_p1;
wire   [22:0] numerator_fu_1690_p2;
wire   [22:0] signed_magnitude_fu_1704_p2;
wire   [22:0] signed_magnitude_2_fu_1710_p3;
wire   [5:0] trunc_ln5_fu_1718_p1;
wire   [16:0] trunc_ln7_3_fu_1730_p4;
wire   [0:0] icmp_ln12_fu_1752_p2;
wire   [0:0] tmp_fu_1722_p3;
wire   [0:0] icmp_ln11_fu_1740_p2;
wire   [0:0] and_ln12_fu_1758_p2;
wire   [0:0] or_ln12_fu_1764_p2;
wire   [16:0] quotient_fu_1746_p2;
wire   [17:0] zext_ln17_fu_1778_p1;
wire   [17:0] sub_ln17_fu_1781_p2;
wire   [17:0] select_ln17_fu_1787_p3;
wire  signed [17:0] sext_ln78_fu_1794_p1;
wire   [6:0] grp_fu_1804_p1;
wire   [6:0] grp_fu_1811_p1;
wire   [6:0] grp_fu_1819_p1;
wire   [6:0] grp_fu_1826_p1;
wire   [6:0] grp_fu_1834_p1;
wire   [6:0] grp_fu_1841_p1;
wire   [6:0] grp_fu_1849_p1;
wire   [6:0] grp_fu_1856_p1;
wire   [6:0] grp_fu_1864_p1;
wire   [6:0] grp_fu_1871_p1;
wire   [6:0] grp_fu_1879_p1;
wire   [6:0] grp_fu_1886_p1;
wire   [6:0] grp_fu_1894_p1;
wire   [6:0] grp_fu_1901_p1;
wire   [6:0] grp_fu_1909_p1;
wire   [6:0] grp_fu_1916_p1;
reg    ap_done_reg;
wire    ap_continue_int;
reg    ap_done_int;
reg   [15:0] ap_NS_fsm;
wire    ap_block_pp0_stage0_subdone;
reg    ap_idle_pp0_1to1;
wire    ap_block_pp0_stage1_subdone;
wire    ap_block_pp0_stage2_subdone;
wire    ap_block_pp0_stage3_subdone;
wire    ap_block_pp0_stage4_subdone;
wire    ap_block_pp0_stage5_subdone;
wire    ap_block_pp0_stage6_subdone;
wire    ap_block_pp0_stage7_subdone;
wire    ap_block_pp0_stage8_subdone;
wire    ap_block_pp0_stage9_subdone;
wire    ap_block_pp0_stage11_subdone;
wire    ap_block_pp0_stage12_subdone;
wire    ap_block_pp0_stage13_subdone;
wire    ap_block_pp0_stage14_subdone;
wire    ap_enable_pp0;
wire    ap_start_int;
wire    ap_ready_sig;
wire    ap_done_sig;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_CS_fsm = 16'd1;
#0 ap_enable_reg_pp0_iter1 = 1'b0;
#0 ap_enable_reg_pp0_iter0_reg = 1'b0;
#0 class_index_fu_184 = 2'd0;
#0 ap_done_reg = 1'b0;
end

hybrid_lif_head_q12_6_mul_12s_7ns_18_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 12 ),
    .din1_WIDTH( 7 ),
    .dout_WIDTH( 18 ))
mul_12s_7ns_18_1_1_U14(
    .din0(weight_q_q1),
    .din1(product_32_fu_1114_p1),
    .dout(product_32_fu_1114_p2)
);

hybrid_lif_head_q12_6_mul_12s_7ns_18_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 12 ),
    .din1_WIDTH( 7 ),
    .dout_WIDTH( 18 ))
mul_12s_7ns_18_1_1_U15(
    .din0(reg_676),
    .din1(product_fu_1155_p1),
    .dout(product_fu_1155_p2)
);

hybrid_lif_head_q12_6_mul_12s_7ns_18_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 12 ),
    .din1_WIDTH( 7 ),
    .dout_WIDTH( 18 ))
mul_12s_7ns_18_1_1_U16(
    .din0(reg_676),
    .din1(product_3_fu_1196_p1),
    .dout(product_3_fu_1196_p2)
);

hybrid_lif_head_q12_6_mul_12s_7ns_18_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 12 ),
    .din1_WIDTH( 7 ),
    .dout_WIDTH( 18 ))
mul_12s_7ns_18_1_1_U17(
    .din0(reg_681),
    .din1(product_5_fu_1249_p1),
    .dout(product_5_fu_1249_p2)
);

hybrid_lif_head_q12_6_mul_12s_7ns_18_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 12 ),
    .din1_WIDTH( 7 ),
    .dout_WIDTH( 18 ))
mul_12s_7ns_18_1_1_U18(
    .din0(reg_676),
    .din1(product_7_fu_1290_p1),
    .dout(product_7_fu_1290_p2)
);

hybrid_lif_head_q12_6_mul_12s_7ns_18_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 12 ),
    .din1_WIDTH( 7 ),
    .dout_WIDTH( 18 ))
mul_12s_7ns_18_1_1_U19(
    .din0(reg_686),
    .din1(product_9_fu_1356_p1),
    .dout(product_9_fu_1356_p2)
);

hybrid_lif_head_q12_6_mul_12s_7ns_18_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 12 ),
    .din1_WIDTH( 7 ),
    .dout_WIDTH( 18 ))
mul_12s_7ns_18_1_1_U20(
    .din0(reg_681),
    .din1(product_11_fu_1397_p1),
    .dout(product_11_fu_1397_p2)
);

hybrid_lif_head_q12_6_mul_12s_7ns_18_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 12 ),
    .din1_WIDTH( 7 ),
    .dout_WIDTH( 18 ))
mul_12s_7ns_18_1_1_U21(
    .din0(reg_690),
    .din1(product_13_fu_1429_p1),
    .dout(product_13_fu_1429_p2)
);

hybrid_lif_head_q12_6_mul_12s_7ns_18_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 12 ),
    .din1_WIDTH( 7 ),
    .dout_WIDTH( 18 ))
mul_12s_7ns_18_1_1_U22(
    .din0(reg_676),
    .din1(product_16_fu_1445_p1),
    .dout(product_16_fu_1445_p2)
);

hybrid_lif_head_q12_6_mul_12s_7ns_18_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 12 ),
    .din1_WIDTH( 7 ),
    .dout_WIDTH( 18 ))
mul_12s_7ns_18_1_1_U23(
    .din0(reg_695),
    .din1(product_18_fu_1499_p1),
    .dout(product_18_fu_1499_p2)
);

hybrid_lif_head_q12_6_mul_12s_7ns_18_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 12 ),
    .din1_WIDTH( 7 ),
    .dout_WIDTH( 18 ))
mul_12s_7ns_18_1_1_U24(
    .din0(reg_699),
    .din1(product_20_fu_1515_p1),
    .dout(product_20_fu_1515_p2)
);

hybrid_lif_head_q12_6_mul_12s_7ns_18_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 12 ),
    .din1_WIDTH( 7 ),
    .dout_WIDTH( 18 ))
mul_12s_7ns_18_1_1_U25(
    .din0(weight_q_load_22_reg_2409),
    .din1(product_22_fu_1542_p1),
    .dout(product_22_fu_1542_p2)
);

hybrid_lif_head_q12_6_mul_12s_7ns_18_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 12 ),
    .din1_WIDTH( 7 ),
    .dout_WIDTH( 18 ))
mul_12s_7ns_18_1_1_U26(
    .din0(weight_q_load_24_reg_2444),
    .din1(product_24_fu_1557_p1),
    .dout(product_24_fu_1557_p2)
);

hybrid_lif_head_q12_6_mul_12s_7ns_18_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 12 ),
    .din1_WIDTH( 7 ),
    .dout_WIDTH( 18 ))
mul_12s_7ns_18_1_1_U27(
    .din0(weight_q_load_26_reg_2449),
    .din1(product_26_fu_1597_p1),
    .dout(product_26_fu_1597_p2)
);

hybrid_lif_head_q12_6_mul_12s_7ns_18_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 12 ),
    .din1_WIDTH( 7 ),
    .dout_WIDTH( 18 ))
mul_12s_7ns_18_1_1_U28(
    .din0(weight_q_load_28_reg_2474),
    .din1(product_28_fu_1612_p1),
    .dout(product_28_fu_1612_p2)
);

hybrid_lif_head_q12_6_mul_12s_7ns_18_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 12 ),
    .din1_WIDTH( 7 ),
    .dout_WIDTH( 18 ))
mul_12s_7ns_18_1_1_U29(
    .din0(weight_q_load_29_reg_2479),
    .din1(product_29_fu_1636_p1),
    .dout(product_29_fu_1636_p2)
);

hybrid_lif_head_q12_6_mac_muladd_12s_7ns_18s_19_4_1 #(
    .ID( 1 ),
    .NUM_STAGE( 4 ),
    .din0_WIDTH( 12 ),
    .din1_WIDTH( 7 ),
    .din2_WIDTH( 18 ),
    .dout_WIDTH( 19 ))
mac_muladd_12s_7ns_18s_19_4_1_U30(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(reg_676),
    .din1(grp_fu_1804_p1),
    .din2(product_32_fu_1114_p2),
    .ce(1'b1),
    .dout(grp_fu_1804_p3)
);

hybrid_lif_head_q12_6_mac_muladd_12s_7ns_18s_19_4_1 #(
    .ID( 1 ),
    .NUM_STAGE( 4 ),
    .din0_WIDTH( 12 ),
    .din1_WIDTH( 7 ),
    .din2_WIDTH( 18 ),
    .dout_WIDTH( 19 ))
mac_muladd_12s_7ns_18s_19_4_1_U31(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(reg_671),
    .din1(grp_fu_1811_p1),
    .din2(product_fu_1155_p2),
    .ce(1'b1),
    .dout(grp_fu_1811_p3)
);

hybrid_lif_head_q12_6_mac_muladd_12s_7ns_18s_19_4_1 #(
    .ID( 1 ),
    .NUM_STAGE( 4 ),
    .din0_WIDTH( 12 ),
    .din1_WIDTH( 7 ),
    .din2_WIDTH( 18 ),
    .dout_WIDTH( 19 ))
mac_muladd_12s_7ns_18s_19_4_1_U32(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(reg_681),
    .din1(grp_fu_1819_p1),
    .din2(product_3_fu_1196_p2),
    .ce(1'b1),
    .dout(grp_fu_1819_p3)
);

hybrid_lif_head_q12_6_mac_muladd_12s_7ns_18s_19_4_1 #(
    .ID( 1 ),
    .NUM_STAGE( 4 ),
    .din0_WIDTH( 12 ),
    .din1_WIDTH( 7 ),
    .din2_WIDTH( 18 ),
    .dout_WIDTH( 19 ))
mac_muladd_12s_7ns_18s_19_4_1_U33(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(reg_686),
    .din1(grp_fu_1826_p1),
    .din2(product_5_fu_1249_p2),
    .ce(1'b1),
    .dout(grp_fu_1826_p3)
);

hybrid_lif_head_q12_6_mac_muladd_12s_7ns_18s_19_4_1 #(
    .ID( 1 ),
    .NUM_STAGE( 4 ),
    .din0_WIDTH( 12 ),
    .din1_WIDTH( 7 ),
    .din2_WIDTH( 18 ),
    .dout_WIDTH( 19 ))
mac_muladd_12s_7ns_18s_19_4_1_U34(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(reg_690),
    .din1(grp_fu_1834_p1),
    .din2(product_7_fu_1290_p2),
    .ce(1'b1),
    .dout(grp_fu_1834_p3)
);

hybrid_lif_head_q12_6_mac_muladd_12s_7ns_18s_19_4_1 #(
    .ID( 1 ),
    .NUM_STAGE( 4 ),
    .din0_WIDTH( 12 ),
    .din1_WIDTH( 7 ),
    .din2_WIDTH( 18 ),
    .dout_WIDTH( 19 ))
mac_muladd_12s_7ns_18s_19_4_1_U35(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(reg_695),
    .din1(grp_fu_1841_p1),
    .din2(product_9_fu_1356_p2),
    .ce(1'b1),
    .dout(grp_fu_1841_p3)
);

hybrid_lif_head_q12_6_mac_muladd_12s_7ns_18s_19_4_1 #(
    .ID( 1 ),
    .NUM_STAGE( 4 ),
    .din0_WIDTH( 12 ),
    .din1_WIDTH( 7 ),
    .din2_WIDTH( 18 ),
    .dout_WIDTH( 19 ))
mac_muladd_12s_7ns_18s_19_4_1_U36(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(reg_699),
    .din1(grp_fu_1849_p1),
    .din2(product_11_fu_1397_p2),
    .ce(1'b1),
    .dout(grp_fu_1849_p3)
);

hybrid_lif_head_q12_6_mac_muladd_12s_7ns_18s_19_4_1 #(
    .ID( 1 ),
    .NUM_STAGE( 4 ),
    .din0_WIDTH( 12 ),
    .din1_WIDTH( 7 ),
    .din2_WIDTH( 18 ),
    .dout_WIDTH( 19 ))
mac_muladd_12s_7ns_18s_19_4_1_U37(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(reg_671),
    .din1(grp_fu_1856_p1),
    .din2(product_13_fu_1429_p2),
    .ce(1'b1),
    .dout(grp_fu_1856_p3)
);

hybrid_lif_head_q12_6_mac_muladd_12s_7ns_18s_19_4_1 #(
    .ID( 1 ),
    .NUM_STAGE( 4 ),
    .din0_WIDTH( 12 ),
    .din1_WIDTH( 7 ),
    .din2_WIDTH( 18 ),
    .dout_WIDTH( 19 ))
mac_muladd_12s_7ns_18s_19_4_1_U38(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(weight_q_load_15_reg_2184),
    .din1(grp_fu_1864_p1),
    .din2(product_16_fu_1445_p2),
    .ce(1'b1),
    .dout(grp_fu_1864_p3)
);

hybrid_lif_head_q12_6_mac_muladd_12s_7ns_18s_19_4_1 #(
    .ID( 1 ),
    .NUM_STAGE( 4 ),
    .din0_WIDTH( 12 ),
    .din1_WIDTH( 7 ),
    .din2_WIDTH( 18 ),
    .dout_WIDTH( 19 ))
mac_muladd_12s_7ns_18s_19_4_1_U39(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(weight_q_load_17_reg_2199),
    .din1(grp_fu_1871_p1),
    .din2(product_18_fu_1499_p2),
    .ce(1'b1),
    .dout(grp_fu_1871_p3)
);

hybrid_lif_head_q12_6_mac_muladd_12s_7ns_18s_19_4_1 #(
    .ID( 1 ),
    .NUM_STAGE( 4 ),
    .din0_WIDTH( 12 ),
    .din1_WIDTH( 7 ),
    .din2_WIDTH( 18 ),
    .dout_WIDTH( 19 ))
mac_muladd_12s_7ns_18s_19_4_1_U40(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(weight_q_load_19_reg_2204),
    .din1(grp_fu_1879_p1),
    .din2(product_20_fu_1515_p2),
    .ce(1'b1),
    .dout(grp_fu_1879_p3)
);

hybrid_lif_head_q12_6_mac_muladd_12s_7ns_18s_19_4_1 #(
    .ID( 1 ),
    .NUM_STAGE( 4 ),
    .din0_WIDTH( 12 ),
    .din1_WIDTH( 7 ),
    .din2_WIDTH( 18 ),
    .dout_WIDTH( 19 ))
mac_muladd_12s_7ns_18s_19_4_1_U41(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(weight_q_load_21_reg_2219),
    .din1(grp_fu_1886_p1),
    .din2(product_22_fu_1542_p2),
    .ce(1'b1),
    .dout(grp_fu_1886_p3)
);

hybrid_lif_head_q12_6_mac_muladd_12s_7ns_18s_19_4_1 #(
    .ID( 1 ),
    .NUM_STAGE( 4 ),
    .din0_WIDTH( 12 ),
    .din1_WIDTH( 7 ),
    .din2_WIDTH( 18 ),
    .dout_WIDTH( 19 ))
mac_muladd_12s_7ns_18s_19_4_1_U42(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(weight_q_load_23_reg_2224),
    .din1(grp_fu_1894_p1),
    .din2(product_24_fu_1557_p2),
    .ce(1'b1),
    .dout(grp_fu_1894_p3)
);

hybrid_lif_head_q12_6_mac_muladd_12s_7ns_18s_19_4_1 #(
    .ID( 1 ),
    .NUM_STAGE( 4 ),
    .din0_WIDTH( 12 ),
    .din1_WIDTH( 7 ),
    .din2_WIDTH( 18 ),
    .dout_WIDTH( 19 ))
mac_muladd_12s_7ns_18s_19_4_1_U43(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(weight_q_load_25_reg_2244),
    .din1(grp_fu_1901_p1),
    .din2(product_26_fu_1597_p2),
    .ce(1'b1),
    .dout(grp_fu_1901_p3)
);

hybrid_lif_head_q12_6_mac_muladd_12s_7ns_18s_19_4_1 #(
    .ID( 1 ),
    .NUM_STAGE( 4 ),
    .din0_WIDTH( 12 ),
    .din1_WIDTH( 7 ),
    .din2_WIDTH( 18 ),
    .dout_WIDTH( 19 ))
mac_muladd_12s_7ns_18s_19_4_1_U44(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(weight_q_load_27_reg_2249),
    .din1(grp_fu_1909_p1),
    .din2(product_28_fu_1612_p2),
    .ce(1'b1),
    .dout(grp_fu_1909_p3)
);

hybrid_lif_head_q12_6_mac_muladd_12s_7ns_18s_19_4_1 #(
    .ID( 1 ),
    .NUM_STAGE( 4 ),
    .din0_WIDTH( 12 ),
    .din1_WIDTH( 7 ),
    .din2_WIDTH( 18 ),
    .dout_WIDTH( 19 ))
mac_muladd_12s_7ns_18s_19_4_1_U45(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(weight_q_load_30_reg_2269),
    .din1(grp_fu_1916_p1),
    .din2(product_29_fu_1636_p2),
    .ce(1'b1),
    .dout(grp_fu_1916_p3)
);

hybrid_lif_head_q12_6_flow_control_loop_pipe_sequential_init flow_control_loop_pipe_sequential_init_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(ap_start),
    .ap_ready(ap_ready_sig),
    .ap_done(ap_done_sig),
    .ap_start_int(ap_start_int),
    .ap_loop_init(ap_loop_init),
    .ap_ready_int(ap_ready_int),
    .ap_loop_exit_ready(ap_condition_exit_pp0_iter0_stage10),
    .ap_loop_exit_done(ap_done_int),
    .ap_continue_int(ap_continue_int),
    .ap_done_int(ap_done_int)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_pp0_stage0;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_done_reg <= 1'b0;
    end else begin
        if ((ap_continue_int == 1'b1)) begin
            ap_done_reg <= 1'b0;
        end else if (((ap_loop_exit_ready == 1'b1) & (1'b0 == ap_block_pp0_stage10_subdone) & (1'b1 == ap_CS_fsm_pp0_stage10))) begin
            ap_done_reg <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter0_reg <= 1'b0;
    end else begin
        if ((1'b1 == ap_condition_exit_pp0_iter0_stage10)) begin
            ap_enable_reg_pp0_iter0_reg <= 1'b0;
        end else if ((1'b1 == ap_CS_fsm_pp0_stage0)) begin
            ap_enable_reg_pp0_iter0_reg <= ap_start_int;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter1 <= 1'b0;
    end else begin
        if (((1'b0 == ap_block_pp0_stage10_subdone) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage10))) begin
            ap_enable_reg_pp0_iter1 <= 1'b0;
        end else if (((1'b0 == ap_block_pp0_stage15_subdone) & (1'b1 == ap_CS_fsm_pp0_stage15))) begin
            ap_enable_reg_pp0_iter1 <= ap_enable_reg_pp0_iter0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        if (((ap_enable_reg_pp0_iter0 == 1'b1) & (icmp_ln66_fu_839_p2 == 1'd0))) begin
            class_index_fu_184 <= add_ln66_fu_845_p2;
        end else if ((ap_loop_init == 1'b1)) begin
            class_index_fu_184 <= 2'd0;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((ap_enable_reg_pp0_iter0_reg == 1'b1)) begin
        if (((1'b0 == ap_block_pp0_stage8_11001) & (1'b1 == ap_CS_fsm_pp0_stage8))) begin
            reg_671 <= weight_q_q0;
        end else if (((1'b0 == ap_block_pp0_stage1_11001) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
            reg_671 <= weight_q_q1;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((((ap_enable_reg_pp0_iter0_reg == 1'b1) & (1'b0 == ap_block_pp0_stage13_11001) & (1'b1 == ap_CS_fsm_pp0_stage13)) | ((ap_enable_reg_pp0_iter0_reg == 1'b1) & (1'b0 == ap_block_pp0_stage11_11001) & (1'b1 == ap_CS_fsm_pp0_stage11)) | ((ap_enable_reg_pp0_iter0_reg == 1'b1) & (1'b0 == ap_block_pp0_stage10_11001) & (1'b1 == ap_CS_fsm_pp0_stage10)))) begin
        reg_676 <= weight_q_q1;
    end else if ((((ap_enable_reg_pp0_iter0_reg == 1'b1) & (1'b0 == ap_block_pp0_stage9_11001) & (1'b1 == ap_CS_fsm_pp0_stage9)) | ((ap_enable_reg_pp0_iter0_reg == 1'b1) & (1'b0 == ap_block_pp0_stage1_11001) & (1'b1 == ap_CS_fsm_pp0_stage1)))) begin
        reg_676 <= weight_q_q0;
    end
end

always @ (posedge ap_clk) begin
    if (((ap_enable_reg_pp0_iter0_reg == 1'b1) & (1'b0 == ap_block_pp0_stage10_11001) & (1'b1 == ap_CS_fsm_pp0_stage10))) begin
        reg_681 <= weight_q_q0;
    end else if ((((ap_enable_reg_pp0_iter0_reg == 1'b1) & (1'b0 == ap_block_pp0_stage12_11001) & (1'b1 == ap_CS_fsm_pp0_stage12)) | ((ap_enable_reg_pp0_iter0_reg == 1'b1) & (1'b0 == ap_block_pp0_stage2_11001) & (1'b1 == ap_CS_fsm_pp0_stage2)))) begin
        reg_681 <= weight_q_q1;
    end
end

always @ (posedge ap_clk) begin
    if ((ap_enable_reg_pp0_iter0_reg == 1'b1)) begin
        if (((1'b0 == ap_block_pp0_stage12_11001) & (1'b1 == ap_CS_fsm_pp0_stage12))) begin
            reg_690 <= weight_q_q0;
        end else if (((1'b0 == ap_block_pp0_stage3_11001) & (1'b1 == ap_CS_fsm_pp0_stage3))) begin
            reg_690 <= weight_q_q1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage4_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage4))) begin
        add_ln72_10_reg_2554 <= grp_fu_1879_p3;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage5_11001) & (1'b1 == ap_CS_fsm_pp0_stage5))) begin
        add_ln72_13_reg_2569 <= add_ln72_13_fu_1588_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((ap_enable_reg_pp0_iter0_reg == 1'b1) & (1'b0 == ap_block_pp0_stage10_11001) & (1'b1 == ap_CS_fsm_pp0_stage10))) begin
        add_ln72_16_reg_2314 <= grp_fu_1804_p3;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage11_11001) & (1'b1 == ap_CS_fsm_pp0_stage11))) begin
        add_ln72_17_reg_2339 <= add_ln72_17_fu_1215_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((ap_enable_reg_pp0_iter0_reg == 1'b1) & (1'b0 == ap_block_pp0_stage12_11001) & (1'b1 == ap_CS_fsm_pp0_stage12))) begin
        add_ln72_18_reg_2364 <= grp_fu_1819_p3;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage8_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage8))) begin
        add_ln72_1_reg_2604 <= grp_fu_1909_p3;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage13_11001) & (1'b1 == ap_CS_fsm_pp0_stage13))) begin
        add_ln72_21_reg_2389 <= add_ln72_21_fu_1322_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((ap_enable_reg_pp0_iter0_reg == 1'b1) & (1'b0 == ap_block_pp0_stage14_11001) & (1'b1 == ap_CS_fsm_pp0_stage14))) begin
        add_ln72_22_reg_2419 <= grp_fu_1834_p3;
        weight_q_load_22_reg_2409 <= weight_q_q0;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage15_11001) & (1'b1 == ap_CS_fsm_pp0_stage15))) begin
        add_ln72_24_reg_2454 <= add_ln72_24_fu_1415_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        add_ln72_25_reg_2484 <= grp_fu_1849_p3;
        weight_q_load_28_reg_2474 <= weight_q_q1;
        weight_q_load_29_reg_2479 <= weight_q_q0;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage1_11001) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
        add_ln72_29_reg_2504 <= add_ln72_29_fu_1489_p2;
        bias_q_load_reg_2509 <= bias_q_q0;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage6_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage6))) begin
        add_ln72_3_reg_2584 <= grp_fu_1894_p3;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage7_11001) & (1'b1 == ap_CS_fsm_pp0_stage7))) begin
        add_ln72_5_reg_2594 <= add_ln72_5_fu_1627_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage2_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage2))) begin
        add_ln72_7_reg_2524 <= grp_fu_1864_p3;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage3_11001) & (1'b1 == ap_CS_fsm_pp0_stage3))) begin
        add_ln72_9_reg_2539 <= add_ln72_9_fu_1533_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        class_index_1_reg_2091 <= ap_sig_allocacmp_class_index_1;
        conv_i104_10_i_cast_reg_2036[6 : 0] <= conv_i104_10_i_cast_fu_787_p1[6 : 0];
        conv_i104_11_i_cast_reg_2031[6 : 0] <= conv_i104_11_i_cast_fu_783_p1[6 : 0];
        conv_i104_12_i_cast_reg_2026[6 : 0] <= conv_i104_12_i_cast_fu_779_p1[6 : 0];
        conv_i104_13_i_cast_reg_2021[6 : 0] <= conv_i104_13_i_cast_fu_775_p1[6 : 0];
        conv_i104_14_i_cast_reg_2016[6 : 0] <= conv_i104_14_i_cast_fu_771_p1[6 : 0];
        conv_i104_15_i_cast_reg_2011[6 : 0] <= conv_i104_15_i_cast_fu_767_p1[6 : 0];
        conv_i104_16_i_cast_reg_2006[6 : 0] <= conv_i104_16_i_cast_fu_763_p1[6 : 0];
        conv_i104_17_i_cast_reg_2001[6 : 0] <= conv_i104_17_i_cast_fu_759_p1[6 : 0];
        conv_i104_18_i_cast_reg_1996[6 : 0] <= conv_i104_18_i_cast_fu_755_p1[6 : 0];
        conv_i104_19_i_cast_reg_1991[6 : 0] <= conv_i104_19_i_cast_fu_751_p1[6 : 0];
        conv_i104_1_i_cast_reg_2081[6 : 0] <= conv_i104_1_i_cast_fu_823_p1[6 : 0];
        conv_i104_20_i_cast_reg_1986[6 : 0] <= conv_i104_20_i_cast_fu_747_p1[6 : 0];
        conv_i104_21_i_cast_reg_1981[6 : 0] <= conv_i104_21_i_cast_fu_743_p1[6 : 0];
        conv_i104_22_i_cast_reg_1976[6 : 0] <= conv_i104_22_i_cast_fu_739_p1[6 : 0];
        conv_i104_23_i_cast_reg_1971[6 : 0] <= conv_i104_23_i_cast_fu_735_p1[6 : 0];
        conv_i104_24_i_cast_reg_1966[6 : 0] <= conv_i104_24_i_cast_fu_731_p1[6 : 0];
        conv_i104_25_i_cast_reg_1961[6 : 0] <= conv_i104_25_i_cast_fu_727_p1[6 : 0];
        conv_i104_26_i_cast_reg_1956[6 : 0] <= conv_i104_26_i_cast_fu_723_p1[6 : 0];
        conv_i104_27_i_cast_reg_1951[6 : 0] <= conv_i104_27_i_cast_fu_719_p1[6 : 0];
        conv_i104_28_i_cast_reg_1946[6 : 0] <= conv_i104_28_i_cast_fu_715_p1[6 : 0];
        conv_i104_29_i_cast_reg_1941[6 : 0] <= conv_i104_29_i_cast_fu_711_p1[6 : 0];
        conv_i104_2_i_cast_reg_2076[6 : 0] <= conv_i104_2_i_cast_fu_819_p1[6 : 0];
        conv_i104_30_i_cast_reg_1936[6 : 0] <= conv_i104_30_i_cast_fu_707_p1[6 : 0];
        conv_i104_31_i_cast_reg_1931[6 : 0] <= conv_i104_31_i_cast_fu_703_p1[6 : 0];
        conv_i104_3_i_cast_reg_2071[6 : 0] <= conv_i104_3_i_cast_fu_815_p1[6 : 0];
        conv_i104_4_i_cast_reg_2066[6 : 0] <= conv_i104_4_i_cast_fu_811_p1[6 : 0];
        conv_i104_5_i_cast_reg_2061[6 : 0] <= conv_i104_5_i_cast_fu_807_p1[6 : 0];
        conv_i104_6_i_cast_reg_2056[6 : 0] <= conv_i104_6_i_cast_fu_803_p1[6 : 0];
        conv_i104_7_i_cast_reg_2051[6 : 0] <= conv_i104_7_i_cast_fu_799_p1[6 : 0];
        conv_i104_8_i_cast_reg_2046[6 : 0] <= conv_i104_8_i_cast_fu_795_p1[6 : 0];
        conv_i104_9_i_cast_reg_2041[6 : 0] <= conv_i104_9_i_cast_fu_791_p1[6 : 0];
        conv_i104_i_cast_reg_2086[6 : 0] <= conv_i104_i_cast_fu_827_p1[6 : 0];
        icmp_ln66_reg_2096 <= icmp_ln66_fu_839_p2;
        trunc_ln66_reg_2100 <= trunc_ln66_fu_851_p1;
        zext_ln66_reg_2459[1 : 0] <= zext_ln66_fu_1421_p1[1 : 0];
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage9_11001) & (1'b1 == ap_CS_fsm_pp0_stage9))) begin
        negative_reg_2609 <= numerator_fu_1690_p2[32'd22];
        quotient_2_reg_2614 <= quotient_2_fu_1770_p3;
    end
end

always @ (posedge ap_clk) begin
    if ((((ap_enable_reg_pp0_iter0_reg == 1'b1) & (1'b0 == ap_block_pp0_stage2_11001) & (1'b1 == ap_CS_fsm_pp0_stage2)) | ((ap_enable_reg_pp0_iter0_reg == 1'b1) & (1'b0 == ap_block_pp0_stage11_11001) & (1'b1 == ap_CS_fsm_pp0_stage11)))) begin
        reg_686 <= weight_q_q0;
    end
end

always @ (posedge ap_clk) begin
    if ((((ap_enable_reg_pp0_iter0_reg == 1'b1) & (1'b0 == ap_block_pp0_stage3_11001) & (1'b1 == ap_CS_fsm_pp0_stage3)) | ((ap_enable_reg_pp0_iter0_reg == 1'b1) & (1'b0 == ap_block_pp0_stage13_11001) & (1'b1 == ap_CS_fsm_pp0_stage13)))) begin
        reg_695 <= weight_q_q0;
    end
end

always @ (posedge ap_clk) begin
    if ((((ap_enable_reg_pp0_iter0_reg == 1'b1) & (1'b0 == ap_block_pp0_stage14_11001) & (1'b1 == ap_CS_fsm_pp0_stage14)) | ((ap_enable_reg_pp0_iter0_reg == 1'b1) & (1'b0 == ap_block_pp0_stage4_11001) & (1'b1 == ap_CS_fsm_pp0_stage4)))) begin
        reg_699 <= weight_q_q1;
    end
end

always @ (posedge ap_clk) begin
    if (((ap_enable_reg_pp0_iter0_reg == 1'b1) & (1'b0 == ap_block_pp0_stage4_11001) & (1'b1 == ap_CS_fsm_pp0_stage4))) begin
        weight_q_load_15_reg_2184 <= weight_q_q0;
    end
end

always @ (posedge ap_clk) begin
    if (((ap_enable_reg_pp0_iter0_reg == 1'b1) & (1'b0 == ap_block_pp0_stage5_11001) & (1'b1 == ap_CS_fsm_pp0_stage5))) begin
        weight_q_load_17_reg_2199 <= weight_q_q1;
        weight_q_load_19_reg_2204 <= weight_q_q0;
    end
end

always @ (posedge ap_clk) begin
    if (((ap_enable_reg_pp0_iter0_reg == 1'b1) & (1'b0 == ap_block_pp0_stage6_11001) & (1'b1 == ap_CS_fsm_pp0_stage6))) begin
        weight_q_load_21_reg_2219 <= weight_q_q1;
        weight_q_load_23_reg_2224 <= weight_q_q0;
    end
end

always @ (posedge ap_clk) begin
    if (((ap_enable_reg_pp0_iter0_reg == 1'b1) & (1'b0 == ap_block_pp0_stage15_11001) & (1'b1 == ap_CS_fsm_pp0_stage15))) begin
        weight_q_load_24_reg_2444 <= weight_q_q1;
        weight_q_load_26_reg_2449 <= weight_q_q0;
    end
end

always @ (posedge ap_clk) begin
    if (((ap_enable_reg_pp0_iter0_reg == 1'b1) & (1'b0 == ap_block_pp0_stage7_11001) & (1'b1 == ap_CS_fsm_pp0_stage7))) begin
        weight_q_load_25_reg_2244 <= weight_q_q1;
        weight_q_load_27_reg_2249 <= weight_q_q0;
    end
end

always @ (posedge ap_clk) begin
    if (((ap_enable_reg_pp0_iter0_reg == 1'b1) & (1'b0 == ap_block_pp0_stage8_11001) & (1'b1 == ap_CS_fsm_pp0_stage8))) begin
        weight_q_load_30_reg_2269 <= weight_q_q1;
    end
end

always @ (*) begin
    if (((icmp_ln66_reg_2096 == 1'd1) & (ap_enable_reg_pp0_iter0_reg == 1'b1) & (1'b0 == ap_block_pp0_stage10_subdone) & (1'b1 == ap_CS_fsm_pp0_stage10))) begin
        ap_condition_exit_pp0_iter0_stage10 = 1'b1;
    end else begin
        ap_condition_exit_pp0_iter0_stage10 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_loop_exit_ready == 1'b1) & (1'b0 == ap_block_pp0_stage10_subdone) & (1'b1 == ap_CS_fsm_pp0_stage10))) begin
        ap_done_int = 1'b1;
    end else begin
        ap_done_int = ap_done_reg;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_pp0_stage0)) begin
        ap_enable_reg_pp0_iter0 = ap_start_int;
    end else begin
        ap_enable_reg_pp0_iter0 = ap_enable_reg_pp0_iter0_reg;
    end
end

always @ (*) begin
    if (((ap_idle_pp0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (ap_start_int == 1'b0))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter1 == 1'b0) & (ap_enable_reg_pp0_iter0 == 1'b0))) begin
        ap_idle_pp0 = 1'b1;
    end else begin
        ap_idle_pp0 = 1'b0;
    end
end

always @ (*) begin
    if ((ap_enable_reg_pp0_iter1 == 1'b0)) begin
        ap_idle_pp0_1to1 = 1'b1;
    end else begin
        ap_idle_pp0_1to1 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter0_reg == 1'b1) & (1'b0 == ap_block_pp0_stage15_subdone) & (1'b1 == ap_CS_fsm_pp0_stage15))) begin
        ap_ready_int = 1'b1;
    end else begin
        ap_ready_int = 1'b0;
    end
end

always @ (*) begin
    if (((ap_loop_init == 1'b1) & (1'b0 == ap_block_pp0_stage0) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_sig_allocacmp_class_index_1 = 2'd0;
    end else begin
        ap_sig_allocacmp_class_index_1 = class_index_fu_184;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        bias_q_ce0_local = 1'b1;
    end else begin
        bias_q_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage10_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage10))) begin
        logits_q_ce0_local = 1'b1;
    end else begin
        logits_q_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage10_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage10))) begin
        logits_q_we0_local = 1'b1;
    end else begin
        logits_q_we0_local = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter0_reg == 1'b1) & (1'b0 == ap_block_pp0_stage15) & (1'b1 == ap_CS_fsm_pp0_stage15))) begin
        weight_q_address0_local = zext_ln71_29_fu_1388_p1;
    end else if (((ap_enable_reg_pp0_iter0_reg == 1'b1) & (1'b0 == ap_block_pp0_stage14) & (1'b1 == ap_CS_fsm_pp0_stage14))) begin
        weight_q_address0_local = zext_ln71_26_fu_1347_p1;
    end else if (((ap_enable_reg_pp0_iter0_reg == 1'b1) & (1'b0 == ap_block_pp0_stage13) & (1'b1 == ap_CS_fsm_pp0_stage13))) begin
        weight_q_address0_local = zext_ln71_22_fu_1281_p1;
    end else if (((ap_enable_reg_pp0_iter0_reg == 1'b1) & (1'b0 == ap_block_pp0_stage12) & (1'b1 == ap_CS_fsm_pp0_stage12))) begin
        weight_q_address0_local = zext_ln71_18_fu_1240_p1;
    end else if (((ap_enable_reg_pp0_iter0_reg == 1'b1) & (1'b0 == ap_block_pp0_stage11) & (1'b1 == ap_CS_fsm_pp0_stage11))) begin
        weight_q_address0_local = zext_ln71_13_fu_1187_p1;
    end else if (((ap_enable_reg_pp0_iter0_reg == 1'b1) & (1'b0 == ap_block_pp0_stage10) & (1'b1 == ap_CS_fsm_pp0_stage10))) begin
        weight_q_address0_local = zext_ln71_9_fu_1146_p1;
    end else if (((ap_enable_reg_pp0_iter0_reg == 1'b1) & (1'b0 == ap_block_pp0_stage9) & (1'b1 == ap_CS_fsm_pp0_stage9))) begin
        weight_q_address0_local = zext_ln71_5_fu_1105_p1;
    end else if (((ap_enable_reg_pp0_iter0_reg == 1'b1) & (1'b0 == ap_block_pp0_stage8) & (1'b1 == ap_CS_fsm_pp0_stage8))) begin
        weight_q_address0_local = zext_ln71_1_fu_1077_p1;
    end else if (((ap_enable_reg_pp0_iter0_reg == 1'b1) & (1'b0 == ap_block_pp0_stage7) & (1'b1 == ap_CS_fsm_pp0_stage7))) begin
        weight_q_address0_local = zext_ln71_31_fu_1049_p1;
    end else if (((ap_enable_reg_pp0_iter0_reg == 1'b1) & (1'b0 == ap_block_pp0_stage6) & (1'b1 == ap_CS_fsm_pp0_stage6))) begin
        weight_q_address0_local = zext_ln71_27_fu_1025_p1;
    end else if (((ap_enable_reg_pp0_iter0_reg == 1'b1) & (1'b0 == ap_block_pp0_stage5) & (1'b1 == ap_CS_fsm_pp0_stage5))) begin
        weight_q_address0_local = zext_ln71_23_fu_1001_p1;
    end else if (((ap_enable_reg_pp0_iter0_reg == 1'b1) & (1'b0 == ap_block_pp0_stage4) & (1'b1 == ap_CS_fsm_pp0_stage4))) begin
        weight_q_address0_local = zext_ln71_19_fu_977_p1;
    end else if (((ap_enable_reg_pp0_iter0_reg == 1'b1) & (1'b0 == ap_block_pp0_stage3) & (1'b1 == ap_CS_fsm_pp0_stage3))) begin
        weight_q_address0_local = zext_ln71_15_fu_953_p1;
    end else if (((ap_enable_reg_pp0_iter0_reg == 1'b1) & (1'b0 == ap_block_pp0_stage2) & (1'b1 == ap_CS_fsm_pp0_stage2))) begin
        weight_q_address0_local = zext_ln71_12_fu_929_p1;
    end else if (((ap_enable_reg_pp0_iter0_reg == 1'b1) & (1'b0 == ap_block_pp0_stage1) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
        weight_q_address0_local = zext_ln71_8_fu_905_p1;
    end else if (((1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        weight_q_address0_local = zext_ln71_4_fu_876_p1;
    end else begin
        weight_q_address0_local = 'bx;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter0_reg == 1'b1) & (1'b0 == ap_block_pp0_stage15) & (1'b1 == ap_CS_fsm_pp0_stage15))) begin
        weight_q_address1_local = zext_ln71_28_fu_1376_p1;
    end else if (((ap_enable_reg_pp0_iter0_reg == 1'b1) & (1'b0 == ap_block_pp0_stage14) & (1'b1 == ap_CS_fsm_pp0_stage14))) begin
        weight_q_address1_local = zext_ln71_24_fu_1335_p1;
    end else if (((ap_enable_reg_pp0_iter0_reg == 1'b1) & (1'b0 == ap_block_pp0_stage13) & (1'b1 == ap_CS_fsm_pp0_stage13))) begin
        weight_q_address1_local = zext_ln71_20_fu_1269_p1;
    end else if (((ap_enable_reg_pp0_iter0_reg == 1'b1) & (1'b0 == ap_block_pp0_stage12) & (1'b1 == ap_CS_fsm_pp0_stage12))) begin
        weight_q_address1_local = zext_ln71_16_fu_1228_p1;
    end else if (((ap_enable_reg_pp0_iter0_reg == 1'b1) & (1'b0 == ap_block_pp0_stage11) & (1'b1 == ap_CS_fsm_pp0_stage11))) begin
        weight_q_address1_local = zext_ln71_11_fu_1175_p1;
    end else if (((ap_enable_reg_pp0_iter0_reg == 1'b1) & (1'b0 == ap_block_pp0_stage10) & (1'b1 == ap_CS_fsm_pp0_stage10))) begin
        weight_q_address1_local = zext_ln71_7_fu_1134_p1;
    end else if (((ap_enable_reg_pp0_iter0_reg == 1'b1) & (1'b0 == ap_block_pp0_stage9) & (1'b1 == ap_CS_fsm_pp0_stage9))) begin
        weight_q_address1_local = zext_ln71_3_fu_1093_p1;
    end else if (((ap_enable_reg_pp0_iter0_reg == 1'b1) & (1'b0 == ap_block_pp0_stage8) & (1'b1 == ap_CS_fsm_pp0_stage8))) begin
        weight_q_address1_local = zext_ln71_fu_1065_p1;
    end else if (((ap_enable_reg_pp0_iter0_reg == 1'b1) & (1'b0 == ap_block_pp0_stage7) & (1'b1 == ap_CS_fsm_pp0_stage7))) begin
        weight_q_address1_local = zext_ln71_30_fu_1037_p1;
    end else if (((ap_enable_reg_pp0_iter0_reg == 1'b1) & (1'b0 == ap_block_pp0_stage6) & (1'b1 == ap_CS_fsm_pp0_stage6))) begin
        weight_q_address1_local = zext_ln71_25_fu_1013_p1;
    end else if (((ap_enable_reg_pp0_iter0_reg == 1'b1) & (1'b0 == ap_block_pp0_stage5) & (1'b1 == ap_CS_fsm_pp0_stage5))) begin
        weight_q_address1_local = zext_ln71_21_fu_989_p1;
    end else if (((ap_enable_reg_pp0_iter0_reg == 1'b1) & (1'b0 == ap_block_pp0_stage4) & (1'b1 == ap_CS_fsm_pp0_stage4))) begin
        weight_q_address1_local = zext_ln71_17_fu_965_p1;
    end else if (((ap_enable_reg_pp0_iter0_reg == 1'b1) & (1'b0 == ap_block_pp0_stage3) & (1'b1 == ap_CS_fsm_pp0_stage3))) begin
        weight_q_address1_local = zext_ln71_14_fu_941_p1;
    end else if (((ap_enable_reg_pp0_iter0_reg == 1'b1) & (1'b0 == ap_block_pp0_stage2) & (1'b1 == ap_CS_fsm_pp0_stage2))) begin
        weight_q_address1_local = zext_ln71_10_fu_917_p1;
    end else if (((ap_enable_reg_pp0_iter0_reg == 1'b1) & (1'b0 == ap_block_pp0_stage1) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
        weight_q_address1_local = zext_ln71_6_fu_893_p1;
    end else if (((1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        weight_q_address1_local = zext_ln71_2_fu_863_p1;
    end else begin
        weight_q_address1_local = 'bx;
    end
end

always @ (*) begin
    if ((((ap_enable_reg_pp0_iter0_reg == 1'b1) & (1'b0 == ap_block_pp0_stage15_11001) & (1'b1 == ap_CS_fsm_pp0_stage15)) | ((ap_enable_reg_pp0_iter0_reg == 1'b1) & (1'b0 == ap_block_pp0_stage7_11001) & (1'b1 == ap_CS_fsm_pp0_stage7)) | ((ap_enable_reg_pp0_iter0_reg == 1'b1) & (1'b0 == ap_block_pp0_stage6_11001) & (1'b1 == ap_CS_fsm_pp0_stage6)) | ((ap_enable_reg_pp0_iter0_reg == 1'b1) & (1'b0 == ap_block_pp0_stage5_11001) & (1'b1 == ap_CS_fsm_pp0_stage5)) | ((ap_enable_reg_pp0_iter0_reg == 1'b1) & (1'b0 == ap_block_pp0_stage14_11001) & (1'b1 == ap_CS_fsm_pp0_stage14)) | ((ap_enable_reg_pp0_iter0_reg == 1'b1) & (1'b0 == ap_block_pp0_stage4_11001) & (1'b1 == ap_CS_fsm_pp0_stage4)) | ((ap_enable_reg_pp0_iter0_reg == 1'b1) & (1'b0 == ap_block_pp0_stage3_11001) & (1'b1 == ap_CS_fsm_pp0_stage3)) | ((ap_enable_reg_pp0_iter0_reg == 1'b1) & (1'b0 == ap_block_pp0_stage12_11001) & (1'b1 == ap_CS_fsm_pp0_stage12)) | ((ap_enable_reg_pp0_iter0_reg == 1'b1) & (1'b0 == ap_block_pp0_stage2_11001) & (1'b1 == ap_CS_fsm_pp0_stage2)) | ((ap_enable_reg_pp0_iter0_reg 
    == 1'b1) & (1'b0 == ap_block_pp0_stage13_11001) & (1'b1 == ap_CS_fsm_pp0_stage13)) | ((ap_enable_reg_pp0_iter0_reg == 1'b1) & (1'b0 == ap_block_pp0_stage11_11001) & (1'b1 == ap_CS_fsm_pp0_stage11)) | ((ap_enable_reg_pp0_iter0_reg == 1'b1) & (1'b0 == ap_block_pp0_stage10_11001) & (1'b1 == ap_CS_fsm_pp0_stage10)) | ((ap_enable_reg_pp0_iter0_reg == 1'b1) & (1'b0 == ap_block_pp0_stage9_11001) & (1'b1 == ap_CS_fsm_pp0_stage9)) | ((ap_enable_reg_pp0_iter0_reg == 1'b1) & (1'b0 == ap_block_pp0_stage8_11001) & (1'b1 == ap_CS_fsm_pp0_stage8)) | ((ap_enable_reg_pp0_iter0_reg == 1'b1) & (1'b0 == ap_block_pp0_stage1_11001) & (1'b1 == ap_CS_fsm_pp0_stage1)) | ((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0)))) begin
        weight_q_ce0_local = 1'b1;
    end else begin
        weight_q_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if ((((ap_enable_reg_pp0_iter0_reg == 1'b1) & (1'b0 == ap_block_pp0_stage15_11001) & (1'b1 == ap_CS_fsm_pp0_stage15)) | ((ap_enable_reg_pp0_iter0_reg == 1'b1) & (1'b0 == ap_block_pp0_stage7_11001) & (1'b1 == ap_CS_fsm_pp0_stage7)) | ((ap_enable_reg_pp0_iter0_reg == 1'b1) & (1'b0 == ap_block_pp0_stage6_11001) & (1'b1 == ap_CS_fsm_pp0_stage6)) | ((ap_enable_reg_pp0_iter0_reg == 1'b1) & (1'b0 == ap_block_pp0_stage5_11001) & (1'b1 == ap_CS_fsm_pp0_stage5)) | ((ap_enable_reg_pp0_iter0_reg == 1'b1) & (1'b0 == ap_block_pp0_stage14_11001) & (1'b1 == ap_CS_fsm_pp0_stage14)) | ((ap_enable_reg_pp0_iter0_reg == 1'b1) & (1'b0 == ap_block_pp0_stage4_11001) & (1'b1 == ap_CS_fsm_pp0_stage4)) | ((ap_enable_reg_pp0_iter0_reg == 1'b1) & (1'b0 == ap_block_pp0_stage3_11001) & (1'b1 == ap_CS_fsm_pp0_stage3)) | ((ap_enable_reg_pp0_iter0_reg == 1'b1) & (1'b0 == ap_block_pp0_stage12_11001) & (1'b1 == ap_CS_fsm_pp0_stage12)) | ((ap_enable_reg_pp0_iter0_reg == 1'b1) & (1'b0 == ap_block_pp0_stage2_11001) & (1'b1 == ap_CS_fsm_pp0_stage2)) | ((ap_enable_reg_pp0_iter0_reg 
    == 1'b1) & (1'b0 == ap_block_pp0_stage13_11001) & (1'b1 == ap_CS_fsm_pp0_stage13)) | ((ap_enable_reg_pp0_iter0_reg == 1'b1) & (1'b0 == ap_block_pp0_stage11_11001) & (1'b1 == ap_CS_fsm_pp0_stage11)) | ((ap_enable_reg_pp0_iter0_reg == 1'b1) & (1'b0 == ap_block_pp0_stage10_11001) & (1'b1 == ap_CS_fsm_pp0_stage10)) | ((ap_enable_reg_pp0_iter0_reg == 1'b1) & (1'b0 == ap_block_pp0_stage9_11001) & (1'b1 == ap_CS_fsm_pp0_stage9)) | ((ap_enable_reg_pp0_iter0_reg == 1'b1) & (1'b0 == ap_block_pp0_stage8_11001) & (1'b1 == ap_CS_fsm_pp0_stage8)) | ((ap_enable_reg_pp0_iter0_reg == 1'b1) & (1'b0 == ap_block_pp0_stage1_11001) & (1'b1 == ap_CS_fsm_pp0_stage1)) | ((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0)))) begin
        weight_q_ce1_local = 1'b1;
    end else begin
        weight_q_ce1_local = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_pp0_stage0 : begin
            if ((~((ap_start_int == 1'b0) & (ap_idle_pp0_1to1 == 1'b1)) & (1'b0 == ap_block_pp0_stage0_subdone))) begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage1;
            end else begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage0;
            end
        end
        ap_ST_fsm_pp0_stage1 : begin
            if ((1'b0 == ap_block_pp0_stage1_subdone)) begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage2;
            end else begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage1;
            end
        end
        ap_ST_fsm_pp0_stage2 : begin
            if ((1'b0 == ap_block_pp0_stage2_subdone)) begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage3;
            end else begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage2;
            end
        end
        ap_ST_fsm_pp0_stage3 : begin
            if ((1'b0 == ap_block_pp0_stage3_subdone)) begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage4;
            end else begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage3;
            end
        end
        ap_ST_fsm_pp0_stage4 : begin
            if ((1'b0 == ap_block_pp0_stage4_subdone)) begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage5;
            end else begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage4;
            end
        end
        ap_ST_fsm_pp0_stage5 : begin
            if ((1'b0 == ap_block_pp0_stage5_subdone)) begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage6;
            end else begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage5;
            end
        end
        ap_ST_fsm_pp0_stage6 : begin
            if ((1'b0 == ap_block_pp0_stage6_subdone)) begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage7;
            end else begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage6;
            end
        end
        ap_ST_fsm_pp0_stage7 : begin
            if ((1'b0 == ap_block_pp0_stage7_subdone)) begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage8;
            end else begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage7;
            end
        end
        ap_ST_fsm_pp0_stage8 : begin
            if ((1'b0 == ap_block_pp0_stage8_subdone)) begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage9;
            end else begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage8;
            end
        end
        ap_ST_fsm_pp0_stage9 : begin
            if ((1'b0 == ap_block_pp0_stage9_subdone)) begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage10;
            end else begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage9;
            end
        end
        ap_ST_fsm_pp0_stage10 : begin
            if ((1'b1 == ap_condition_exit_pp0_iter0_stage10)) begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage0;
            end else if ((1'b0 == ap_block_pp0_stage10_subdone)) begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage11;
            end else begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage10;
            end
        end
        ap_ST_fsm_pp0_stage11 : begin
            if ((1'b0 == ap_block_pp0_stage11_subdone)) begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage12;
            end else begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage11;
            end
        end
        ap_ST_fsm_pp0_stage12 : begin
            if ((1'b0 == ap_block_pp0_stage12_subdone)) begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage13;
            end else begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage12;
            end
        end
        ap_ST_fsm_pp0_stage13 : begin
            if ((1'b0 == ap_block_pp0_stage13_subdone)) begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage14;
            end else begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage13;
            end
        end
        ap_ST_fsm_pp0_stage14 : begin
            if ((1'b0 == ap_block_pp0_stage14_subdone)) begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage15;
            end else begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage14;
            end
        end
        ap_ST_fsm_pp0_stage15 : begin
            if ((1'b0 == ap_block_pp0_stage15_subdone)) begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage0;
            end else begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage15;
            end
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign add_ln66_fu_845_p2 = (ap_sig_allocacmp_class_index_1 + 2'd1);

assign add_ln72_12_fu_1578_p2 = ($signed(sext_ln72_12_fu_1575_p1) + $signed(sext_ln72_11_fu_1572_p1));

assign add_ln72_13_fu_1588_p2 = ($signed(sext_ln72_13_fu_1584_p1) + $signed(sext_ln72_10_fu_1569_p1));

assign add_ln72_14_fu_1677_p2 = ($signed(sext_ln72_14_fu_1674_p1) + $signed(sext_ln72_7_fu_1670_p1));

assign add_ln72_17_fu_1215_p2 = ($signed(sext_ln72_17_fu_1212_p1) + $signed(sext_ln72_16_fu_1209_p1));

assign add_ln72_20_fu_1312_p2 = ($signed(sext_ln72_20_fu_1309_p1) + $signed(sext_ln72_19_fu_1306_p1));

assign add_ln72_21_fu_1322_p2 = ($signed(sext_ln72_21_fu_1318_p1) + $signed(sext_ln72_18_fu_1303_p1));

assign add_ln72_24_fu_1415_p2 = ($signed(sext_ln72_24_fu_1412_p1) + $signed(sext_ln72_23_fu_1409_p1));

assign add_ln72_27_fu_1469_p2 = ($signed(sext_ln72_27_fu_1466_p1) + $signed(sext_ln72_26_fu_1463_p1));

assign add_ln72_28_fu_1479_p2 = ($signed(sext_ln72_28_fu_1475_p1) + $signed(sext_ln72_25_fu_1460_p1));

assign add_ln72_29_fu_1489_p2 = ($signed(sext_ln72_29_fu_1485_p1) + $signed(sext_ln72_22_fu_1457_p1));

assign add_ln72_2_fu_1651_p2 = ($signed(sext_ln72_2_fu_1648_p1) + $signed(sext_ln72_1_fu_1645_p1));

assign add_ln72_5_fu_1627_p2 = ($signed(sext_ln72_5_fu_1624_p1) + $signed(sext_ln72_4_fu_1621_p1));

assign add_ln72_6_fu_1664_p2 = ($signed(sext_ln72_6_fu_1661_p1) + $signed(sext_ln72_3_fu_1657_p1));

assign add_ln72_9_fu_1533_p2 = ($signed(sext_ln72_9_fu_1530_p1) + $signed(sext_ln72_8_fu_1527_p1));

assign add_ln78_fu_1797_p2 = ($signed(select_ln17_fu_1787_p3) + $signed(sext_ln78_fu_1794_p1));

assign and_ln12_fu_1758_p2 = (tmp_fu_1722_p3 & icmp_ln12_fu_1752_p2);

assign ap_CS_fsm_pp0_stage0 = ap_CS_fsm[32'd0];

assign ap_CS_fsm_pp0_stage1 = ap_CS_fsm[32'd1];

assign ap_CS_fsm_pp0_stage10 = ap_CS_fsm[32'd10];

assign ap_CS_fsm_pp0_stage11 = ap_CS_fsm[32'd11];

assign ap_CS_fsm_pp0_stage12 = ap_CS_fsm[32'd12];

assign ap_CS_fsm_pp0_stage13 = ap_CS_fsm[32'd13];

assign ap_CS_fsm_pp0_stage14 = ap_CS_fsm[32'd14];

assign ap_CS_fsm_pp0_stage15 = ap_CS_fsm[32'd15];

assign ap_CS_fsm_pp0_stage2 = ap_CS_fsm[32'd2];

assign ap_CS_fsm_pp0_stage3 = ap_CS_fsm[32'd3];

assign ap_CS_fsm_pp0_stage4 = ap_CS_fsm[32'd4];

assign ap_CS_fsm_pp0_stage5 = ap_CS_fsm[32'd5];

assign ap_CS_fsm_pp0_stage6 = ap_CS_fsm[32'd6];

assign ap_CS_fsm_pp0_stage7 = ap_CS_fsm[32'd7];

assign ap_CS_fsm_pp0_stage8 = ap_CS_fsm[32'd8];

assign ap_CS_fsm_pp0_stage9 = ap_CS_fsm[32'd9];

assign ap_block_pp0_stage0 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage0_11001 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage0_subdone = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage1 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage10 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage10_11001 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage10_subdone = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage11 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage11_11001 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage11_subdone = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage12 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage12_11001 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage12_subdone = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage13 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage13_11001 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage13_subdone = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage14 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage14_11001 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage14_subdone = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage15 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage15_11001 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage15_subdone = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage1_11001 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage1_subdone = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage2 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage2_11001 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage2_subdone = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage3 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage3_11001 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage3_subdone = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage4 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage4_11001 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage4_subdone = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage5 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage5_11001 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage5_subdone = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage6 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage6_11001 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage6_subdone = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage7 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage7_11001 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage7_subdone = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage8 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage8_11001 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage8_subdone = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage9 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage9_11001 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage9_subdone = ~(1'b1 == 1'b1);

assign ap_done = ap_done_sig;

assign ap_enable_pp0 = (ap_idle_pp0 ^ 1'b1);

assign ap_loop_exit_ready = ap_condition_exit_pp0_iter0_stage10;

assign ap_ready = ap_ready_sig;

assign bias_q_address0 = zext_ln66_fu_1421_p1;

assign bias_q_ce0 = bias_q_ce0_local;

assign conv_i104_10_i_cast_fu_787_p1 = conv_i104_10_i;

assign conv_i104_11_i_cast_fu_783_p1 = conv_i104_11_i;

assign conv_i104_12_i_cast_fu_779_p1 = conv_i104_12_i;

assign conv_i104_13_i_cast_fu_775_p1 = conv_i104_13_i;

assign conv_i104_14_i_cast_fu_771_p1 = conv_i104_14_i;

assign conv_i104_15_i_cast_fu_767_p1 = conv_i104_15_i;

assign conv_i104_16_i_cast_fu_763_p1 = conv_i104_16_i;

assign conv_i104_17_i_cast_fu_759_p1 = conv_i104_17_i;

assign conv_i104_18_i_cast_fu_755_p1 = conv_i104_18_i;

assign conv_i104_19_i_cast_fu_751_p1 = conv_i104_19_i;

assign conv_i104_1_i_cast_fu_823_p1 = conv_i104_1_i;

assign conv_i104_20_i_cast_fu_747_p1 = conv_i104_20_i;

assign conv_i104_21_i_cast_fu_743_p1 = conv_i104_21_i;

assign conv_i104_22_i_cast_fu_739_p1 = conv_i104_22_i;

assign conv_i104_23_i_cast_fu_735_p1 = conv_i104_23_i;

assign conv_i104_24_i_cast_fu_731_p1 = conv_i104_24_i;

assign conv_i104_25_i_cast_fu_727_p1 = conv_i104_25_i;

assign conv_i104_26_i_cast_fu_723_p1 = conv_i104_26_i;

assign conv_i104_27_i_cast_fu_719_p1 = conv_i104_27_i;

assign conv_i104_28_i_cast_fu_715_p1 = conv_i104_28_i;

assign conv_i104_29_i_cast_fu_711_p1 = conv_i104_29_i;

assign conv_i104_2_i_cast_fu_819_p1 = conv_i104_2_i;

assign conv_i104_30_i_cast_fu_707_p1 = conv_i104_30_i;

assign conv_i104_31_i_cast_fu_703_p1 = conv_i104_31_i;

assign conv_i104_3_i_cast_fu_815_p1 = conv_i104_3_i;

assign conv_i104_4_i_cast_fu_811_p1 = conv_i104_4_i;

assign conv_i104_5_i_cast_fu_807_p1 = conv_i104_5_i;

assign conv_i104_6_i_cast_fu_803_p1 = conv_i104_6_i;

assign conv_i104_7_i_cast_fu_799_p1 = conv_i104_7_i;

assign conv_i104_8_i_cast_fu_795_p1 = conv_i104_8_i;

assign conv_i104_9_i_cast_fu_791_p1 = conv_i104_9_i;

assign conv_i104_i_cast_fu_827_p1 = conv_i104_i;

assign grp_fu_1804_p1 = conv_i104_4_i_cast_reg_2066;

assign grp_fu_1811_p1 = conv_i104_2_i_cast_reg_2076;

assign grp_fu_1819_p1 = conv_i104_6_i_cast_reg_2056;

assign grp_fu_1826_p1 = conv_i104_8_i_cast_reg_2046;

assign grp_fu_1834_p1 = conv_i104_10_i_cast_reg_2036;

assign grp_fu_1841_p1 = conv_i104_12_i_cast_reg_2026;

assign grp_fu_1849_p1 = conv_i104_14_i_cast_reg_2016;

assign grp_fu_1856_p1 = conv_i104_31_i_cast_reg_1931;

assign grp_fu_1864_p1 = conv_i104_15_i_cast_reg_2011;

assign grp_fu_1871_p1 = conv_i104_17_i_cast_reg_2001;

assign grp_fu_1879_p1 = conv_i104_19_i_cast_reg_1991;

assign grp_fu_1886_p1 = conv_i104_21_i_cast_reg_1981;

assign grp_fu_1894_p1 = conv_i104_23_i_cast_reg_1971;

assign grp_fu_1901_p1 = conv_i104_25_i_cast_reg_1961;

assign grp_fu_1909_p1 = conv_i104_27_i_cast_reg_1951;

assign grp_fu_1916_p1 = conv_i104_30_i_cast_reg_1936;

assign icmp_ln11_fu_1740_p2 = ((trunc_ln5_fu_1718_p1 > 6'd32) ? 1'b1 : 1'b0);

assign icmp_ln12_fu_1752_p2 = ((trunc_ln5_fu_1718_p1 == 6'd32) ? 1'b1 : 1'b0);

assign icmp_ln66_fu_839_p2 = ((ap_sig_allocacmp_class_index_1 == 2'd2) ? 1'b1 : 1'b0);

assign logits_q_address0 = zext_ln66_reg_2459;

assign logits_q_ce0 = logits_q_ce0_local;

assign logits_q_d0 = add_ln78_fu_1797_p2;

assign logits_q_we0 = logits_q_we0_local;

assign negative_fu_1696_p3 = numerator_fu_1690_p2[32'd22];

assign numerator_fu_1690_p2 = ($signed(sext_ln72_30_fu_1687_p1) + $signed(sext_ln72_15_fu_1683_p1));

assign or_ln12_fu_1764_p2 = (icmp_ln11_fu_1740_p2 | and_ln12_fu_1758_p2);

assign product_11_fu_1397_p1 = conv_i104_11_i_cast_reg_2031;

assign product_13_fu_1429_p1 = conv_i104_13_i_cast_reg_2021;

assign product_16_fu_1445_p1 = conv_i104_16_i_cast_reg_2006;

assign product_18_fu_1499_p1 = conv_i104_18_i_cast_reg_1996;

assign product_20_fu_1515_p1 = conv_i104_20_i_cast_reg_1986;

assign product_22_fu_1542_p1 = conv_i104_22_i_cast_reg_1976;

assign product_24_fu_1557_p1 = conv_i104_24_i_cast_reg_1966;

assign product_26_fu_1597_p1 = conv_i104_26_i_cast_reg_1956;

assign product_28_fu_1612_p1 = conv_i104_28_i_cast_reg_1946;

assign product_29_fu_1636_p1 = conv_i104_29_i_cast_reg_1941;

assign product_32_fu_1114_p1 = conv_i104_i_cast_reg_2086;

assign product_3_fu_1196_p1 = conv_i104_3_i_cast_reg_2071;

assign product_5_fu_1249_p1 = conv_i104_5_i_cast_reg_2061;

assign product_7_fu_1290_p1 = conv_i104_7_i_cast_reg_2051;

assign product_9_fu_1356_p1 = conv_i104_9_i_cast_reg_2041;

assign product_fu_1155_p1 = conv_i104_1_i_cast_reg_2081;

assign quotient_2_fu_1770_p3 = ((or_ln12_fu_1764_p2[0:0] == 1'b1) ? quotient_fu_1746_p2 : trunc_ln7_3_fu_1730_p4);

assign quotient_fu_1746_p2 = (trunc_ln7_3_fu_1730_p4 + 17'd1);

assign select_ln17_fu_1787_p3 = ((negative_reg_2609[0:0] == 1'b1) ? sub_ln17_fu_1781_p2 : zext_ln17_fu_1778_p1);

assign sext_ln72_10_fu_1569_p1 = $signed(add_ln72_9_reg_2539);

assign sext_ln72_11_fu_1572_p1 = add_ln72_10_reg_2554;

assign sext_ln72_12_fu_1575_p1 = grp_fu_1886_p3;

assign sext_ln72_13_fu_1584_p1 = $signed(add_ln72_12_fu_1578_p2);

assign sext_ln72_14_fu_1674_p1 = $signed(add_ln72_13_reg_2569);

assign sext_ln72_15_fu_1683_p1 = $signed(add_ln72_14_fu_1677_p2);

assign sext_ln72_16_fu_1209_p1 = grp_fu_1811_p3;

assign sext_ln72_17_fu_1212_p1 = add_ln72_16_reg_2314;

assign sext_ln72_18_fu_1303_p1 = $signed(add_ln72_17_reg_2339);

assign sext_ln72_19_fu_1306_p1 = add_ln72_18_reg_2364;

assign sext_ln72_1_fu_1645_p1 = grp_fu_1916_p3;

assign sext_ln72_20_fu_1309_p1 = grp_fu_1826_p3;

assign sext_ln72_21_fu_1318_p1 = $signed(add_ln72_20_fu_1312_p2);

assign sext_ln72_22_fu_1457_p1 = $signed(add_ln72_21_reg_2389);

assign sext_ln72_23_fu_1409_p1 = add_ln72_22_reg_2419;

assign sext_ln72_24_fu_1412_p1 = grp_fu_1841_p3;

assign sext_ln72_25_fu_1460_p1 = $signed(add_ln72_24_reg_2454);

assign sext_ln72_26_fu_1463_p1 = add_ln72_25_reg_2484;

assign sext_ln72_27_fu_1466_p1 = grp_fu_1856_p3;

assign sext_ln72_28_fu_1475_p1 = $signed(add_ln72_27_fu_1469_p2);

assign sext_ln72_29_fu_1485_p1 = $signed(add_ln72_28_fu_1479_p2);

assign sext_ln72_2_fu_1648_p1 = add_ln72_1_reg_2604;

assign sext_ln72_30_fu_1687_p1 = $signed(add_ln72_29_reg_2504);

assign sext_ln72_3_fu_1657_p1 = $signed(add_ln72_2_fu_1651_p2);

assign sext_ln72_4_fu_1621_p1 = add_ln72_3_reg_2584;

assign sext_ln72_5_fu_1624_p1 = grp_fu_1901_p3;

assign sext_ln72_6_fu_1661_p1 = $signed(add_ln72_5_reg_2594);

assign sext_ln72_7_fu_1670_p1 = $signed(add_ln72_6_fu_1664_p2);

assign sext_ln72_8_fu_1527_p1 = add_ln72_7_reg_2524;

assign sext_ln72_9_fu_1530_p1 = grp_fu_1871_p3;

assign sext_ln78_fu_1794_p1 = $signed(bias_q_load_reg_2509);

assign signed_magnitude_2_fu_1710_p3 = ((negative_fu_1696_p3[0:0] == 1'b1) ? signed_magnitude_fu_1704_p2 : numerator_fu_1690_p2);

assign signed_magnitude_fu_1704_p2 = (23'd0 - numerator_fu_1690_p2);

assign sub_ln17_fu_1781_p2 = (18'd0 - zext_ln17_fu_1778_p1);

assign tmp_10_fu_910_p3 = {{trunc_ln66_reg_2100}, {5'd10}};

assign tmp_11_fu_1168_p3 = {{trunc_ln66_reg_2100}, {5'd11}};

assign tmp_12_fu_922_p3 = {{trunc_ln66_reg_2100}, {5'd12}};

assign tmp_13_fu_1180_p3 = {{trunc_ln66_reg_2100}, {5'd13}};

assign tmp_14_fu_934_p3 = {{trunc_ln66_reg_2100}, {5'd14}};

assign tmp_15_fu_946_p3 = {{trunc_ln66_reg_2100}, {5'd15}};

assign tmp_16_fu_1221_p3 = {{trunc_ln66_reg_2100}, {5'd16}};

assign tmp_17_fu_958_p3 = {{trunc_ln66_reg_2100}, {5'd17}};

assign tmp_18_fu_1233_p3 = {{trunc_ln66_reg_2100}, {5'd18}};

assign tmp_19_fu_970_p3 = {{trunc_ln66_reg_2100}, {5'd19}};

assign tmp_1_fu_898_p3 = {{trunc_ln66_reg_2100}, {5'd8}};

assign tmp_20_fu_1262_p3 = {{trunc_ln66_reg_2100}, {5'd20}};

assign tmp_21_fu_982_p3 = {{trunc_ln66_reg_2100}, {5'd21}};

assign tmp_22_fu_1274_p3 = {{trunc_ln66_reg_2100}, {5'd22}};

assign tmp_23_fu_994_p3 = {{trunc_ln66_reg_2100}, {5'd23}};

assign tmp_24_fu_1328_p3 = {{trunc_ln66_reg_2100}, {5'd24}};

assign tmp_25_fu_1006_p3 = {{trunc_ln66_reg_2100}, {5'd25}};

assign tmp_26_fu_1340_p3 = {{trunc_ln66_reg_2100}, {5'd26}};

assign tmp_27_fu_1018_p3 = {{trunc_ln66_reg_2100}, {5'd27}};

assign tmp_28_fu_1369_p3 = {{trunc_ln66_reg_2100}, {5'd28}};

assign tmp_29_fu_1381_p3 = {{trunc_ln66_reg_2100}, {5'd29}};

assign tmp_2_fu_1139_p3 = {{trunc_ln66_reg_2100}, {5'd9}};

assign tmp_30_fu_1030_p3 = {{trunc_ln66_reg_2100}, {5'd30}};

assign tmp_31_fu_1042_p3 = {{trunc_ln66_reg_2100}, {5'd31}};

assign tmp_3_fu_1058_p3 = {{trunc_ln66_reg_2100}, {5'd0}};

assign tmp_4_fu_1070_p3 = {{trunc_ln66_reg_2100}, {5'd1}};

assign tmp_5_fu_855_p3 = {{trunc_ln66_fu_851_p1}, {5'd2}};

assign tmp_6_fu_1086_p3 = {{trunc_ln66_reg_2100}, {5'd3}};

assign tmp_7_fu_868_p3 = {{trunc_ln66_fu_851_p1}, {5'd4}};

assign tmp_8_fu_1098_p3 = {{trunc_ln66_reg_2100}, {5'd5}};

assign tmp_9_fu_886_p3 = {{trunc_ln66_reg_2100}, {5'd6}};

assign tmp_fu_1722_p3 = signed_magnitude_2_fu_1710_p3[32'd6];

assign tmp_s_fu_1127_p3 = {{trunc_ln66_reg_2100}, {5'd7}};

assign trunc_ln5_fu_1718_p1 = signed_magnitude_2_fu_1710_p3[5:0];

assign trunc_ln66_fu_851_p1 = ap_sig_allocacmp_class_index_1[0:0];

assign trunc_ln7_3_fu_1730_p4 = {{signed_magnitude_2_fu_1710_p3[22:6]}};

assign weight_q_address0 = weight_q_address0_local;

assign weight_q_address1 = weight_q_address1_local;

assign weight_q_ce0 = weight_q_ce0_local;

assign weight_q_ce1 = weight_q_ce1_local;

assign zext_ln17_fu_1778_p1 = quotient_2_reg_2614;

assign zext_ln66_fu_1421_p1 = class_index_1_reg_2091;

assign zext_ln71_10_fu_917_p1 = tmp_10_fu_910_p3;

assign zext_ln71_11_fu_1175_p1 = tmp_11_fu_1168_p3;

assign zext_ln71_12_fu_929_p1 = tmp_12_fu_922_p3;

assign zext_ln71_13_fu_1187_p1 = tmp_13_fu_1180_p3;

assign zext_ln71_14_fu_941_p1 = tmp_14_fu_934_p3;

assign zext_ln71_15_fu_953_p1 = tmp_15_fu_946_p3;

assign zext_ln71_16_fu_1228_p1 = tmp_16_fu_1221_p3;

assign zext_ln71_17_fu_965_p1 = tmp_17_fu_958_p3;

assign zext_ln71_18_fu_1240_p1 = tmp_18_fu_1233_p3;

assign zext_ln71_19_fu_977_p1 = tmp_19_fu_970_p3;

assign zext_ln71_1_fu_1077_p1 = tmp_4_fu_1070_p3;

assign zext_ln71_20_fu_1269_p1 = tmp_20_fu_1262_p3;

assign zext_ln71_21_fu_989_p1 = tmp_21_fu_982_p3;

assign zext_ln71_22_fu_1281_p1 = tmp_22_fu_1274_p3;

assign zext_ln71_23_fu_1001_p1 = tmp_23_fu_994_p3;

assign zext_ln71_24_fu_1335_p1 = tmp_24_fu_1328_p3;

assign zext_ln71_25_fu_1013_p1 = tmp_25_fu_1006_p3;

assign zext_ln71_26_fu_1347_p1 = tmp_26_fu_1340_p3;

assign zext_ln71_27_fu_1025_p1 = tmp_27_fu_1018_p3;

assign zext_ln71_28_fu_1376_p1 = tmp_28_fu_1369_p3;

assign zext_ln71_29_fu_1388_p1 = tmp_29_fu_1381_p3;

assign zext_ln71_2_fu_863_p1 = tmp_5_fu_855_p3;

assign zext_ln71_30_fu_1037_p1 = tmp_30_fu_1030_p3;

assign zext_ln71_31_fu_1049_p1 = tmp_31_fu_1042_p3;

assign zext_ln71_3_fu_1093_p1 = tmp_6_fu_1086_p3;

assign zext_ln71_4_fu_876_p1 = tmp_7_fu_868_p3;

assign zext_ln71_5_fu_1105_p1 = tmp_8_fu_1098_p3;

assign zext_ln71_6_fu_893_p1 = tmp_9_fu_886_p3;

assign zext_ln71_7_fu_1134_p1 = tmp_s_fu_1127_p3;

assign zext_ln71_8_fu_905_p1 = tmp_1_fu_898_p3;

assign zext_ln71_9_fu_1146_p1 = tmp_2_fu_1139_p3;

assign zext_ln71_fu_1065_p1 = tmp_3_fu_1058_p3;

always @ (posedge ap_clk) begin
    conv_i104_31_i_cast_reg_1931[17:7] <= 11'b00000000000;
    conv_i104_30_i_cast_reg_1936[17:7] <= 11'b00000000000;
    conv_i104_29_i_cast_reg_1941[17:7] <= 11'b00000000000;
    conv_i104_28_i_cast_reg_1946[17:7] <= 11'b00000000000;
    conv_i104_27_i_cast_reg_1951[17:7] <= 11'b00000000000;
    conv_i104_26_i_cast_reg_1956[17:7] <= 11'b00000000000;
    conv_i104_25_i_cast_reg_1961[17:7] <= 11'b00000000000;
    conv_i104_24_i_cast_reg_1966[17:7] <= 11'b00000000000;
    conv_i104_23_i_cast_reg_1971[17:7] <= 11'b00000000000;
    conv_i104_22_i_cast_reg_1976[17:7] <= 11'b00000000000;
    conv_i104_21_i_cast_reg_1981[17:7] <= 11'b00000000000;
    conv_i104_20_i_cast_reg_1986[17:7] <= 11'b00000000000;
    conv_i104_19_i_cast_reg_1991[17:7] <= 11'b00000000000;
    conv_i104_18_i_cast_reg_1996[17:7] <= 11'b00000000000;
    conv_i104_17_i_cast_reg_2001[17:7] <= 11'b00000000000;
    conv_i104_16_i_cast_reg_2006[17:7] <= 11'b00000000000;
    conv_i104_15_i_cast_reg_2011[17:7] <= 11'b00000000000;
    conv_i104_14_i_cast_reg_2016[17:7] <= 11'b00000000000;
    conv_i104_13_i_cast_reg_2021[17:7] <= 11'b00000000000;
    conv_i104_12_i_cast_reg_2026[17:7] <= 11'b00000000000;
    conv_i104_11_i_cast_reg_2031[17:7] <= 11'b00000000000;
    conv_i104_10_i_cast_reg_2036[17:7] <= 11'b00000000000;
    conv_i104_9_i_cast_reg_2041[17:7] <= 11'b00000000000;
    conv_i104_8_i_cast_reg_2046[17:7] <= 11'b00000000000;
    conv_i104_7_i_cast_reg_2051[17:7] <= 11'b00000000000;
    conv_i104_6_i_cast_reg_2056[17:7] <= 11'b00000000000;
    conv_i104_5_i_cast_reg_2061[17:7] <= 11'b00000000000;
    conv_i104_4_i_cast_reg_2066[17:7] <= 11'b00000000000;
    conv_i104_3_i_cast_reg_2071[17:7] <= 11'b00000000000;
    conv_i104_2_i_cast_reg_2076[17:7] <= 11'b00000000000;
    conv_i104_1_i_cast_reg_2081[17:7] <= 11'b00000000000;
    conv_i104_i_cast_reg_2086[17:7] <= 11'b00000000000;
    zext_ln66_reg_2459[63:2] <= 62'b00000000000000000000000000000000000000000000000000000000000000;
end

endmodule //hybrid_lif_head_q12_6_run_hybrid_lif_head_Pipeline_VITIS_LOOP_66_5
