// ==============================================================
// Generated by Vitis HLS v2025.1
// Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// Copyright 2022-2025 Advanced Micro Devices, Inc. All Rights Reserved.
// ==============================================================

`timescale 1 ns / 1 ps 

module hybrid_lif_head_q12_6_run_hybrid_lif_head_Pipeline_VITIS_LOOP_36_2_VITIS_LOOP_37_3 (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_idle,
        ap_ready,
        feature_current_q_address0,
        feature_current_q_ce0,
        feature_current_q_q0,
        membrane_address0,
        membrane_ce0,
        membrane_we0,
        membrane_d0,
        membrane_address1,
        membrane_ce1,
        membrane_q1,
        spike_count_q_address0,
        spike_count_q_ce0,
        spike_count_q_we0,
        spike_count_q_d0,
        spike_count_q_address1,
        spike_count_q_ce1,
        spike_count_q_q1
);

parameter    ap_ST_fsm_pp0_stage0 = 1'd1;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
output   ap_idle;
output   ap_ready;
output  [10:0] feature_current_q_address0;
output   feature_current_q_ce0;
input  [11:0] feature_current_q_q0;
output  [4:0] membrane_address0;
output   membrane_ce0;
output   membrane_we0;
output  [15:0] membrane_d0;
output  [4:0] membrane_address1;
output   membrane_ce1;
input  [15:0] membrane_q1;
output  [4:0] spike_count_q_address0;
output   spike_count_q_ce0;
output   spike_count_q_we0;
output  [5:0] spike_count_q_d0;
output  [4:0] spike_count_q_address1;
output   spike_count_q_ce1;
input  [5:0] spike_count_q_q1;

reg ap_idle;

(* fsm_encoding = "none" *) reg   [0:0] ap_CS_fsm;
wire    ap_CS_fsm_pp0_stage0;
wire    ap_enable_reg_pp0_iter0;
reg    ap_enable_reg_pp0_iter1;
reg    ap_enable_reg_pp0_iter2;
reg    ap_enable_reg_pp0_iter3;
reg    ap_idle_pp0;
wire    ap_block_pp0_stage0_subdone;
wire   [0:0] icmp_ln36_fu_169_p2;
reg    ap_condition_exit_pp0_iter0_stage0;
wire    ap_loop_exit_ready;
reg    ap_ready_int;
reg   [0:0] icmp_ln36_reg_450;
wire    ap_block_pp0_stage0_11001;
reg   [0:0] icmp_ln36_reg_450_pp0_iter1_reg;
reg   [0:0] icmp_ln36_reg_450_pp0_iter2_reg;
wire   [0:0] icmp_ln37_fu_184_p2;
reg   [0:0] icmp_ln37_reg_454;
wire   [5:0] select_ln36_fu_190_p3;
reg   [5:0] select_ln36_reg_459;
wire   [63:0] zext_ln37_fu_198_p1;
reg   [63:0] zext_ln37_reg_464;
reg   [63:0] zext_ln37_reg_464_pp0_iter1_reg;
reg   [4:0] membrane_addr_reg_469;
reg   [4:0] membrane_addr_reg_469_pp0_iter1_reg;
wire   [0:0] negative_fu_271_p3;
reg   [0:0] negative_reg_480;
wire   [14:0] quotient_4_fu_359_p3;
reg   [14:0] quotient_4_reg_485;
wire   [0:0] icmp_ln46_fu_409_p2;
reg   [0:0] icmp_ln46_reg_490;
reg   [4:0] spike_count_q_addr_reg_494;
reg   [15:0] ap_phi_mux_updated_2_phi_fu_144_p4;
wire   [15:0] updated_1_fu_415_p2;
wire   [15:0] ap_phi_reg_pp0_iter2_updated_2_reg_141;
wire   [15:0] updated_fu_392_p2;
wire    ap_block_pp0_stage0;
wire   [63:0] zext_ln43_1_fu_252_p1;
reg   [5:0] channel_fu_82;
wire   [5:0] add_ln37_fu_203_p2;
wire    ap_loop_init;
reg   [5:0] ap_sig_allocacmp_channel_load;
reg   [5:0] time_index_fu_86;
wire   [5:0] select_ln36_1_fu_228_p3;
reg   [10:0] indvar_flatten_fu_90;
wire   [10:0] add_ln36_1_fu_175_p2;
reg   [10:0] ap_sig_allocacmp_indvar_flatten_load;
reg    membrane_ce1_local;
reg    membrane_we0_local;
reg    membrane_ce0_local;
reg    feature_current_q_ce0_local;
reg    spike_count_q_ce1_local;
reg    spike_count_q_we0_local;
wire   [5:0] add_ln49_fu_422_p2;
reg    spike_count_q_ce0_local;
wire   [5:0] add_ln36_fu_222_p2;
wire   [10:0] tmp_fu_235_p3;
wire   [10:0] zext_ln43_fu_243_p1;
wire   [10:0] add_ln43_fu_246_p2;
wire  signed [15:0] sext_ln39_fu_257_p0;
wire   [6:0] beta_product_fu_261_p1;
wire   [21:0] beta_product_fu_261_p2;
wire   [20:0] trunc_ln3_fu_267_p1;
wire   [20:0] signed_magnitude_fu_279_p2;
wire   [20:0] signed_magnitude_4_fu_285_p3;
wire   [4:0] tmp_1_fu_311_p4;
wire   [6:0] twice_remainder_fu_321_p3;
wire   [14:0] trunc_ln7_1_fu_301_p4;
wire   [0:0] icmp_ln12_fu_341_p2;
wire   [0:0] tmp_3_fu_293_p3;
wire   [0:0] icmp_ln11_fu_329_p2;
wire   [0:0] and_ln12_fu_347_p2;
wire   [0:0] or_ln12_fu_353_p2;
wire   [14:0] quotient_fu_335_p2;
wire   [15:0] zext_ln17_fu_372_p1;
wire   [15:0] sub_ln17_fu_375_p2;
wire   [15:0] select_ln17_fu_381_p3;
wire  signed [15:0] sext_ln43_fu_388_p1;
wire   [10:0] tmp_4_fu_399_p4;
reg    ap_done_reg;
wire    ap_continue_int;
reg    ap_done_int;
reg    ap_loop_exit_ready_pp0_iter1_reg;
reg    ap_loop_exit_ready_pp0_iter2_reg;
reg   [0:0] ap_NS_fsm;
wire    ap_enable_pp0;
wire    ap_start_int;
wire    ap_ready_sig;
wire    ap_done_sig;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_CS_fsm = 1'd1;
#0 ap_enable_reg_pp0_iter1 = 1'b0;
#0 ap_enable_reg_pp0_iter2 = 1'b0;
#0 ap_enable_reg_pp0_iter3 = 1'b0;
#0 channel_fu_82 = 6'd0;
#0 time_index_fu_86 = 6'd0;
#0 indvar_flatten_fu_90 = 11'd0;
#0 ap_done_reg = 1'b0;
end

hybrid_lif_head_q12_6_mul_16s_7ns_22_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 16 ),
    .din1_WIDTH( 7 ),
    .dout_WIDTH( 22 ))
mul_16s_7ns_22_1_1_U3(
    .din0(sext_ln39_fu_257_p0),
    .din1(beta_product_fu_261_p1),
    .dout(beta_product_fu_261_p2)
);

hybrid_lif_head_q12_6_flow_control_loop_pipe_sequential_init flow_control_loop_pipe_sequential_init_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(ap_start),
    .ap_ready(ap_ready_sig),
    .ap_done(ap_done_sig),
    .ap_start_int(ap_start_int),
    .ap_loop_init(ap_loop_init),
    .ap_ready_int(ap_ready_int),
    .ap_loop_exit_ready(ap_condition_exit_pp0_iter0_stage0),
    .ap_loop_exit_done(ap_done_int),
    .ap_continue_int(ap_continue_int),
    .ap_done_int(ap_done_int)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_pp0_stage0;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_done_reg <= 1'b0;
    end else begin
        if ((ap_continue_int == 1'b1)) begin
            ap_done_reg <= 1'b0;
        end else if (((1'b0 == ap_block_pp0_stage0_subdone) & (ap_loop_exit_ready_pp0_iter2_reg == 1'b1))) begin
            ap_done_reg <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter1 <= 1'b0;
    end else begin
        if ((1'b1 == ap_condition_exit_pp0_iter0_stage0)) begin
            ap_enable_reg_pp0_iter1 <= 1'b0;
        end else if (((1'b0 == ap_block_pp0_stage0_subdone) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            ap_enable_reg_pp0_iter1 <= ap_start_int;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter2 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter2 <= ap_enable_reg_pp0_iter1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter3 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter3 <= ap_enable_reg_pp0_iter2;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        if (((icmp_ln36_fu_169_p2 == 1'd0) & (ap_enable_reg_pp0_iter0 == 1'b1))) begin
            channel_fu_82 <= add_ln37_fu_203_p2;
        end else if ((ap_loop_init == 1'b1)) begin
            channel_fu_82 <= 6'd0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        if (((icmp_ln36_fu_169_p2 == 1'd0) & (ap_enable_reg_pp0_iter0 == 1'b1))) begin
            indvar_flatten_fu_90 <= add_ln36_1_fu_175_p2;
        end else if ((ap_loop_init == 1'b1)) begin
            indvar_flatten_fu_90 <= 11'd0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        if ((ap_loop_init == 1'b1)) begin
            time_index_fu_86 <= 6'd0;
        end else if ((ap_enable_reg_pp0_iter1 == 1'b1)) begin
            time_index_fu_86 <= select_ln36_1_fu_228_p3;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_loop_exit_ready_pp0_iter1_reg <= ap_loop_exit_ready;
        ap_loop_exit_ready_pp0_iter2_reg <= ap_loop_exit_ready_pp0_iter1_reg;
        icmp_ln36_reg_450 <= icmp_ln36_fu_169_p2;
        icmp_ln36_reg_450_pp0_iter1_reg <= icmp_ln36_reg_450;
        icmp_ln37_reg_454 <= icmp_ln37_fu_184_p2;
        membrane_addr_reg_469 <= zext_ln37_fu_198_p1;
        membrane_addr_reg_469_pp0_iter1_reg <= membrane_addr_reg_469;
        negative_reg_480 <= beta_product_fu_261_p2[32'd21];
        quotient_4_reg_485 <= quotient_4_fu_359_p3;
        select_ln36_reg_459 <= select_ln36_fu_190_p3;
        zext_ln37_reg_464[5 : 0] <= zext_ln37_fu_198_p1[5 : 0];
        zext_ln37_reg_464_pp0_iter1_reg[5 : 0] <= zext_ln37_reg_464[5 : 0];
    end
end

always @ (posedge ap_clk) begin
    if ((1'b0 == ap_block_pp0_stage0_11001)) begin
        icmp_ln36_reg_450_pp0_iter2_reg <= icmp_ln36_reg_450_pp0_iter1_reg;
        icmp_ln46_reg_490 <= icmp_ln46_fu_409_p2;
        spike_count_q_addr_reg_494 <= zext_ln37_reg_464_pp0_iter1_reg;
    end
end

always @ (*) begin
    if (((icmp_ln36_fu_169_p2 == 1'd1) & (1'b0 == ap_block_pp0_stage0_subdone) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_condition_exit_pp0_iter0_stage0 = 1'b1;
    end else begin
        ap_condition_exit_pp0_iter0_stage0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_subdone) & (ap_loop_exit_ready_pp0_iter2_reg == 1'b1))) begin
        ap_done_int = 1'b1;
    end else begin
        ap_done_int = ap_done_reg;
    end
end

always @ (*) begin
    if (((ap_start_int == 1'b0) & (ap_idle_pp0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter3 == 1'b0) & (ap_enable_reg_pp0_iter2 == 1'b0) & (ap_enable_reg_pp0_iter1 == 1'b0) & (ap_enable_reg_pp0_iter0 == 1'b0))) begin
        ap_idle_pp0 = 1'b1;
    end else begin
        ap_idle_pp0 = 1'b0;
    end
end

always @ (*) begin
    if ((icmp_ln36_reg_450_pp0_iter1_reg == 1'd0)) begin
        if ((icmp_ln46_fu_409_p2 == 1'd0)) begin
            ap_phi_mux_updated_2_phi_fu_144_p4 = updated_fu_392_p2;
        end else if ((icmp_ln46_fu_409_p2 == 1'd1)) begin
            ap_phi_mux_updated_2_phi_fu_144_p4 = updated_1_fu_415_p2;
        end else begin
            ap_phi_mux_updated_2_phi_fu_144_p4 = ap_phi_reg_pp0_iter2_updated_2_reg_141;
        end
    end else begin
        ap_phi_mux_updated_2_phi_fu_144_p4 = ap_phi_reg_pp0_iter2_updated_2_reg_141;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_subdone) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_ready_int = 1'b1;
    end else begin
        ap_ready_int = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (1'b1 == ap_CS_fsm_pp0_stage0) & (ap_loop_init == 1'b1))) begin
        ap_sig_allocacmp_channel_load = 6'd0;
    end else begin
        ap_sig_allocacmp_channel_load = channel_fu_82;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (1'b1 == ap_CS_fsm_pp0_stage0) & (ap_loop_init == 1'b1))) begin
        ap_sig_allocacmp_indvar_flatten_load = 11'd0;
    end else begin
        ap_sig_allocacmp_indvar_flatten_load = indvar_flatten_fu_90;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        feature_current_q_ce0_local = 1'b1;
    end else begin
        feature_current_q_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
        membrane_ce0_local = 1'b1;
    end else begin
        membrane_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        membrane_ce1_local = 1'b1;
    end else begin
        membrane_ce1_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
        membrane_we0_local = 1'b1;
    end else begin
        membrane_we0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter3 == 1'b1))) begin
        spike_count_q_ce0_local = 1'b1;
    end else begin
        spike_count_q_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
        spike_count_q_ce1_local = 1'b1;
    end else begin
        spike_count_q_ce1_local = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln36_reg_450_pp0_iter2_reg == 1'd0) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter3 == 1'b1) & (icmp_ln46_reg_490 == 1'd1))) begin
        spike_count_q_we0_local = 1'b1;
    end else begin
        spike_count_q_we0_local = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_pp0_stage0 : begin
            ap_NS_fsm = ap_ST_fsm_pp0_stage0;
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign add_ln36_1_fu_175_p2 = (ap_sig_allocacmp_indvar_flatten_load + 11'd1);

assign add_ln36_fu_222_p2 = (time_index_fu_86 + 6'd1);

assign add_ln37_fu_203_p2 = (select_ln36_fu_190_p3 + 6'd1);

assign add_ln43_fu_246_p2 = (tmp_fu_235_p3 + zext_ln43_fu_243_p1);

assign add_ln49_fu_422_p2 = (spike_count_q_q1 + 6'd1);

assign and_ln12_fu_347_p2 = (tmp_3_fu_293_p3 & icmp_ln12_fu_341_p2);

assign ap_CS_fsm_pp0_stage0 = ap_CS_fsm[32'd0];

assign ap_block_pp0_stage0 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage0_11001 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage0_subdone = ~(1'b1 == 1'b1);

assign ap_done = ap_done_sig;

assign ap_enable_pp0 = (ap_idle_pp0 ^ 1'b1);

assign ap_enable_reg_pp0_iter0 = ap_start_int;

assign ap_loop_exit_ready = ap_condition_exit_pp0_iter0_stage0;

assign ap_phi_reg_pp0_iter2_updated_2_reg_141 = 'bx;

assign ap_ready = ap_ready_sig;

assign beta_product_fu_261_p1 = 22'd58;

assign feature_current_q_address0 = zext_ln43_1_fu_252_p1;

assign feature_current_q_ce0 = feature_current_q_ce0_local;

assign icmp_ln11_fu_329_p2 = ((twice_remainder_fu_321_p3 > 7'd64) ? 1'b1 : 1'b0);

assign icmp_ln12_fu_341_p2 = ((twice_remainder_fu_321_p3 == 7'd64) ? 1'b1 : 1'b0);

assign icmp_ln36_fu_169_p2 = ((ap_sig_allocacmp_indvar_flatten_load == 11'd1536) ? 1'b1 : 1'b0);

assign icmp_ln37_fu_184_p2 = ((ap_sig_allocacmp_channel_load == 6'd32) ? 1'b1 : 1'b0);

assign icmp_ln46_fu_409_p2 = (($signed(tmp_4_fu_399_p4) > $signed(11'd0)) ? 1'b1 : 1'b0);

assign membrane_address0 = membrane_addr_reg_469_pp0_iter1_reg;

assign membrane_address1 = zext_ln37_fu_198_p1;

assign membrane_ce0 = membrane_ce0_local;

assign membrane_ce1 = membrane_ce1_local;

assign membrane_d0 = ap_phi_mux_updated_2_phi_fu_144_p4;

assign membrane_we0 = membrane_we0_local;

assign negative_fu_271_p3 = beta_product_fu_261_p2[32'd21];

assign or_ln12_fu_353_p2 = (icmp_ln11_fu_329_p2 | and_ln12_fu_347_p2);

assign quotient_4_fu_359_p3 = ((or_ln12_fu_353_p2[0:0] == 1'b1) ? quotient_fu_335_p2 : trunc_ln7_1_fu_301_p4);

assign quotient_fu_335_p2 = (trunc_ln7_1_fu_301_p4 + 15'd1);

assign select_ln17_fu_381_p3 = ((negative_reg_480[0:0] == 1'b1) ? sub_ln17_fu_375_p2 : zext_ln17_fu_372_p1);

assign select_ln36_1_fu_228_p3 = ((icmp_ln37_reg_454[0:0] == 1'b1) ? add_ln36_fu_222_p2 : time_index_fu_86);

assign select_ln36_fu_190_p3 = ((icmp_ln37_fu_184_p2[0:0] == 1'b1) ? 6'd0 : ap_sig_allocacmp_channel_load);

assign sext_ln39_fu_257_p0 = membrane_q1;

assign sext_ln43_fu_388_p1 = $signed(feature_current_q_q0);

assign signed_magnitude_4_fu_285_p3 = ((negative_fu_271_p3[0:0] == 1'b1) ? signed_magnitude_fu_279_p2 : trunc_ln3_fu_267_p1);

assign signed_magnitude_fu_279_p2 = (21'd0 - trunc_ln3_fu_267_p1);

assign spike_count_q_address0 = spike_count_q_addr_reg_494;

assign spike_count_q_address1 = zext_ln37_reg_464_pp0_iter1_reg;

assign spike_count_q_ce0 = spike_count_q_ce0_local;

assign spike_count_q_ce1 = spike_count_q_ce1_local;

assign spike_count_q_d0 = add_ln49_fu_422_p2;

assign spike_count_q_we0 = spike_count_q_we0_local;

assign sub_ln17_fu_375_p2 = (16'd0 - zext_ln17_fu_372_p1);

assign tmp_1_fu_311_p4 = {{signed_magnitude_4_fu_285_p3[5:1]}};

assign tmp_3_fu_293_p3 = signed_magnitude_4_fu_285_p3[32'd6];

assign tmp_4_fu_399_p4 = {{updated_fu_392_p2[15:5]}};

assign tmp_fu_235_p3 = {{select_ln36_1_fu_228_p3}, {5'd0}};

assign trunc_ln3_fu_267_p1 = beta_product_fu_261_p2[20:0];

assign trunc_ln7_1_fu_301_p4 = {{signed_magnitude_4_fu_285_p3[20:6]}};

assign twice_remainder_fu_321_p3 = {{tmp_1_fu_311_p4}, {2'd0}};

assign updated_1_fu_415_p2 = ($signed(updated_fu_392_p2) + $signed(16'd65504));

assign updated_fu_392_p2 = ($signed(select_ln17_fu_381_p3) + $signed(sext_ln43_fu_388_p1));

assign zext_ln17_fu_372_p1 = quotient_4_reg_485;

assign zext_ln37_fu_198_p1 = select_ln36_fu_190_p3;

assign zext_ln43_1_fu_252_p1 = add_ln43_fu_246_p2;

assign zext_ln43_fu_243_p1 = select_ln36_reg_459;

always @ (posedge ap_clk) begin
    zext_ln37_reg_464[63:6] <= 58'b0000000000000000000000000000000000000000000000000000000000;
    zext_ln37_reg_464_pp0_iter1_reg[63:6] <= 58'b0000000000000000000000000000000000000000000000000000000000;
end

endmodule //hybrid_lif_head_q12_6_run_hybrid_lif_head_Pipeline_VITIS_LOOP_36_2_VITIS_LOOP_37_3
