// ==============================================================
// Generated by Vitis HLS v2025.1
// Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// Copyright 2022-2025 Advanced Micro Devices, Inc. All Rights Reserved.
// ==============================================================

`timescale 1 ns / 1 ps 

module hybrid_lif_head_q12_6_run_hybrid_lif_head_Pipeline_VITIS_LOOP_59_4 (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_idle,
        ap_ready,
        spike_count_q_address0,
        spike_count_q_ce0,
        spike_count_q_q0,
        rate_q_address0,
        rate_q_ce0,
        rate_q_we0,
        rate_q_d0
);

parameter    ap_ST_fsm_pp0_stage0 = 1'd1;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
output   ap_idle;
output   ap_ready;
output  [4:0] spike_count_q_address0;
output   spike_count_q_ce0;
input  [5:0] spike_count_q_q0;
output  [4:0] rate_q_address0;
output   rate_q_ce0;
output   rate_q_we0;
output  [6:0] rate_q_d0;

reg ap_idle;

(* fsm_encoding = "none" *) reg   [0:0] ap_CS_fsm;
wire    ap_CS_fsm_pp0_stage0;
wire    ap_enable_reg_pp0_iter0;
reg    ap_enable_reg_pp0_iter1;
reg    ap_enable_reg_pp0_iter2;
reg    ap_enable_reg_pp0_iter3;
reg    ap_enable_reg_pp0_iter4;
reg    ap_enable_reg_pp0_iter5;
reg    ap_enable_reg_pp0_iter6;
reg    ap_enable_reg_pp0_iter7;
reg    ap_enable_reg_pp0_iter8;
reg    ap_enable_reg_pp0_iter9;
reg    ap_enable_reg_pp0_iter10;
reg    ap_enable_reg_pp0_iter11;
reg    ap_enable_reg_pp0_iter12;
reg    ap_idle_pp0;
wire    ap_block_pp0_stage0_subdone;
wire   [0:0] icmp_ln59_fu_94_p2;
reg    ap_condition_exit_pp0_iter0_stage0;
wire    ap_loop_exit_ready;
reg    ap_ready_int;
wire    ap_block_pp0_stage0_11001;
wire   [63:0] zext_ln59_fu_106_p1;
reg   [63:0] zext_ln59_reg_192;
reg   [63:0] zext_ln59_reg_192_pp0_iter1_reg;
reg   [63:0] zext_ln59_reg_192_pp0_iter2_reg;
reg   [63:0] zext_ln59_reg_192_pp0_iter3_reg;
reg   [63:0] zext_ln59_reg_192_pp0_iter4_reg;
reg   [63:0] zext_ln59_reg_192_pp0_iter5_reg;
reg   [63:0] zext_ln59_reg_192_pp0_iter6_reg;
reg   [63:0] zext_ln59_reg_192_pp0_iter7_reg;
reg   [63:0] zext_ln59_reg_192_pp0_iter8_reg;
reg   [63:0] zext_ln59_reg_192_pp0_iter9_reg;
reg   [63:0] zext_ln59_reg_192_pp0_iter10_reg;
reg   [63:0] zext_ln59_reg_192_pp0_iter11_reg;
wire   [7:0] shl_ln7_fu_116_p3;
reg   [6:0] trunc_ln_reg_207;
reg   [6:0] trunc_ln_reg_207_pp0_iter2_reg;
reg   [6:0] trunc_ln_reg_207_pp0_iter3_reg;
reg   [6:0] trunc_ln_reg_207_pp0_iter4_reg;
reg   [6:0] trunc_ln_reg_207_pp0_iter5_reg;
reg   [6:0] trunc_ln_reg_207_pp0_iter6_reg;
reg   [6:0] trunc_ln_reg_207_pp0_iter7_reg;
reg   [6:0] trunc_ln_reg_207_pp0_iter8_reg;
reg   [6:0] trunc_ln_reg_207_pp0_iter9_reg;
reg   [6:0] trunc_ln_reg_207_pp0_iter10_reg;
reg   [6:0] trunc_ln_reg_207_pp0_iter11_reg;
wire    ap_block_pp0_stage0;
reg   [5:0] channel_fu_56;
wire   [5:0] add_ln59_fu_100_p2;
wire    ap_loop_init;
reg   [5:0] ap_sig_allocacmp_channel_1;
reg    spike_count_q_ce0_local;
reg    rate_q_we0_local;
wire   [6:0] select_ln11_fu_173_p3;
reg    rate_q_ce0_local;
wire   [2:0] grp_fu_124_p1;
wire   [7:0] mul_ln13_fu_134_p0;
wire   [9:0] mul_ln13_fu_134_p1;
wire   [16:0] mul_ln13_fu_134_p2;
wire   [1:0] grp_fu_124_p2;
wire   [1:0] trunc_ln9_fu_150_p1;
wire   [6:0] twice_remainder_fu_154_p3;
wire   [0:0] icmp_ln11_fu_162_p2;
wire   [6:0] add_ln11_fu_168_p2;
reg    ap_done_reg;
wire    ap_continue_int;
reg    ap_done_int;
reg    ap_loop_exit_ready_pp0_iter1_reg;
reg    ap_loop_exit_ready_pp0_iter2_reg;
reg    ap_loop_exit_ready_pp0_iter3_reg;
reg    ap_loop_exit_ready_pp0_iter4_reg;
reg    ap_loop_exit_ready_pp0_iter5_reg;
reg    ap_loop_exit_ready_pp0_iter6_reg;
reg    ap_loop_exit_ready_pp0_iter7_reg;
reg    ap_loop_exit_ready_pp0_iter8_reg;
reg    ap_loop_exit_ready_pp0_iter9_reg;
reg    ap_loop_exit_ready_pp0_iter10_reg;
reg    ap_loop_exit_ready_pp0_iter11_reg;
reg   [0:0] ap_NS_fsm;
wire    ap_enable_pp0;
wire    ap_start_int;
wire    ap_ready_sig;
wire    ap_done_sig;
wire   [16:0] mul_ln13_fu_134_p00;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_CS_fsm = 1'd1;
#0 ap_enable_reg_pp0_iter1 = 1'b0;
#0 ap_enable_reg_pp0_iter2 = 1'b0;
#0 ap_enable_reg_pp0_iter3 = 1'b0;
#0 ap_enable_reg_pp0_iter4 = 1'b0;
#0 ap_enable_reg_pp0_iter5 = 1'b0;
#0 ap_enable_reg_pp0_iter6 = 1'b0;
#0 ap_enable_reg_pp0_iter7 = 1'b0;
#0 ap_enable_reg_pp0_iter8 = 1'b0;
#0 ap_enable_reg_pp0_iter9 = 1'b0;
#0 ap_enable_reg_pp0_iter10 = 1'b0;
#0 ap_enable_reg_pp0_iter11 = 1'b0;
#0 ap_enable_reg_pp0_iter12 = 1'b0;
#0 channel_fu_56 = 6'd0;
#0 ap_done_reg = 1'b0;
end

hybrid_lif_head_q12_6_urem_8ns_3ns_2_12_1 #(
    .ID( 1 ),
    .NUM_STAGE( 12 ),
    .din0_WIDTH( 8 ),
    .din1_WIDTH( 3 ),
    .dout_WIDTH( 2 ))
urem_8ns_3ns_2_12_1_U8(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(shl_ln7_fu_116_p3),
    .din1(grp_fu_124_p1),
    .ce(1'b1),
    .dout(grp_fu_124_p2)
);

hybrid_lif_head_q12_6_mul_8ns_10ns_17_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 8 ),
    .din1_WIDTH( 10 ),
    .dout_WIDTH( 17 ))
mul_8ns_10ns_17_1_1_U9(
    .din0(mul_ln13_fu_134_p0),
    .din1(mul_ln13_fu_134_p1),
    .dout(mul_ln13_fu_134_p2)
);

hybrid_lif_head_q12_6_flow_control_loop_pipe_sequential_init flow_control_loop_pipe_sequential_init_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(ap_start),
    .ap_ready(ap_ready_sig),
    .ap_done(ap_done_sig),
    .ap_start_int(ap_start_int),
    .ap_loop_init(ap_loop_init),
    .ap_ready_int(ap_ready_int),
    .ap_loop_exit_ready(ap_condition_exit_pp0_iter0_stage0),
    .ap_loop_exit_done(ap_done_int),
    .ap_continue_int(ap_continue_int),
    .ap_done_int(ap_done_int)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_pp0_stage0;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_done_reg <= 1'b0;
    end else begin
        if ((ap_continue_int == 1'b1)) begin
            ap_done_reg <= 1'b0;
        end else if (((1'b0 == ap_block_pp0_stage0_subdone) & (ap_loop_exit_ready_pp0_iter11_reg == 1'b1))) begin
            ap_done_reg <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter1 <= 1'b0;
    end else begin
        if ((1'b1 == ap_condition_exit_pp0_iter0_stage0)) begin
            ap_enable_reg_pp0_iter1 <= 1'b0;
        end else if (((1'b0 == ap_block_pp0_stage0_subdone) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            ap_enable_reg_pp0_iter1 <= ap_start_int;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter10 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter10 <= ap_enable_reg_pp0_iter9;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter11 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter11 <= ap_enable_reg_pp0_iter10;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter12 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter12 <= ap_enable_reg_pp0_iter11;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter2 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter2 <= ap_enable_reg_pp0_iter1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter3 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter3 <= ap_enable_reg_pp0_iter2;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter4 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter4 <= ap_enable_reg_pp0_iter3;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter5 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter5 <= ap_enable_reg_pp0_iter4;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter6 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter6 <= ap_enable_reg_pp0_iter5;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter7 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter7 <= ap_enable_reg_pp0_iter6;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter8 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter8 <= ap_enable_reg_pp0_iter7;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter9 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter9 <= ap_enable_reg_pp0_iter8;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        if (((icmp_ln59_fu_94_p2 == 1'd0) & (ap_enable_reg_pp0_iter0 == 1'b1))) begin
            channel_fu_56 <= add_ln59_fu_100_p2;
        end else if ((ap_loop_init == 1'b1)) begin
            channel_fu_56 <= 6'd0;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b0 == ap_block_pp0_stage0_11001)) begin
        ap_loop_exit_ready_pp0_iter10_reg <= ap_loop_exit_ready_pp0_iter9_reg;
        ap_loop_exit_ready_pp0_iter11_reg <= ap_loop_exit_ready_pp0_iter10_reg;
        ap_loop_exit_ready_pp0_iter3_reg <= ap_loop_exit_ready_pp0_iter2_reg;
        ap_loop_exit_ready_pp0_iter4_reg <= ap_loop_exit_ready_pp0_iter3_reg;
        ap_loop_exit_ready_pp0_iter5_reg <= ap_loop_exit_ready_pp0_iter4_reg;
        ap_loop_exit_ready_pp0_iter6_reg <= ap_loop_exit_ready_pp0_iter5_reg;
        ap_loop_exit_ready_pp0_iter7_reg <= ap_loop_exit_ready_pp0_iter6_reg;
        ap_loop_exit_ready_pp0_iter8_reg <= ap_loop_exit_ready_pp0_iter7_reg;
        ap_loop_exit_ready_pp0_iter9_reg <= ap_loop_exit_ready_pp0_iter8_reg;
        trunc_ln_reg_207_pp0_iter10_reg <= trunc_ln_reg_207_pp0_iter9_reg;
        trunc_ln_reg_207_pp0_iter11_reg <= trunc_ln_reg_207_pp0_iter10_reg;
        trunc_ln_reg_207_pp0_iter2_reg <= trunc_ln_reg_207;
        trunc_ln_reg_207_pp0_iter3_reg <= trunc_ln_reg_207_pp0_iter2_reg;
        trunc_ln_reg_207_pp0_iter4_reg <= trunc_ln_reg_207_pp0_iter3_reg;
        trunc_ln_reg_207_pp0_iter5_reg <= trunc_ln_reg_207_pp0_iter4_reg;
        trunc_ln_reg_207_pp0_iter6_reg <= trunc_ln_reg_207_pp0_iter5_reg;
        trunc_ln_reg_207_pp0_iter7_reg <= trunc_ln_reg_207_pp0_iter6_reg;
        trunc_ln_reg_207_pp0_iter8_reg <= trunc_ln_reg_207_pp0_iter7_reg;
        trunc_ln_reg_207_pp0_iter9_reg <= trunc_ln_reg_207_pp0_iter8_reg;
        zext_ln59_reg_192_pp0_iter10_reg[5 : 0] <= zext_ln59_reg_192_pp0_iter9_reg[5 : 0];
        zext_ln59_reg_192_pp0_iter11_reg[5 : 0] <= zext_ln59_reg_192_pp0_iter10_reg[5 : 0];
        zext_ln59_reg_192_pp0_iter2_reg[5 : 0] <= zext_ln59_reg_192_pp0_iter1_reg[5 : 0];
        zext_ln59_reg_192_pp0_iter3_reg[5 : 0] <= zext_ln59_reg_192_pp0_iter2_reg[5 : 0];
        zext_ln59_reg_192_pp0_iter4_reg[5 : 0] <= zext_ln59_reg_192_pp0_iter3_reg[5 : 0];
        zext_ln59_reg_192_pp0_iter5_reg[5 : 0] <= zext_ln59_reg_192_pp0_iter4_reg[5 : 0];
        zext_ln59_reg_192_pp0_iter6_reg[5 : 0] <= zext_ln59_reg_192_pp0_iter5_reg[5 : 0];
        zext_ln59_reg_192_pp0_iter7_reg[5 : 0] <= zext_ln59_reg_192_pp0_iter6_reg[5 : 0];
        zext_ln59_reg_192_pp0_iter8_reg[5 : 0] <= zext_ln59_reg_192_pp0_iter7_reg[5 : 0];
        zext_ln59_reg_192_pp0_iter9_reg[5 : 0] <= zext_ln59_reg_192_pp0_iter8_reg[5 : 0];
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_loop_exit_ready_pp0_iter1_reg <= ap_loop_exit_ready;
        ap_loop_exit_ready_pp0_iter2_reg <= ap_loop_exit_ready_pp0_iter1_reg;
        trunc_ln_reg_207 <= {{mul_ln13_fu_134_p2[16:10]}};
        zext_ln59_reg_192[5 : 0] <= zext_ln59_fu_106_p1[5 : 0];
        zext_ln59_reg_192_pp0_iter1_reg[5 : 0] <= zext_ln59_reg_192[5 : 0];
    end
end

always @ (*) begin
    if (((icmp_ln59_fu_94_p2 == 1'd1) & (1'b0 == ap_block_pp0_stage0_subdone) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_condition_exit_pp0_iter0_stage0 = 1'b1;
    end else begin
        ap_condition_exit_pp0_iter0_stage0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_subdone) & (ap_loop_exit_ready_pp0_iter11_reg == 1'b1))) begin
        ap_done_int = 1'b1;
    end else begin
        ap_done_int = ap_done_reg;
    end
end

always @ (*) begin
    if (((ap_idle_pp0 == 1'b1) & (ap_start_int == 1'b0) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter12 == 1'b0) & (ap_enable_reg_pp0_iter11 == 1'b0) & (ap_enable_reg_pp0_iter10 == 1'b0) & (ap_enable_reg_pp0_iter9 == 1'b0) & (ap_enable_reg_pp0_iter8 == 1'b0) & (ap_enable_reg_pp0_iter7 == 1'b0) & (ap_enable_reg_pp0_iter6 == 1'b0) & (ap_enable_reg_pp0_iter5 == 1'b0) & (ap_enable_reg_pp0_iter4 == 1'b0) & (ap_enable_reg_pp0_iter3 == 1'b0) & (ap_enable_reg_pp0_iter2 == 1'b0) & (ap_enable_reg_pp0_iter1 == 1'b0) & (ap_enable_reg_pp0_iter0 == 1'b0))) begin
        ap_idle_pp0 = 1'b1;
    end else begin
        ap_idle_pp0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_subdone) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_ready_int = 1'b1;
    end else begin
        ap_ready_int = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (1'b1 == ap_CS_fsm_pp0_stage0) & (ap_loop_init == 1'b1))) begin
        ap_sig_allocacmp_channel_1 = 6'd0;
    end else begin
        ap_sig_allocacmp_channel_1 = channel_fu_56;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter12 == 1'b1))) begin
        rate_q_ce0_local = 1'b1;
    end else begin
        rate_q_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter12 == 1'b1))) begin
        rate_q_we0_local = 1'b1;
    end else begin
        rate_q_we0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        spike_count_q_ce0_local = 1'b1;
    end else begin
        spike_count_q_ce0_local = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_pp0_stage0 : begin
            ap_NS_fsm = ap_ST_fsm_pp0_stage0;
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign add_ln11_fu_168_p2 = (trunc_ln_reg_207_pp0_iter11_reg + 7'd1);

assign add_ln59_fu_100_p2 = (ap_sig_allocacmp_channel_1 + 6'd1);

assign ap_CS_fsm_pp0_stage0 = ap_CS_fsm[32'd0];

assign ap_block_pp0_stage0 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage0_11001 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage0_subdone = ~(1'b1 == 1'b1);

assign ap_done = ap_done_sig;

assign ap_enable_pp0 = (ap_idle_pp0 ^ 1'b1);

assign ap_enable_reg_pp0_iter0 = ap_start_int;

assign ap_loop_exit_ready = ap_condition_exit_pp0_iter0_stage0;

assign ap_ready = ap_ready_sig;

assign grp_fu_124_p1 = 8'd3;

assign icmp_ln11_fu_162_p2 = ((twice_remainder_fu_154_p3 > 7'd48) ? 1'b1 : 1'b0);

assign icmp_ln59_fu_94_p2 = ((ap_sig_allocacmp_channel_1 == 6'd32) ? 1'b1 : 1'b0);

assign mul_ln13_fu_134_p0 = mul_ln13_fu_134_p00;

assign mul_ln13_fu_134_p00 = shl_ln7_fu_116_p3;

assign mul_ln13_fu_134_p1 = 17'd342;

assign rate_q_address0 = zext_ln59_reg_192_pp0_iter11_reg;

assign rate_q_ce0 = rate_q_ce0_local;

assign rate_q_d0 = select_ln11_fu_173_p3;

assign rate_q_we0 = rate_q_we0_local;

assign select_ln11_fu_173_p3 = ((icmp_ln11_fu_162_p2[0:0] == 1'b1) ? add_ln11_fu_168_p2 : trunc_ln_reg_207_pp0_iter11_reg);

assign shl_ln7_fu_116_p3 = {{spike_count_q_q0}, {2'd0}};

assign spike_count_q_address0 = zext_ln59_fu_106_p1;

assign spike_count_q_ce0 = spike_count_q_ce0_local;

assign trunc_ln9_fu_150_p1 = grp_fu_124_p2[1:0];

assign twice_remainder_fu_154_p3 = {{trunc_ln9_fu_150_p1}, {5'd0}};

assign zext_ln59_fu_106_p1 = ap_sig_allocacmp_channel_1;

always @ (posedge ap_clk) begin
    zext_ln59_reg_192[63:6] <= 58'b0000000000000000000000000000000000000000000000000000000000;
    zext_ln59_reg_192_pp0_iter1_reg[63:6] <= 58'b0000000000000000000000000000000000000000000000000000000000;
    zext_ln59_reg_192_pp0_iter2_reg[63:6] <= 58'b0000000000000000000000000000000000000000000000000000000000;
    zext_ln59_reg_192_pp0_iter3_reg[63:6] <= 58'b0000000000000000000000000000000000000000000000000000000000;
    zext_ln59_reg_192_pp0_iter4_reg[63:6] <= 58'b0000000000000000000000000000000000000000000000000000000000;
    zext_ln59_reg_192_pp0_iter5_reg[63:6] <= 58'b0000000000000000000000000000000000000000000000000000000000;
    zext_ln59_reg_192_pp0_iter6_reg[63:6] <= 58'b0000000000000000000000000000000000000000000000000000000000;
    zext_ln59_reg_192_pp0_iter7_reg[63:6] <= 58'b0000000000000000000000000000000000000000000000000000000000;
    zext_ln59_reg_192_pp0_iter8_reg[63:6] <= 58'b0000000000000000000000000000000000000000000000000000000000;
    zext_ln59_reg_192_pp0_iter9_reg[63:6] <= 58'b0000000000000000000000000000000000000000000000000000000000;
    zext_ln59_reg_192_pp0_iter10_reg[63:6] <= 58'b0000000000000000000000000000000000000000000000000000000000;
    zext_ln59_reg_192_pp0_iter11_reg[63:6] <= 58'b0000000000000000000000000000000000000000000000000000000000;
end

endmodule //hybrid_lif_head_q12_6_run_hybrid_lif_head_Pipeline_VITIS_LOOP_59_4
