// ==============================================================
// Generated by Vitis HLS v2025.1
// Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// Copyright 2022-2025 Advanced Micro Devices, Inc. All Rights Reserved.
// ==============================================================

`timescale 1 ns / 1 ps 

module hybrid_lif_head_q12_6_run_hybrid_lif_head (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_idle,
        ap_ready,
        feature_current_q_address0,
        feature_current_q_ce0,
        feature_current_q_q0,
        weight_q_address0,
        weight_q_ce0,
        weight_q_q0,
        weight_q_address1,
        weight_q_ce1,
        weight_q_q1,
        bias_q_address0,
        bias_q_ce0,
        bias_q_q0,
        logits_q_address0,
        logits_q_ce0,
        logits_q_we0,
        logits_q_d0,
        spike_count_q_address0,
        spike_count_q_ce0,
        spike_count_q_we0,
        spike_count_q_d0,
        spike_count_q_q0,
        spike_count_q_address1,
        spike_count_q_ce1,
        spike_count_q_q1
);

parameter    ap_ST_fsm_state1 = 24'd1;
parameter    ap_ST_fsm_state2 = 24'd2;
parameter    ap_ST_fsm_state3 = 24'd4;
parameter    ap_ST_fsm_state4 = 24'd8;
parameter    ap_ST_fsm_state5 = 24'd16;
parameter    ap_ST_fsm_state6 = 24'd32;
parameter    ap_ST_fsm_state7 = 24'd64;
parameter    ap_ST_fsm_state8 = 24'd128;
parameter    ap_ST_fsm_state9 = 24'd256;
parameter    ap_ST_fsm_state10 = 24'd512;
parameter    ap_ST_fsm_state11 = 24'd1024;
parameter    ap_ST_fsm_state12 = 24'd2048;
parameter    ap_ST_fsm_state13 = 24'd4096;
parameter    ap_ST_fsm_state14 = 24'd8192;
parameter    ap_ST_fsm_state15 = 24'd16384;
parameter    ap_ST_fsm_state16 = 24'd32768;
parameter    ap_ST_fsm_state17 = 24'd65536;
parameter    ap_ST_fsm_state18 = 24'd131072;
parameter    ap_ST_fsm_state19 = 24'd262144;
parameter    ap_ST_fsm_state20 = 24'd524288;
parameter    ap_ST_fsm_state21 = 24'd1048576;
parameter    ap_ST_fsm_state22 = 24'd2097152;
parameter    ap_ST_fsm_state23 = 24'd4194304;
parameter    ap_ST_fsm_state24 = 24'd8388608;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
output   ap_idle;
output   ap_ready;
output  [10:0] feature_current_q_address0;
output   feature_current_q_ce0;
input  [11:0] feature_current_q_q0;
output  [5:0] weight_q_address0;
output   weight_q_ce0;
input  [11:0] weight_q_q0;
output  [5:0] weight_q_address1;
output   weight_q_ce1;
input  [11:0] weight_q_q1;
output  [0:0] bias_q_address0;
output   bias_q_ce0;
input  [11:0] bias_q_q0;
output  [0:0] logits_q_address0;
output   logits_q_ce0;
output   logits_q_we0;
output  [17:0] logits_q_d0;
output  [4:0] spike_count_q_address0;
output   spike_count_q_ce0;
output   spike_count_q_we0;
output  [5:0] spike_count_q_d0;
input  [5:0] spike_count_q_q0;
output  [4:0] spike_count_q_address1;
output   spike_count_q_ce1;
input  [5:0] spike_count_q_q1;

reg ap_done;
reg ap_idle;
reg ap_ready;
reg[4:0] spike_count_q_address0;
reg spike_count_q_ce0;
reg spike_count_q_we0;
reg[5:0] spike_count_q_d0;
reg spike_count_q_ce1;

(* fsm_encoding = "none" *) reg   [23:0] ap_CS_fsm;
wire    ap_CS_fsm_state1;
wire    ap_CS_fsm_state7;
reg   [6:0] rate_q_load_reg_443;
wire    ap_CS_fsm_state8;
reg   [6:0] rate_q_load_1_reg_448;
reg   [6:0] rate_q_load_2_reg_463;
wire    ap_CS_fsm_state9;
reg   [6:0] rate_q_load_3_reg_468;
reg   [6:0] rate_q_load_4_reg_483;
wire    ap_CS_fsm_state10;
reg   [6:0] rate_q_load_5_reg_488;
reg   [6:0] rate_q_load_6_reg_503;
wire    ap_CS_fsm_state11;
reg   [6:0] rate_q_load_7_reg_508;
reg   [6:0] rate_q_load_8_reg_523;
wire    ap_CS_fsm_state12;
reg   [6:0] rate_q_load_9_reg_528;
reg   [6:0] rate_q_load_10_reg_543;
wire    ap_CS_fsm_state13;
reg   [6:0] rate_q_load_11_reg_548;
reg   [6:0] rate_q_load_12_reg_563;
wire    ap_CS_fsm_state14;
reg   [6:0] rate_q_load_13_reg_568;
reg   [6:0] rate_q_load_14_reg_583;
wire    ap_CS_fsm_state15;
reg   [6:0] rate_q_load_15_reg_588;
reg   [6:0] rate_q_load_16_reg_603;
wire    ap_CS_fsm_state16;
reg   [6:0] rate_q_load_17_reg_608;
reg   [6:0] rate_q_load_18_reg_623;
wire    ap_CS_fsm_state17;
reg   [6:0] rate_q_load_19_reg_628;
reg   [6:0] rate_q_load_20_reg_643;
wire    ap_CS_fsm_state18;
reg   [6:0] rate_q_load_21_reg_648;
reg   [6:0] rate_q_load_22_reg_663;
wire    ap_CS_fsm_state19;
reg   [6:0] rate_q_load_23_reg_668;
reg   [6:0] rate_q_load_24_reg_683;
wire    ap_CS_fsm_state20;
reg   [6:0] rate_q_load_25_reg_688;
reg   [6:0] rate_q_load_26_reg_703;
wire    ap_CS_fsm_state21;
reg   [6:0] rate_q_load_27_reg_708;
reg   [6:0] rate_q_load_28_reg_723;
wire    ap_CS_fsm_state22;
reg   [6:0] rate_q_load_29_reg_728;
reg   [6:0] rate_q_load_30_reg_743;
wire    ap_CS_fsm_state23;
reg   [6:0] rate_q_load_31_reg_748;
reg   [4:0] membrane_address0;
reg    membrane_ce0;
reg    membrane_we0;
reg   [15:0] membrane_d0;
reg    membrane_ce1;
wire   [15:0] membrane_q1;
reg   [4:0] rate_q_address0;
reg    rate_q_ce0;
reg    rate_q_we0;
wire   [6:0] rate_q_q0;
wire   [6:0] rate_q_q1;
wire    grp_run_hybrid_lif_head_Pipeline_VITIS_LOOP_31_1_fu_365_ap_start;
wire    grp_run_hybrid_lif_head_Pipeline_VITIS_LOOP_31_1_fu_365_ap_done;
wire    grp_run_hybrid_lif_head_Pipeline_VITIS_LOOP_31_1_fu_365_ap_idle;
wire    grp_run_hybrid_lif_head_Pipeline_VITIS_LOOP_31_1_fu_365_ap_ready;
wire   [4:0] grp_run_hybrid_lif_head_Pipeline_VITIS_LOOP_31_1_fu_365_membrane_address0;
wire    grp_run_hybrid_lif_head_Pipeline_VITIS_LOOP_31_1_fu_365_membrane_ce0;
wire    grp_run_hybrid_lif_head_Pipeline_VITIS_LOOP_31_1_fu_365_membrane_we0;
wire   [15:0] grp_run_hybrid_lif_head_Pipeline_VITIS_LOOP_31_1_fu_365_membrane_d0;
wire   [4:0] grp_run_hybrid_lif_head_Pipeline_VITIS_LOOP_31_1_fu_365_spike_count_q_address0;
wire    grp_run_hybrid_lif_head_Pipeline_VITIS_LOOP_31_1_fu_365_spike_count_q_ce0;
wire    grp_run_hybrid_lif_head_Pipeline_VITIS_LOOP_31_1_fu_365_spike_count_q_we0;
wire   [5:0] grp_run_hybrid_lif_head_Pipeline_VITIS_LOOP_31_1_fu_365_spike_count_q_d0;
wire    grp_run_hybrid_lif_head_Pipeline_VITIS_LOOP_36_2_VITIS_LOOP_37_3_fu_373_ap_start;
wire    grp_run_hybrid_lif_head_Pipeline_VITIS_LOOP_36_2_VITIS_LOOP_37_3_fu_373_ap_done;
wire    grp_run_hybrid_lif_head_Pipeline_VITIS_LOOP_36_2_VITIS_LOOP_37_3_fu_373_ap_idle;
wire    grp_run_hybrid_lif_head_Pipeline_VITIS_LOOP_36_2_VITIS_LOOP_37_3_fu_373_ap_ready;
wire   [10:0] grp_run_hybrid_lif_head_Pipeline_VITIS_LOOP_36_2_VITIS_LOOP_37_3_fu_373_feature_current_q_address0;
wire    grp_run_hybrid_lif_head_Pipeline_VITIS_LOOP_36_2_VITIS_LOOP_37_3_fu_373_feature_current_q_ce0;
wire   [4:0] grp_run_hybrid_lif_head_Pipeline_VITIS_LOOP_36_2_VITIS_LOOP_37_3_fu_373_membrane_address0;
wire    grp_run_hybrid_lif_head_Pipeline_VITIS_LOOP_36_2_VITIS_LOOP_37_3_fu_373_membrane_ce0;
wire    grp_run_hybrid_lif_head_Pipeline_VITIS_LOOP_36_2_VITIS_LOOP_37_3_fu_373_membrane_we0;
wire   [15:0] grp_run_hybrid_lif_head_Pipeline_VITIS_LOOP_36_2_VITIS_LOOP_37_3_fu_373_membrane_d0;
wire   [4:0] grp_run_hybrid_lif_head_Pipeline_VITIS_LOOP_36_2_VITIS_LOOP_37_3_fu_373_membrane_address1;
wire    grp_run_hybrid_lif_head_Pipeline_VITIS_LOOP_36_2_VITIS_LOOP_37_3_fu_373_membrane_ce1;
wire   [4:0] grp_run_hybrid_lif_head_Pipeline_VITIS_LOOP_36_2_VITIS_LOOP_37_3_fu_373_spike_count_q_address0;
wire    grp_run_hybrid_lif_head_Pipeline_VITIS_LOOP_36_2_VITIS_LOOP_37_3_fu_373_spike_count_q_ce0;
wire    grp_run_hybrid_lif_head_Pipeline_VITIS_LOOP_36_2_VITIS_LOOP_37_3_fu_373_spike_count_q_we0;
wire   [5:0] grp_run_hybrid_lif_head_Pipeline_VITIS_LOOP_36_2_VITIS_LOOP_37_3_fu_373_spike_count_q_d0;
wire   [4:0] grp_run_hybrid_lif_head_Pipeline_VITIS_LOOP_36_2_VITIS_LOOP_37_3_fu_373_spike_count_q_address1;
wire    grp_run_hybrid_lif_head_Pipeline_VITIS_LOOP_36_2_VITIS_LOOP_37_3_fu_373_spike_count_q_ce1;
wire    grp_run_hybrid_lif_head_Pipeline_VITIS_LOOP_59_4_fu_382_ap_start;
wire    grp_run_hybrid_lif_head_Pipeline_VITIS_LOOP_59_4_fu_382_ap_done;
wire    grp_run_hybrid_lif_head_Pipeline_VITIS_LOOP_59_4_fu_382_ap_idle;
wire    grp_run_hybrid_lif_head_Pipeline_VITIS_LOOP_59_4_fu_382_ap_ready;
wire   [4:0] grp_run_hybrid_lif_head_Pipeline_VITIS_LOOP_59_4_fu_382_spike_count_q_address0;
wire    grp_run_hybrid_lif_head_Pipeline_VITIS_LOOP_59_4_fu_382_spike_count_q_ce0;
wire   [4:0] grp_run_hybrid_lif_head_Pipeline_VITIS_LOOP_59_4_fu_382_rate_q_address0;
wire    grp_run_hybrid_lif_head_Pipeline_VITIS_LOOP_59_4_fu_382_rate_q_ce0;
wire    grp_run_hybrid_lif_head_Pipeline_VITIS_LOOP_59_4_fu_382_rate_q_we0;
wire   [6:0] grp_run_hybrid_lif_head_Pipeline_VITIS_LOOP_59_4_fu_382_rate_q_d0;
wire    grp_run_hybrid_lif_head_Pipeline_VITIS_LOOP_66_5_fu_389_ap_start;
wire    grp_run_hybrid_lif_head_Pipeline_VITIS_LOOP_66_5_fu_389_ap_done;
wire    grp_run_hybrid_lif_head_Pipeline_VITIS_LOOP_66_5_fu_389_ap_idle;
wire    grp_run_hybrid_lif_head_Pipeline_VITIS_LOOP_66_5_fu_389_ap_ready;
wire   [5:0] grp_run_hybrid_lif_head_Pipeline_VITIS_LOOP_66_5_fu_389_weight_q_address0;
wire    grp_run_hybrid_lif_head_Pipeline_VITIS_LOOP_66_5_fu_389_weight_q_ce0;
wire   [5:0] grp_run_hybrid_lif_head_Pipeline_VITIS_LOOP_66_5_fu_389_weight_q_address1;
wire    grp_run_hybrid_lif_head_Pipeline_VITIS_LOOP_66_5_fu_389_weight_q_ce1;
wire   [0:0] grp_run_hybrid_lif_head_Pipeline_VITIS_LOOP_66_5_fu_389_bias_q_address0;
wire    grp_run_hybrid_lif_head_Pipeline_VITIS_LOOP_66_5_fu_389_bias_q_ce0;
wire   [0:0] grp_run_hybrid_lif_head_Pipeline_VITIS_LOOP_66_5_fu_389_logits_q_address0;
wire    grp_run_hybrid_lif_head_Pipeline_VITIS_LOOP_66_5_fu_389_logits_q_ce0;
wire    grp_run_hybrid_lif_head_Pipeline_VITIS_LOOP_66_5_fu_389_logits_q_we0;
wire   [17:0] grp_run_hybrid_lif_head_Pipeline_VITIS_LOOP_66_5_fu_389_logits_q_d0;
reg    grp_run_hybrid_lif_head_Pipeline_VITIS_LOOP_31_1_fu_365_ap_start_reg;
wire    ap_CS_fsm_state2;
reg    grp_run_hybrid_lif_head_Pipeline_VITIS_LOOP_36_2_VITIS_LOOP_37_3_fu_373_ap_start_reg;
wire    ap_CS_fsm_state3;
wire    ap_CS_fsm_state4;
reg    grp_run_hybrid_lif_head_Pipeline_VITIS_LOOP_59_4_fu_382_ap_start_reg;
wire    ap_CS_fsm_state5;
wire    ap_CS_fsm_state6;
reg    grp_run_hybrid_lif_head_Pipeline_VITIS_LOOP_66_5_fu_389_ap_start_reg;
wire    ap_CS_fsm_state24;
reg    rate_q_ce1_local;
reg   [4:0] rate_q_address1_local;
reg    rate_q_ce0_local;
reg   [4:0] rate_q_address0_local;
reg   [23:0] ap_NS_fsm;
reg    ap_ST_fsm_state1_blk;
reg    ap_ST_fsm_state2_blk;
wire    ap_ST_fsm_state3_blk;
reg    ap_ST_fsm_state4_blk;
wire    ap_ST_fsm_state5_blk;
reg    ap_ST_fsm_state6_blk;
wire    ap_ST_fsm_state7_blk;
wire    ap_ST_fsm_state8_blk;
wire    ap_ST_fsm_state9_blk;
wire    ap_ST_fsm_state10_blk;
wire    ap_ST_fsm_state11_blk;
wire    ap_ST_fsm_state12_blk;
wire    ap_ST_fsm_state13_blk;
wire    ap_ST_fsm_state14_blk;
wire    ap_ST_fsm_state15_blk;
wire    ap_ST_fsm_state16_blk;
wire    ap_ST_fsm_state17_blk;
wire    ap_ST_fsm_state18_blk;
wire    ap_ST_fsm_state19_blk;
wire    ap_ST_fsm_state20_blk;
wire    ap_ST_fsm_state21_blk;
wire    ap_ST_fsm_state22_blk;
wire    ap_ST_fsm_state23_blk;
reg    ap_ST_fsm_state24_blk;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_CS_fsm = 24'd1;
#0 grp_run_hybrid_lif_head_Pipeline_VITIS_LOOP_31_1_fu_365_ap_start_reg = 1'b0;
#0 grp_run_hybrid_lif_head_Pipeline_VITIS_LOOP_36_2_VITIS_LOOP_37_3_fu_373_ap_start_reg = 1'b0;
#0 grp_run_hybrid_lif_head_Pipeline_VITIS_LOOP_59_4_fu_382_ap_start_reg = 1'b0;
#0 grp_run_hybrid_lif_head_Pipeline_VITIS_LOOP_66_5_fu_389_ap_start_reg = 1'b0;
end

hybrid_lif_head_q12_6_run_hybrid_lif_head_membrane_RAM_AUTO_1R1W #(
    .DataWidth( 16 ),
    .AddressRange( 32 ),
    .AddressWidth( 5 ))
membrane_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(membrane_address0),
    .ce0(membrane_ce0),
    .we0(membrane_we0),
    .d0(membrane_d0),
    .address1(grp_run_hybrid_lif_head_Pipeline_VITIS_LOOP_36_2_VITIS_LOOP_37_3_fu_373_membrane_address1),
    .ce1(membrane_ce1),
    .q1(membrane_q1)
);

hybrid_lif_head_q12_6_run_hybrid_lif_head_rate_q_RAM_AUTO_1R1W #(
    .DataWidth( 7 ),
    .AddressRange( 32 ),
    .AddressWidth( 5 ))
rate_q_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(rate_q_address0),
    .ce0(rate_q_ce0),
    .we0(rate_q_we0),
    .d0(grp_run_hybrid_lif_head_Pipeline_VITIS_LOOP_59_4_fu_382_rate_q_d0),
    .q0(rate_q_q0),
    .address1(rate_q_address1_local),
    .ce1(rate_q_ce1_local),
    .q1(rate_q_q1)
);

hybrid_lif_head_q12_6_run_hybrid_lif_head_Pipeline_VITIS_LOOP_31_1 grp_run_hybrid_lif_head_Pipeline_VITIS_LOOP_31_1_fu_365(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(grp_run_hybrid_lif_head_Pipeline_VITIS_LOOP_31_1_fu_365_ap_start),
    .ap_done(grp_run_hybrid_lif_head_Pipeline_VITIS_LOOP_31_1_fu_365_ap_done),
    .ap_idle(grp_run_hybrid_lif_head_Pipeline_VITIS_LOOP_31_1_fu_365_ap_idle),
    .ap_ready(grp_run_hybrid_lif_head_Pipeline_VITIS_LOOP_31_1_fu_365_ap_ready),
    .membrane_address0(grp_run_hybrid_lif_head_Pipeline_VITIS_LOOP_31_1_fu_365_membrane_address0),
    .membrane_ce0(grp_run_hybrid_lif_head_Pipeline_VITIS_LOOP_31_1_fu_365_membrane_ce0),
    .membrane_we0(grp_run_hybrid_lif_head_Pipeline_VITIS_LOOP_31_1_fu_365_membrane_we0),
    .membrane_d0(grp_run_hybrid_lif_head_Pipeline_VITIS_LOOP_31_1_fu_365_membrane_d0),
    .spike_count_q_address0(grp_run_hybrid_lif_head_Pipeline_VITIS_LOOP_31_1_fu_365_spike_count_q_address0),
    .spike_count_q_ce0(grp_run_hybrid_lif_head_Pipeline_VITIS_LOOP_31_1_fu_365_spike_count_q_ce0),
    .spike_count_q_we0(grp_run_hybrid_lif_head_Pipeline_VITIS_LOOP_31_1_fu_365_spike_count_q_we0),
    .spike_count_q_d0(grp_run_hybrid_lif_head_Pipeline_VITIS_LOOP_31_1_fu_365_spike_count_q_d0)
);

hybrid_lif_head_q12_6_run_hybrid_lif_head_Pipeline_VITIS_LOOP_36_2_VITIS_LOOP_37_3 grp_run_hybrid_lif_head_Pipeline_VITIS_LOOP_36_2_VITIS_LOOP_37_3_fu_373(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(grp_run_hybrid_lif_head_Pipeline_VITIS_LOOP_36_2_VITIS_LOOP_37_3_fu_373_ap_start),
    .ap_done(grp_run_hybrid_lif_head_Pipeline_VITIS_LOOP_36_2_VITIS_LOOP_37_3_fu_373_ap_done),
    .ap_idle(grp_run_hybrid_lif_head_Pipeline_VITIS_LOOP_36_2_VITIS_LOOP_37_3_fu_373_ap_idle),
    .ap_ready(grp_run_hybrid_lif_head_Pipeline_VITIS_LOOP_36_2_VITIS_LOOP_37_3_fu_373_ap_ready),
    .feature_current_q_address0(grp_run_hybrid_lif_head_Pipeline_VITIS_LOOP_36_2_VITIS_LOOP_37_3_fu_373_feature_current_q_address0),
    .feature_current_q_ce0(grp_run_hybrid_lif_head_Pipeline_VITIS_LOOP_36_2_VITIS_LOOP_37_3_fu_373_feature_current_q_ce0),
    .feature_current_q_q0(feature_current_q_q0),
    .membrane_address0(grp_run_hybrid_lif_head_Pipeline_VITIS_LOOP_36_2_VITIS_LOOP_37_3_fu_373_membrane_address0),
    .membrane_ce0(grp_run_hybrid_lif_head_Pipeline_VITIS_LOOP_36_2_VITIS_LOOP_37_3_fu_373_membrane_ce0),
    .membrane_we0(grp_run_hybrid_lif_head_Pipeline_VITIS_LOOP_36_2_VITIS_LOOP_37_3_fu_373_membrane_we0),
    .membrane_d0(grp_run_hybrid_lif_head_Pipeline_VITIS_LOOP_36_2_VITIS_LOOP_37_3_fu_373_membrane_d0),
    .membrane_address1(grp_run_hybrid_lif_head_Pipeline_VITIS_LOOP_36_2_VITIS_LOOP_37_3_fu_373_membrane_address1),
    .membrane_ce1(grp_run_hybrid_lif_head_Pipeline_VITIS_LOOP_36_2_VITIS_LOOP_37_3_fu_373_membrane_ce1),
    .membrane_q1(membrane_q1),
    .spike_count_q_address0(grp_run_hybrid_lif_head_Pipeline_VITIS_LOOP_36_2_VITIS_LOOP_37_3_fu_373_spike_count_q_address0),
    .spike_count_q_ce0(grp_run_hybrid_lif_head_Pipeline_VITIS_LOOP_36_2_VITIS_LOOP_37_3_fu_373_spike_count_q_ce0),
    .spike_count_q_we0(grp_run_hybrid_lif_head_Pipeline_VITIS_LOOP_36_2_VITIS_LOOP_37_3_fu_373_spike_count_q_we0),
    .spike_count_q_d0(grp_run_hybrid_lif_head_Pipeline_VITIS_LOOP_36_2_VITIS_LOOP_37_3_fu_373_spike_count_q_d0),
    .spike_count_q_address1(grp_run_hybrid_lif_head_Pipeline_VITIS_LOOP_36_2_VITIS_LOOP_37_3_fu_373_spike_count_q_address1),
    .spike_count_q_ce1(grp_run_hybrid_lif_head_Pipeline_VITIS_LOOP_36_2_VITIS_LOOP_37_3_fu_373_spike_count_q_ce1),
    .spike_count_q_q1(spike_count_q_q1)
);

hybrid_lif_head_q12_6_run_hybrid_lif_head_Pipeline_VITIS_LOOP_59_4 grp_run_hybrid_lif_head_Pipeline_VITIS_LOOP_59_4_fu_382(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(grp_run_hybrid_lif_head_Pipeline_VITIS_LOOP_59_4_fu_382_ap_start),
    .ap_done(grp_run_hybrid_lif_head_Pipeline_VITIS_LOOP_59_4_fu_382_ap_done),
    .ap_idle(grp_run_hybrid_lif_head_Pipeline_VITIS_LOOP_59_4_fu_382_ap_idle),
    .ap_ready(grp_run_hybrid_lif_head_Pipeline_VITIS_LOOP_59_4_fu_382_ap_ready),
    .spike_count_q_address0(grp_run_hybrid_lif_head_Pipeline_VITIS_LOOP_59_4_fu_382_spike_count_q_address0),
    .spike_count_q_ce0(grp_run_hybrid_lif_head_Pipeline_VITIS_LOOP_59_4_fu_382_spike_count_q_ce0),
    .spike_count_q_q0(spike_count_q_q0),
    .rate_q_address0(grp_run_hybrid_lif_head_Pipeline_VITIS_LOOP_59_4_fu_382_rate_q_address0),
    .rate_q_ce0(grp_run_hybrid_lif_head_Pipeline_VITIS_LOOP_59_4_fu_382_rate_q_ce0),
    .rate_q_we0(grp_run_hybrid_lif_head_Pipeline_VITIS_LOOP_59_4_fu_382_rate_q_we0),
    .rate_q_d0(grp_run_hybrid_lif_head_Pipeline_VITIS_LOOP_59_4_fu_382_rate_q_d0)
);

hybrid_lif_head_q12_6_run_hybrid_lif_head_Pipeline_VITIS_LOOP_66_5 grp_run_hybrid_lif_head_Pipeline_VITIS_LOOP_66_5_fu_389(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(grp_run_hybrid_lif_head_Pipeline_VITIS_LOOP_66_5_fu_389_ap_start),
    .ap_done(grp_run_hybrid_lif_head_Pipeline_VITIS_LOOP_66_5_fu_389_ap_done),
    .ap_idle(grp_run_hybrid_lif_head_Pipeline_VITIS_LOOP_66_5_fu_389_ap_idle),
    .ap_ready(grp_run_hybrid_lif_head_Pipeline_VITIS_LOOP_66_5_fu_389_ap_ready),
    .weight_q_address0(grp_run_hybrid_lif_head_Pipeline_VITIS_LOOP_66_5_fu_389_weight_q_address0),
    .weight_q_ce0(grp_run_hybrid_lif_head_Pipeline_VITIS_LOOP_66_5_fu_389_weight_q_ce0),
    .weight_q_q0(weight_q_q0),
    .weight_q_address1(grp_run_hybrid_lif_head_Pipeline_VITIS_LOOP_66_5_fu_389_weight_q_address1),
    .weight_q_ce1(grp_run_hybrid_lif_head_Pipeline_VITIS_LOOP_66_5_fu_389_weight_q_ce1),
    .weight_q_q1(weight_q_q1),
    .conv_i104_i(rate_q_load_reg_443),
    .conv_i104_1_i(rate_q_load_1_reg_448),
    .conv_i104_2_i(rate_q_load_2_reg_463),
    .conv_i104_3_i(rate_q_load_3_reg_468),
    .conv_i104_4_i(rate_q_load_4_reg_483),
    .conv_i104_5_i(rate_q_load_5_reg_488),
    .conv_i104_6_i(rate_q_load_6_reg_503),
    .conv_i104_7_i(rate_q_load_7_reg_508),
    .conv_i104_8_i(rate_q_load_8_reg_523),
    .conv_i104_9_i(rate_q_load_9_reg_528),
    .conv_i104_10_i(rate_q_load_10_reg_543),
    .conv_i104_11_i(rate_q_load_11_reg_548),
    .conv_i104_12_i(rate_q_load_12_reg_563),
    .conv_i104_13_i(rate_q_load_13_reg_568),
    .conv_i104_14_i(rate_q_load_14_reg_583),
    .conv_i104_15_i(rate_q_load_15_reg_588),
    .conv_i104_16_i(rate_q_load_16_reg_603),
    .conv_i104_17_i(rate_q_load_17_reg_608),
    .conv_i104_18_i(rate_q_load_18_reg_623),
    .conv_i104_19_i(rate_q_load_19_reg_628),
    .conv_i104_20_i(rate_q_load_20_reg_643),
    .conv_i104_21_i(rate_q_load_21_reg_648),
    .conv_i104_22_i(rate_q_load_22_reg_663),
    .conv_i104_23_i(rate_q_load_23_reg_668),
    .conv_i104_24_i(rate_q_load_24_reg_683),
    .conv_i104_25_i(rate_q_load_25_reg_688),
    .conv_i104_26_i(rate_q_load_26_reg_703),
    .conv_i104_27_i(rate_q_load_27_reg_708),
    .conv_i104_28_i(rate_q_load_28_reg_723),
    .conv_i104_29_i(rate_q_load_29_reg_728),
    .conv_i104_30_i(rate_q_load_30_reg_743),
    .conv_i104_31_i(rate_q_load_31_reg_748),
    .bias_q_address0(grp_run_hybrid_lif_head_Pipeline_VITIS_LOOP_66_5_fu_389_bias_q_address0),
    .bias_q_ce0(grp_run_hybrid_lif_head_Pipeline_VITIS_LOOP_66_5_fu_389_bias_q_ce0),
    .bias_q_q0(bias_q_q0),
    .logits_q_address0(grp_run_hybrid_lif_head_Pipeline_VITIS_LOOP_66_5_fu_389_logits_q_address0),
    .logits_q_ce0(grp_run_hybrid_lif_head_Pipeline_VITIS_LOOP_66_5_fu_389_logits_q_ce0),
    .logits_q_we0(grp_run_hybrid_lif_head_Pipeline_VITIS_LOOP_66_5_fu_389_logits_q_we0),
    .logits_q_d0(grp_run_hybrid_lif_head_Pipeline_VITIS_LOOP_66_5_fu_389_logits_q_d0)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_state1;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        grp_run_hybrid_lif_head_Pipeline_VITIS_LOOP_31_1_fu_365_ap_start_reg <= 1'b0;
    end else begin
        if (((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
            grp_run_hybrid_lif_head_Pipeline_VITIS_LOOP_31_1_fu_365_ap_start_reg <= 1'b1;
        end else if ((grp_run_hybrid_lif_head_Pipeline_VITIS_LOOP_31_1_fu_365_ap_ready == 1'b1)) begin
            grp_run_hybrid_lif_head_Pipeline_VITIS_LOOP_31_1_fu_365_ap_start_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        grp_run_hybrid_lif_head_Pipeline_VITIS_LOOP_36_2_VITIS_LOOP_37_3_fu_373_ap_start_reg <= 1'b0;
    end else begin
        if ((1'b1 == ap_CS_fsm_state3)) begin
            grp_run_hybrid_lif_head_Pipeline_VITIS_LOOP_36_2_VITIS_LOOP_37_3_fu_373_ap_start_reg <= 1'b1;
        end else if ((grp_run_hybrid_lif_head_Pipeline_VITIS_LOOP_36_2_VITIS_LOOP_37_3_fu_373_ap_ready == 1'b1)) begin
            grp_run_hybrid_lif_head_Pipeline_VITIS_LOOP_36_2_VITIS_LOOP_37_3_fu_373_ap_start_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        grp_run_hybrid_lif_head_Pipeline_VITIS_LOOP_59_4_fu_382_ap_start_reg <= 1'b0;
    end else begin
        if ((1'b1 == ap_CS_fsm_state5)) begin
            grp_run_hybrid_lif_head_Pipeline_VITIS_LOOP_59_4_fu_382_ap_start_reg <= 1'b1;
        end else if ((grp_run_hybrid_lif_head_Pipeline_VITIS_LOOP_59_4_fu_382_ap_ready == 1'b1)) begin
            grp_run_hybrid_lif_head_Pipeline_VITIS_LOOP_59_4_fu_382_ap_start_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        grp_run_hybrid_lif_head_Pipeline_VITIS_LOOP_66_5_fu_389_ap_start_reg <= 1'b0;
    end else begin
        if ((1'b1 == ap_CS_fsm_state23)) begin
            grp_run_hybrid_lif_head_Pipeline_VITIS_LOOP_66_5_fu_389_ap_start_reg <= 1'b1;
        end else if ((grp_run_hybrid_lif_head_Pipeline_VITIS_LOOP_66_5_fu_389_ap_ready == 1'b1)) begin
            grp_run_hybrid_lif_head_Pipeline_VITIS_LOOP_66_5_fu_389_ap_start_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state13)) begin
        rate_q_load_10_reg_543 <= rate_q_q1;
        rate_q_load_11_reg_548 <= rate_q_q0;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state14)) begin
        rate_q_load_12_reg_563 <= rate_q_q1;
        rate_q_load_13_reg_568 <= rate_q_q0;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state15)) begin
        rate_q_load_14_reg_583 <= rate_q_q1;
        rate_q_load_15_reg_588 <= rate_q_q0;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state16)) begin
        rate_q_load_16_reg_603 <= rate_q_q1;
        rate_q_load_17_reg_608 <= rate_q_q0;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state17)) begin
        rate_q_load_18_reg_623 <= rate_q_q1;
        rate_q_load_19_reg_628 <= rate_q_q0;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state8)) begin
        rate_q_load_1_reg_448 <= rate_q_q0;
        rate_q_load_reg_443 <= rate_q_q1;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state18)) begin
        rate_q_load_20_reg_643 <= rate_q_q1;
        rate_q_load_21_reg_648 <= rate_q_q0;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state19)) begin
        rate_q_load_22_reg_663 <= rate_q_q1;
        rate_q_load_23_reg_668 <= rate_q_q0;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state20)) begin
        rate_q_load_24_reg_683 <= rate_q_q1;
        rate_q_load_25_reg_688 <= rate_q_q0;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state21)) begin
        rate_q_load_26_reg_703 <= rate_q_q1;
        rate_q_load_27_reg_708 <= rate_q_q0;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state22)) begin
        rate_q_load_28_reg_723 <= rate_q_q1;
        rate_q_load_29_reg_728 <= rate_q_q0;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state9)) begin
        rate_q_load_2_reg_463 <= rate_q_q1;
        rate_q_load_3_reg_468 <= rate_q_q0;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state23)) begin
        rate_q_load_30_reg_743 <= rate_q_q1;
        rate_q_load_31_reg_748 <= rate_q_q0;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state10)) begin
        rate_q_load_4_reg_483 <= rate_q_q1;
        rate_q_load_5_reg_488 <= rate_q_q0;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state11)) begin
        rate_q_load_6_reg_503 <= rate_q_q1;
        rate_q_load_7_reg_508 <= rate_q_q0;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state12)) begin
        rate_q_load_8_reg_523 <= rate_q_q1;
        rate_q_load_9_reg_528 <= rate_q_q0;
    end
end

assign ap_ST_fsm_state10_blk = 1'b0;

assign ap_ST_fsm_state11_blk = 1'b0;

assign ap_ST_fsm_state12_blk = 1'b0;

assign ap_ST_fsm_state13_blk = 1'b0;

assign ap_ST_fsm_state14_blk = 1'b0;

assign ap_ST_fsm_state15_blk = 1'b0;

assign ap_ST_fsm_state16_blk = 1'b0;

assign ap_ST_fsm_state17_blk = 1'b0;

assign ap_ST_fsm_state18_blk = 1'b0;

assign ap_ST_fsm_state19_blk = 1'b0;

always @ (*) begin
    if ((ap_start == 1'b0)) begin
        ap_ST_fsm_state1_blk = 1'b1;
    end else begin
        ap_ST_fsm_state1_blk = 1'b0;
    end
end

assign ap_ST_fsm_state20_blk = 1'b0;

assign ap_ST_fsm_state21_blk = 1'b0;

assign ap_ST_fsm_state22_blk = 1'b0;

assign ap_ST_fsm_state23_blk = 1'b0;

always @ (*) begin
    if ((grp_run_hybrid_lif_head_Pipeline_VITIS_LOOP_66_5_fu_389_ap_done == 1'b0)) begin
        ap_ST_fsm_state24_blk = 1'b1;
    end else begin
        ap_ST_fsm_state24_blk = 1'b0;
    end
end

always @ (*) begin
    if ((grp_run_hybrid_lif_head_Pipeline_VITIS_LOOP_31_1_fu_365_ap_done == 1'b0)) begin
        ap_ST_fsm_state2_blk = 1'b1;
    end else begin
        ap_ST_fsm_state2_blk = 1'b0;
    end
end

assign ap_ST_fsm_state3_blk = 1'b0;

always @ (*) begin
    if ((grp_run_hybrid_lif_head_Pipeline_VITIS_LOOP_36_2_VITIS_LOOP_37_3_fu_373_ap_done == 1'b0)) begin
        ap_ST_fsm_state4_blk = 1'b1;
    end else begin
        ap_ST_fsm_state4_blk = 1'b0;
    end
end

assign ap_ST_fsm_state5_blk = 1'b0;

always @ (*) begin
    if ((grp_run_hybrid_lif_head_Pipeline_VITIS_LOOP_59_4_fu_382_ap_done == 1'b0)) begin
        ap_ST_fsm_state6_blk = 1'b1;
    end else begin
        ap_ST_fsm_state6_blk = 1'b0;
    end
end

assign ap_ST_fsm_state7_blk = 1'b0;

assign ap_ST_fsm_state8_blk = 1'b0;

assign ap_ST_fsm_state9_blk = 1'b0;

always @ (*) begin
    if ((((grp_run_hybrid_lif_head_Pipeline_VITIS_LOOP_66_5_fu_389_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state24)) | ((ap_start == 1'b0) & (1'b1 == ap_CS_fsm_state1)))) begin
        ap_done = 1'b1;
    end else begin
        ap_done = 1'b0;
    end
end

always @ (*) begin
    if (((ap_start == 1'b0) & (1'b1 == ap_CS_fsm_state1))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((grp_run_hybrid_lif_head_Pipeline_VITIS_LOOP_66_5_fu_389_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state24))) begin
        ap_ready = 1'b1;
    end else begin
        ap_ready = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state4)) begin
        membrane_address0 = grp_run_hybrid_lif_head_Pipeline_VITIS_LOOP_36_2_VITIS_LOOP_37_3_fu_373_membrane_address0;
    end else if ((1'b1 == ap_CS_fsm_state2)) begin
        membrane_address0 = grp_run_hybrid_lif_head_Pipeline_VITIS_LOOP_31_1_fu_365_membrane_address0;
    end else begin
        membrane_address0 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state4)) begin
        membrane_ce0 = grp_run_hybrid_lif_head_Pipeline_VITIS_LOOP_36_2_VITIS_LOOP_37_3_fu_373_membrane_ce0;
    end else if ((1'b1 == ap_CS_fsm_state2)) begin
        membrane_ce0 = grp_run_hybrid_lif_head_Pipeline_VITIS_LOOP_31_1_fu_365_membrane_ce0;
    end else begin
        membrane_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state4)) begin
        membrane_ce1 = grp_run_hybrid_lif_head_Pipeline_VITIS_LOOP_36_2_VITIS_LOOP_37_3_fu_373_membrane_ce1;
    end else begin
        membrane_ce1 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state4)) begin
        membrane_d0 = grp_run_hybrid_lif_head_Pipeline_VITIS_LOOP_36_2_VITIS_LOOP_37_3_fu_373_membrane_d0;
    end else if ((1'b1 == ap_CS_fsm_state2)) begin
        membrane_d0 = grp_run_hybrid_lif_head_Pipeline_VITIS_LOOP_31_1_fu_365_membrane_d0;
    end else begin
        membrane_d0 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state4)) begin
        membrane_we0 = grp_run_hybrid_lif_head_Pipeline_VITIS_LOOP_36_2_VITIS_LOOP_37_3_fu_373_membrane_we0;
    end else if ((1'b1 == ap_CS_fsm_state2)) begin
        membrane_we0 = grp_run_hybrid_lif_head_Pipeline_VITIS_LOOP_31_1_fu_365_membrane_we0;
    end else begin
        membrane_we0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state6)) begin
        rate_q_address0 = grp_run_hybrid_lif_head_Pipeline_VITIS_LOOP_59_4_fu_382_rate_q_address0;
    end else begin
        rate_q_address0 = rate_q_address0_local;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state22)) begin
        rate_q_address0_local = 64'd31;
    end else if ((1'b1 == ap_CS_fsm_state21)) begin
        rate_q_address0_local = 64'd29;
    end else if ((1'b1 == ap_CS_fsm_state20)) begin
        rate_q_address0_local = 64'd27;
    end else if ((1'b1 == ap_CS_fsm_state19)) begin
        rate_q_address0_local = 64'd25;
    end else if ((1'b1 == ap_CS_fsm_state18)) begin
        rate_q_address0_local = 64'd23;
    end else if ((1'b1 == ap_CS_fsm_state17)) begin
        rate_q_address0_local = 64'd21;
    end else if ((1'b1 == ap_CS_fsm_state16)) begin
        rate_q_address0_local = 64'd19;
    end else if ((1'b1 == ap_CS_fsm_state15)) begin
        rate_q_address0_local = 64'd17;
    end else if ((1'b1 == ap_CS_fsm_state14)) begin
        rate_q_address0_local = 64'd15;
    end else if ((1'b1 == ap_CS_fsm_state13)) begin
        rate_q_address0_local = 64'd13;
    end else if ((1'b1 == ap_CS_fsm_state12)) begin
        rate_q_address0_local = 64'd11;
    end else if ((1'b1 == ap_CS_fsm_state11)) begin
        rate_q_address0_local = 64'd9;
    end else if ((1'b1 == ap_CS_fsm_state10)) begin
        rate_q_address0_local = 64'd7;
    end else if ((1'b1 == ap_CS_fsm_state9)) begin
        rate_q_address0_local = 64'd5;
    end else if ((1'b1 == ap_CS_fsm_state8)) begin
        rate_q_address0_local = 64'd3;
    end else if ((1'b1 == ap_CS_fsm_state7)) begin
        rate_q_address0_local = 64'd1;
    end else begin
        rate_q_address0_local = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state22)) begin
        rate_q_address1_local = 64'd30;
    end else if ((1'b1 == ap_CS_fsm_state21)) begin
        rate_q_address1_local = 64'd28;
    end else if ((1'b1 == ap_CS_fsm_state20)) begin
        rate_q_address1_local = 64'd26;
    end else if ((1'b1 == ap_CS_fsm_state19)) begin
        rate_q_address1_local = 64'd24;
    end else if ((1'b1 == ap_CS_fsm_state18)) begin
        rate_q_address1_local = 64'd22;
    end else if ((1'b1 == ap_CS_fsm_state17)) begin
        rate_q_address1_local = 64'd20;
    end else if ((1'b1 == ap_CS_fsm_state16)) begin
        rate_q_address1_local = 64'd18;
    end else if ((1'b1 == ap_CS_fsm_state15)) begin
        rate_q_address1_local = 64'd16;
    end else if ((1'b1 == ap_CS_fsm_state14)) begin
        rate_q_address1_local = 64'd14;
    end else if ((1'b1 == ap_CS_fsm_state13)) begin
        rate_q_address1_local = 64'd12;
    end else if ((1'b1 == ap_CS_fsm_state12)) begin
        rate_q_address1_local = 64'd10;
    end else if ((1'b1 == ap_CS_fsm_state11)) begin
        rate_q_address1_local = 64'd8;
    end else if ((1'b1 == ap_CS_fsm_state10)) begin
        rate_q_address1_local = 64'd6;
    end else if ((1'b1 == ap_CS_fsm_state9)) begin
        rate_q_address1_local = 64'd4;
    end else if ((1'b1 == ap_CS_fsm_state8)) begin
        rate_q_address1_local = 64'd2;
    end else if ((1'b1 == ap_CS_fsm_state7)) begin
        rate_q_address1_local = 64'd0;
    end else begin
        rate_q_address1_local = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state6)) begin
        rate_q_ce0 = grp_run_hybrid_lif_head_Pipeline_VITIS_LOOP_59_4_fu_382_rate_q_ce0;
    end else begin
        rate_q_ce0 = rate_q_ce0_local;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state8) | (1'b1 == ap_CS_fsm_state7) | (1'b1 == ap_CS_fsm_state22) | (1'b1 == ap_CS_fsm_state21) | (1'b1 == ap_CS_fsm_state20) | (1'b1 == ap_CS_fsm_state19) | (1'b1 == ap_CS_fsm_state18) | (1'b1 == ap_CS_fsm_state17) | (1'b1 == ap_CS_fsm_state16) | (1'b1 == ap_CS_fsm_state15) | (1'b1 == ap_CS_fsm_state14) | (1'b1 == ap_CS_fsm_state13) | (1'b1 == ap_CS_fsm_state12) | (1'b1 == ap_CS_fsm_state11) | (1'b1 == ap_CS_fsm_state10) | (1'b1 == ap_CS_fsm_state9))) begin
        rate_q_ce0_local = 1'b1;
    end else begin
        rate_q_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state8) | (1'b1 == ap_CS_fsm_state7) | (1'b1 == ap_CS_fsm_state22) | (1'b1 == ap_CS_fsm_state21) | (1'b1 == ap_CS_fsm_state20) | (1'b1 == ap_CS_fsm_state19) | (1'b1 == ap_CS_fsm_state18) | (1'b1 == ap_CS_fsm_state17) | (1'b1 == ap_CS_fsm_state16) | (1'b1 == ap_CS_fsm_state15) | (1'b1 == ap_CS_fsm_state14) | (1'b1 == ap_CS_fsm_state13) | (1'b1 == ap_CS_fsm_state12) | (1'b1 == ap_CS_fsm_state11) | (1'b1 == ap_CS_fsm_state10) | (1'b1 == ap_CS_fsm_state9))) begin
        rate_q_ce1_local = 1'b1;
    end else begin
        rate_q_ce1_local = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state6)) begin
        rate_q_we0 = grp_run_hybrid_lif_head_Pipeline_VITIS_LOOP_59_4_fu_382_rate_q_we0;
    end else begin
        rate_q_we0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state6)) begin
        spike_count_q_address0 = grp_run_hybrid_lif_head_Pipeline_VITIS_LOOP_59_4_fu_382_spike_count_q_address0;
    end else if ((1'b1 == ap_CS_fsm_state4)) begin
        spike_count_q_address0 = grp_run_hybrid_lif_head_Pipeline_VITIS_LOOP_36_2_VITIS_LOOP_37_3_fu_373_spike_count_q_address0;
    end else if ((1'b1 == ap_CS_fsm_state2)) begin
        spike_count_q_address0 = grp_run_hybrid_lif_head_Pipeline_VITIS_LOOP_31_1_fu_365_spike_count_q_address0;
    end else begin
        spike_count_q_address0 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state6)) begin
        spike_count_q_ce0 = grp_run_hybrid_lif_head_Pipeline_VITIS_LOOP_59_4_fu_382_spike_count_q_ce0;
    end else if ((1'b1 == ap_CS_fsm_state4)) begin
        spike_count_q_ce0 = grp_run_hybrid_lif_head_Pipeline_VITIS_LOOP_36_2_VITIS_LOOP_37_3_fu_373_spike_count_q_ce0;
    end else if ((1'b1 == ap_CS_fsm_state2)) begin
        spike_count_q_ce0 = grp_run_hybrid_lif_head_Pipeline_VITIS_LOOP_31_1_fu_365_spike_count_q_ce0;
    end else begin
        spike_count_q_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state4)) begin
        spike_count_q_ce1 = grp_run_hybrid_lif_head_Pipeline_VITIS_LOOP_36_2_VITIS_LOOP_37_3_fu_373_spike_count_q_ce1;
    end else begin
        spike_count_q_ce1 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state4)) begin
        spike_count_q_d0 = grp_run_hybrid_lif_head_Pipeline_VITIS_LOOP_36_2_VITIS_LOOP_37_3_fu_373_spike_count_q_d0;
    end else if ((1'b1 == ap_CS_fsm_state2)) begin
        spike_count_q_d0 = grp_run_hybrid_lif_head_Pipeline_VITIS_LOOP_31_1_fu_365_spike_count_q_d0;
    end else begin
        spike_count_q_d0 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state4)) begin
        spike_count_q_we0 = grp_run_hybrid_lif_head_Pipeline_VITIS_LOOP_36_2_VITIS_LOOP_37_3_fu_373_spike_count_q_we0;
    end else if ((1'b1 == ap_CS_fsm_state2)) begin
        spike_count_q_we0 = grp_run_hybrid_lif_head_Pipeline_VITIS_LOOP_31_1_fu_365_spike_count_q_we0;
    end else begin
        spike_count_q_we0 = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_state1 : begin
            if (((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
                ap_NS_fsm = ap_ST_fsm_state2;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end
        end
        ap_ST_fsm_state2 : begin
            if (((grp_run_hybrid_lif_head_Pipeline_VITIS_LOOP_31_1_fu_365_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state2))) begin
                ap_NS_fsm = ap_ST_fsm_state3;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state2;
            end
        end
        ap_ST_fsm_state3 : begin
            ap_NS_fsm = ap_ST_fsm_state4;
        end
        ap_ST_fsm_state4 : begin
            if (((grp_run_hybrid_lif_head_Pipeline_VITIS_LOOP_36_2_VITIS_LOOP_37_3_fu_373_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state4))) begin
                ap_NS_fsm = ap_ST_fsm_state5;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state4;
            end
        end
        ap_ST_fsm_state5 : begin
            ap_NS_fsm = ap_ST_fsm_state6;
        end
        ap_ST_fsm_state6 : begin
            if (((grp_run_hybrid_lif_head_Pipeline_VITIS_LOOP_59_4_fu_382_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state6))) begin
                ap_NS_fsm = ap_ST_fsm_state7;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state6;
            end
        end
        ap_ST_fsm_state7 : begin
            ap_NS_fsm = ap_ST_fsm_state8;
        end
        ap_ST_fsm_state8 : begin
            ap_NS_fsm = ap_ST_fsm_state9;
        end
        ap_ST_fsm_state9 : begin
            ap_NS_fsm = ap_ST_fsm_state10;
        end
        ap_ST_fsm_state10 : begin
            ap_NS_fsm = ap_ST_fsm_state11;
        end
        ap_ST_fsm_state11 : begin
            ap_NS_fsm = ap_ST_fsm_state12;
        end
        ap_ST_fsm_state12 : begin
            ap_NS_fsm = ap_ST_fsm_state13;
        end
        ap_ST_fsm_state13 : begin
            ap_NS_fsm = ap_ST_fsm_state14;
        end
        ap_ST_fsm_state14 : begin
            ap_NS_fsm = ap_ST_fsm_state15;
        end
        ap_ST_fsm_state15 : begin
            ap_NS_fsm = ap_ST_fsm_state16;
        end
        ap_ST_fsm_state16 : begin
            ap_NS_fsm = ap_ST_fsm_state17;
        end
        ap_ST_fsm_state17 : begin
            ap_NS_fsm = ap_ST_fsm_state18;
        end
        ap_ST_fsm_state18 : begin
            ap_NS_fsm = ap_ST_fsm_state19;
        end
        ap_ST_fsm_state19 : begin
            ap_NS_fsm = ap_ST_fsm_state20;
        end
        ap_ST_fsm_state20 : begin
            ap_NS_fsm = ap_ST_fsm_state21;
        end
        ap_ST_fsm_state21 : begin
            ap_NS_fsm = ap_ST_fsm_state22;
        end
        ap_ST_fsm_state22 : begin
            ap_NS_fsm = ap_ST_fsm_state23;
        end
        ap_ST_fsm_state23 : begin
            ap_NS_fsm = ap_ST_fsm_state24;
        end
        ap_ST_fsm_state24 : begin
            if (((grp_run_hybrid_lif_head_Pipeline_VITIS_LOOP_66_5_fu_389_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state24))) begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state24;
            end
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign ap_CS_fsm_state1 = ap_CS_fsm[32'd0];

assign ap_CS_fsm_state10 = ap_CS_fsm[32'd9];

assign ap_CS_fsm_state11 = ap_CS_fsm[32'd10];

assign ap_CS_fsm_state12 = ap_CS_fsm[32'd11];

assign ap_CS_fsm_state13 = ap_CS_fsm[32'd12];

assign ap_CS_fsm_state14 = ap_CS_fsm[32'd13];

assign ap_CS_fsm_state15 = ap_CS_fsm[32'd14];

assign ap_CS_fsm_state16 = ap_CS_fsm[32'd15];

assign ap_CS_fsm_state17 = ap_CS_fsm[32'd16];

assign ap_CS_fsm_state18 = ap_CS_fsm[32'd17];

assign ap_CS_fsm_state19 = ap_CS_fsm[32'd18];

assign ap_CS_fsm_state2 = ap_CS_fsm[32'd1];

assign ap_CS_fsm_state20 = ap_CS_fsm[32'd19];

assign ap_CS_fsm_state21 = ap_CS_fsm[32'd20];

assign ap_CS_fsm_state22 = ap_CS_fsm[32'd21];

assign ap_CS_fsm_state23 = ap_CS_fsm[32'd22];

assign ap_CS_fsm_state24 = ap_CS_fsm[32'd23];

assign ap_CS_fsm_state3 = ap_CS_fsm[32'd2];

assign ap_CS_fsm_state4 = ap_CS_fsm[32'd3];

assign ap_CS_fsm_state5 = ap_CS_fsm[32'd4];

assign ap_CS_fsm_state6 = ap_CS_fsm[32'd5];

assign ap_CS_fsm_state7 = ap_CS_fsm[32'd6];

assign ap_CS_fsm_state8 = ap_CS_fsm[32'd7];

assign ap_CS_fsm_state9 = ap_CS_fsm[32'd8];

assign bias_q_address0 = grp_run_hybrid_lif_head_Pipeline_VITIS_LOOP_66_5_fu_389_bias_q_address0;

assign bias_q_ce0 = grp_run_hybrid_lif_head_Pipeline_VITIS_LOOP_66_5_fu_389_bias_q_ce0;

assign feature_current_q_address0 = grp_run_hybrid_lif_head_Pipeline_VITIS_LOOP_36_2_VITIS_LOOP_37_3_fu_373_feature_current_q_address0;

assign feature_current_q_ce0 = grp_run_hybrid_lif_head_Pipeline_VITIS_LOOP_36_2_VITIS_LOOP_37_3_fu_373_feature_current_q_ce0;

assign grp_run_hybrid_lif_head_Pipeline_VITIS_LOOP_31_1_fu_365_ap_start = grp_run_hybrid_lif_head_Pipeline_VITIS_LOOP_31_1_fu_365_ap_start_reg;

assign grp_run_hybrid_lif_head_Pipeline_VITIS_LOOP_36_2_VITIS_LOOP_37_3_fu_373_ap_start = grp_run_hybrid_lif_head_Pipeline_VITIS_LOOP_36_2_VITIS_LOOP_37_3_fu_373_ap_start_reg;

assign grp_run_hybrid_lif_head_Pipeline_VITIS_LOOP_59_4_fu_382_ap_start = grp_run_hybrid_lif_head_Pipeline_VITIS_LOOP_59_4_fu_382_ap_start_reg;

assign grp_run_hybrid_lif_head_Pipeline_VITIS_LOOP_66_5_fu_389_ap_start = grp_run_hybrid_lif_head_Pipeline_VITIS_LOOP_66_5_fu_389_ap_start_reg;

assign logits_q_address0 = grp_run_hybrid_lif_head_Pipeline_VITIS_LOOP_66_5_fu_389_logits_q_address0;

assign logits_q_ce0 = grp_run_hybrid_lif_head_Pipeline_VITIS_LOOP_66_5_fu_389_logits_q_ce0;

assign logits_q_d0 = grp_run_hybrid_lif_head_Pipeline_VITIS_LOOP_66_5_fu_389_logits_q_d0;

assign logits_q_we0 = grp_run_hybrid_lif_head_Pipeline_VITIS_LOOP_66_5_fu_389_logits_q_we0;

assign spike_count_q_address1 = grp_run_hybrid_lif_head_Pipeline_VITIS_LOOP_36_2_VITIS_LOOP_37_3_fu_373_spike_count_q_address1;

assign weight_q_address0 = grp_run_hybrid_lif_head_Pipeline_VITIS_LOOP_66_5_fu_389_weight_q_address0;

assign weight_q_address1 = grp_run_hybrid_lif_head_Pipeline_VITIS_LOOP_66_5_fu_389_weight_q_address1;

assign weight_q_ce0 = grp_run_hybrid_lif_head_Pipeline_VITIS_LOOP_66_5_fu_389_weight_q_ce0;

assign weight_q_ce1 = grp_run_hybrid_lif_head_Pipeline_VITIS_LOOP_66_5_fu_389_weight_q_ce1;

endmodule //hybrid_lif_head_q12_6_run_hybrid_lif_head
