// ==============================================================
// Generated by Vitis HLS v2025.1
// Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// Copyright 2022-2025 Advanced Micro Devices, Inc. All Rights Reserved.
// ==============================================================

`timescale 1 ns / 1 ps 

module hybrid_lif_head_q12_6_run_hybrid_lif_head_Pipeline_VITIS_LOOP_31_1 (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_idle,
        ap_ready,
        membrane_address0,
        membrane_ce0,
        membrane_we0,
        membrane_d0,
        spike_count_q_address0,
        spike_count_q_ce0,
        spike_count_q_we0,
        spike_count_q_d0
);

parameter    ap_ST_fsm_state1 = 1'd1;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
output   ap_idle;
output   ap_ready;
output  [4:0] membrane_address0;
output   membrane_ce0;
output   membrane_we0;
output  [15:0] membrane_d0;
output  [4:0] spike_count_q_address0;
output   spike_count_q_ce0;
output   spike_count_q_we0;
output  [5:0] spike_count_q_d0;

reg ap_idle;

(* fsm_encoding = "none" *) reg   [0:0] ap_CS_fsm;
wire    ap_CS_fsm_state1;
reg    ap_block_state1_pp0_stage0_iter0;
wire   [0:0] icmp_ln31_fu_76_p2;
reg    ap_condition_exit_pp0_iter0_stage0;
wire    ap_loop_exit_ready;
reg    ap_ready_int;
wire   [63:0] zext_ln31_fu_88_p1;
reg   [5:0] channel_fu_36;
wire   [5:0] add_ln31_fu_82_p2;
wire    ap_loop_init;
reg   [5:0] ap_sig_allocacmp_channel_2;
reg    membrane_we0_local;
reg    membrane_ce0_local;
reg    spike_count_q_we0_local;
reg    spike_count_q_ce0_local;
reg    ap_done_reg;
wire    ap_continue_int;
reg    ap_done_int;
reg   [0:0] ap_NS_fsm;
reg    ap_ST_fsm_state1_blk;
wire    ap_start_int;
wire    ap_ready_sig;
wire    ap_done_sig;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_CS_fsm = 1'd1;
#0 channel_fu_36 = 6'd0;
#0 ap_done_reg = 1'b0;
end

hybrid_lif_head_q12_6_flow_control_loop_pipe_sequential_init flow_control_loop_pipe_sequential_init_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(ap_start),
    .ap_ready(ap_ready_sig),
    .ap_done(ap_done_sig),
    .ap_start_int(ap_start_int),
    .ap_loop_init(ap_loop_init),
    .ap_ready_int(ap_ready_int),
    .ap_loop_exit_ready(ap_condition_exit_pp0_iter0_stage0),
    .ap_loop_exit_done(ap_done_int),
    .ap_continue_int(ap_continue_int),
    .ap_done_int(ap_done_int)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_state1;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_done_reg <= 1'b0;
    end else begin
        if ((ap_continue_int == 1'b1)) begin
            ap_done_reg <= 1'b0;
        end else if (((ap_loop_exit_ready == 1'b1) & (1'b0 == ap_block_state1_pp0_stage0_iter0) & (1'b1 == ap_CS_fsm_state1))) begin
            ap_done_reg <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_state1_pp0_stage0_iter0) & (1'b1 == ap_CS_fsm_state1))) begin
        if ((icmp_ln31_fu_76_p2 == 1'd0)) begin
            channel_fu_36 <= add_ln31_fu_82_p2;
        end else if ((ap_loop_init == 1'b1)) begin
            channel_fu_36 <= 6'd0;
        end
    end
end

always @ (*) begin
    if ((1'b1 == ap_block_state1_pp0_stage0_iter0)) begin
        ap_ST_fsm_state1_blk = 1'b1;
    end else begin
        ap_ST_fsm_state1_blk = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln31_fu_76_p2 == 1'd1) & (1'b0 == ap_block_state1_pp0_stage0_iter0) & (1'b1 == ap_CS_fsm_state1))) begin
        ap_condition_exit_pp0_iter0_stage0 = 1'b1;
    end else begin
        ap_condition_exit_pp0_iter0_stage0 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_loop_exit_ready == 1'b1) & (1'b0 == ap_block_state1_pp0_stage0_iter0) & (1'b1 == ap_CS_fsm_state1))) begin
        ap_done_int = 1'b1;
    end else begin
        ap_done_int = ap_done_reg;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state1) & (ap_start_int == 1'b0))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_state1_pp0_stage0_iter0) & (1'b1 == ap_CS_fsm_state1))) begin
        ap_ready_int = 1'b1;
    end else begin
        ap_ready_int = 1'b0;
    end
end

always @ (*) begin
    if (((ap_loop_init == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
        ap_sig_allocacmp_channel_2 = 6'd0;
    end else begin
        ap_sig_allocacmp_channel_2 = channel_fu_36;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_state1_pp0_stage0_iter0) & (1'b1 == ap_CS_fsm_state1))) begin
        membrane_ce0_local = 1'b1;
    end else begin
        membrane_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln31_fu_76_p2 == 1'd0) & (1'b0 == ap_block_state1_pp0_stage0_iter0) & (1'b1 == ap_CS_fsm_state1))) begin
        membrane_we0_local = 1'b1;
    end else begin
        membrane_we0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_state1_pp0_stage0_iter0) & (1'b1 == ap_CS_fsm_state1))) begin
        spike_count_q_ce0_local = 1'b1;
    end else begin
        spike_count_q_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln31_fu_76_p2 == 1'd0) & (1'b0 == ap_block_state1_pp0_stage0_iter0) & (1'b1 == ap_CS_fsm_state1))) begin
        spike_count_q_we0_local = 1'b1;
    end else begin
        spike_count_q_we0_local = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_state1 : begin
            ap_NS_fsm = ap_ST_fsm_state1;
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign add_ln31_fu_82_p2 = (ap_sig_allocacmp_channel_2 + 6'd1);

assign ap_CS_fsm_state1 = ap_CS_fsm[32'd0];

always @ (*) begin
    ap_block_state1_pp0_stage0_iter0 = (ap_start_int == 1'b0);
end

assign ap_done = ap_done_sig;

assign ap_loop_exit_ready = ap_condition_exit_pp0_iter0_stage0;

assign ap_ready = ap_ready_sig;

assign icmp_ln31_fu_76_p2 = ((ap_sig_allocacmp_channel_2 == 6'd32) ? 1'b1 : 1'b0);

assign membrane_address0 = zext_ln31_fu_88_p1;

assign membrane_ce0 = membrane_ce0_local;

assign membrane_d0 = 16'd0;

assign membrane_we0 = membrane_we0_local;

assign spike_count_q_address0 = zext_ln31_fu_88_p1;

assign spike_count_q_ce0 = spike_count_q_ce0_local;

assign spike_count_q_d0 = 6'd0;

assign spike_count_q_we0 = spike_count_q_we0_local;

assign zext_ln31_fu_88_p1 = ap_sig_allocacmp_channel_2;

endmodule //hybrid_lif_head_q12_6_run_hybrid_lif_head_Pipeline_VITIS_LOOP_31_1
