// ==============================================================
// Generated by Vitis HLS v2025.1
// Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// Copyright 2022-2025 Advanced Micro Devices, Inc. All Rights Reserved.
// ==============================================================

`timescale 1 ns / 1 ps 

(* CORE_GENERATION_INFO="hybrid_lif_head_q12_6_hybrid_lif_head_q12_6,hls_ip_2025_1,{HLS_INPUT_TYPE=cxx,HLS_INPUT_FLOAT=0,HLS_INPUT_FIXED=0,HLS_INPUT_PART=xc7z020-clg400-2,HLS_INPUT_CLOCK=20.000000,HLS_INPUT_ARCH=others,HLS_SYN_CLOCK=13.172500,HLS_SYN_LAT=1687,HLS_SYN_TPT=none,HLS_SYN_MEM=0,HLS_SYN_DSP=0,HLS_SYN_FF=1639,HLS_SYN_LUT=2082,HLS_VERSION=2025_1}" *)

module hybrid_lif_head_q12_6 (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_idle,
        ap_ready,
        feature_current_q_address0,
        feature_current_q_ce0,
        feature_current_q_q0,
        weight_q_address0,
        weight_q_ce0,
        weight_q_q0,
        weight_q_address1,
        weight_q_ce1,
        weight_q_q1,
        bias_q_address0,
        bias_q_ce0,
        bias_q_q0,
        logits_q_address0,
        logits_q_ce0,
        logits_q_we0,
        logits_q_d0,
        spike_count_q_address0,
        spike_count_q_ce0,
        spike_count_q_we0,
        spike_count_q_d0,
        spike_count_q_q0,
        spike_count_q_address1,
        spike_count_q_ce1,
        spike_count_q_q1
);

parameter    ap_ST_fsm_state1 = 2'd1;
parameter    ap_ST_fsm_state2 = 2'd2;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
output   ap_idle;
output   ap_ready;
output  [10:0] feature_current_q_address0;
output   feature_current_q_ce0;
input  [11:0] feature_current_q_q0;
output  [5:0] weight_q_address0;
output   weight_q_ce0;
input  [11:0] weight_q_q0;
output  [5:0] weight_q_address1;
output   weight_q_ce1;
input  [11:0] weight_q_q1;
output  [0:0] bias_q_address0;
output   bias_q_ce0;
input  [11:0] bias_q_q0;
output  [0:0] logits_q_address0;
output   logits_q_ce0;
output   logits_q_we0;
output  [17:0] logits_q_d0;
output  [4:0] spike_count_q_address0;
output   spike_count_q_ce0;
output   spike_count_q_we0;
output  [5:0] spike_count_q_d0;
input  [5:0] spike_count_q_q0;
output  [4:0] spike_count_q_address1;
output   spike_count_q_ce1;
input  [5:0] spike_count_q_q1;

reg ap_done;
reg ap_idle;
reg ap_ready;

(* fsm_encoding = "none" *) reg   [1:0] ap_CS_fsm;
wire    ap_CS_fsm_state1;
wire    grp_run_hybrid_lif_head_fu_28_ap_start;
wire    grp_run_hybrid_lif_head_fu_28_ap_done;
wire    grp_run_hybrid_lif_head_fu_28_ap_idle;
wire    grp_run_hybrid_lif_head_fu_28_ap_ready;
wire   [10:0] grp_run_hybrid_lif_head_fu_28_feature_current_q_address0;
wire    grp_run_hybrid_lif_head_fu_28_feature_current_q_ce0;
wire   [5:0] grp_run_hybrid_lif_head_fu_28_weight_q_address0;
wire    grp_run_hybrid_lif_head_fu_28_weight_q_ce0;
wire   [5:0] grp_run_hybrid_lif_head_fu_28_weight_q_address1;
wire    grp_run_hybrid_lif_head_fu_28_weight_q_ce1;
wire   [0:0] grp_run_hybrid_lif_head_fu_28_bias_q_address0;
wire    grp_run_hybrid_lif_head_fu_28_bias_q_ce0;
wire   [0:0] grp_run_hybrid_lif_head_fu_28_logits_q_address0;
wire    grp_run_hybrid_lif_head_fu_28_logits_q_ce0;
wire    grp_run_hybrid_lif_head_fu_28_logits_q_we0;
wire   [17:0] grp_run_hybrid_lif_head_fu_28_logits_q_d0;
wire   [4:0] grp_run_hybrid_lif_head_fu_28_spike_count_q_address0;
wire    grp_run_hybrid_lif_head_fu_28_spike_count_q_ce0;
wire    grp_run_hybrid_lif_head_fu_28_spike_count_q_we0;
wire   [5:0] grp_run_hybrid_lif_head_fu_28_spike_count_q_d0;
wire   [4:0] grp_run_hybrid_lif_head_fu_28_spike_count_q_address1;
wire    grp_run_hybrid_lif_head_fu_28_spike_count_q_ce1;
reg    grp_run_hybrid_lif_head_fu_28_ap_start_reg;
wire    ap_CS_fsm_state2;
reg   [1:0] ap_NS_fsm;
reg    ap_ST_fsm_state1_blk;
reg    ap_ST_fsm_state2_blk;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_CS_fsm = 2'd1;
#0 grp_run_hybrid_lif_head_fu_28_ap_start_reg = 1'b0;
end

hybrid_lif_head_q12_6_run_hybrid_lif_head grp_run_hybrid_lif_head_fu_28(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(grp_run_hybrid_lif_head_fu_28_ap_start),
    .ap_done(grp_run_hybrid_lif_head_fu_28_ap_done),
    .ap_idle(grp_run_hybrid_lif_head_fu_28_ap_idle),
    .ap_ready(grp_run_hybrid_lif_head_fu_28_ap_ready),
    .feature_current_q_address0(grp_run_hybrid_lif_head_fu_28_feature_current_q_address0),
    .feature_current_q_ce0(grp_run_hybrid_lif_head_fu_28_feature_current_q_ce0),
    .feature_current_q_q0(feature_current_q_q0),
    .weight_q_address0(grp_run_hybrid_lif_head_fu_28_weight_q_address0),
    .weight_q_ce0(grp_run_hybrid_lif_head_fu_28_weight_q_ce0),
    .weight_q_q0(weight_q_q0),
    .weight_q_address1(grp_run_hybrid_lif_head_fu_28_weight_q_address1),
    .weight_q_ce1(grp_run_hybrid_lif_head_fu_28_weight_q_ce1),
    .weight_q_q1(weight_q_q1),
    .bias_q_address0(grp_run_hybrid_lif_head_fu_28_bias_q_address0),
    .bias_q_ce0(grp_run_hybrid_lif_head_fu_28_bias_q_ce0),
    .bias_q_q0(bias_q_q0),
    .logits_q_address0(grp_run_hybrid_lif_head_fu_28_logits_q_address0),
    .logits_q_ce0(grp_run_hybrid_lif_head_fu_28_logits_q_ce0),
    .logits_q_we0(grp_run_hybrid_lif_head_fu_28_logits_q_we0),
    .logits_q_d0(grp_run_hybrid_lif_head_fu_28_logits_q_d0),
    .spike_count_q_address0(grp_run_hybrid_lif_head_fu_28_spike_count_q_address0),
    .spike_count_q_ce0(grp_run_hybrid_lif_head_fu_28_spike_count_q_ce0),
    .spike_count_q_we0(grp_run_hybrid_lif_head_fu_28_spike_count_q_we0),
    .spike_count_q_d0(grp_run_hybrid_lif_head_fu_28_spike_count_q_d0),
    .spike_count_q_q0(spike_count_q_q0),
    .spike_count_q_address1(grp_run_hybrid_lif_head_fu_28_spike_count_q_address1),
    .spike_count_q_ce1(grp_run_hybrid_lif_head_fu_28_spike_count_q_ce1),
    .spike_count_q_q1(spike_count_q_q1)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_state1;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        grp_run_hybrid_lif_head_fu_28_ap_start_reg <= 1'b0;
    end else begin
        if (((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
            grp_run_hybrid_lif_head_fu_28_ap_start_reg <= 1'b1;
        end else if ((grp_run_hybrid_lif_head_fu_28_ap_ready == 1'b1)) begin
            grp_run_hybrid_lif_head_fu_28_ap_start_reg <= 1'b0;
        end
    end
end

always @ (*) begin
    if ((ap_start == 1'b0)) begin
        ap_ST_fsm_state1_blk = 1'b1;
    end else begin
        ap_ST_fsm_state1_blk = 1'b0;
    end
end

always @ (*) begin
    if ((grp_run_hybrid_lif_head_fu_28_ap_done == 1'b0)) begin
        ap_ST_fsm_state2_blk = 1'b1;
    end else begin
        ap_ST_fsm_state2_blk = 1'b0;
    end
end

always @ (*) begin
    if (((grp_run_hybrid_lif_head_fu_28_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state2))) begin
        ap_done = 1'b1;
    end else begin
        ap_done = 1'b0;
    end
end

always @ (*) begin
    if (((ap_start == 1'b0) & (1'b1 == ap_CS_fsm_state1))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((grp_run_hybrid_lif_head_fu_28_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state2))) begin
        ap_ready = 1'b1;
    end else begin
        ap_ready = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_state1 : begin
            if (((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
                ap_NS_fsm = ap_ST_fsm_state2;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end
        end
        ap_ST_fsm_state2 : begin
            if (((grp_run_hybrid_lif_head_fu_28_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state2))) begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state2;
            end
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign ap_CS_fsm_state1 = ap_CS_fsm[32'd0];

assign ap_CS_fsm_state2 = ap_CS_fsm[32'd1];

assign bias_q_address0 = grp_run_hybrid_lif_head_fu_28_bias_q_address0;

assign bias_q_ce0 = grp_run_hybrid_lif_head_fu_28_bias_q_ce0;

assign feature_current_q_address0 = grp_run_hybrid_lif_head_fu_28_feature_current_q_address0;

assign feature_current_q_ce0 = grp_run_hybrid_lif_head_fu_28_feature_current_q_ce0;

assign grp_run_hybrid_lif_head_fu_28_ap_start = grp_run_hybrid_lif_head_fu_28_ap_start_reg;

assign logits_q_address0 = grp_run_hybrid_lif_head_fu_28_logits_q_address0;

assign logits_q_ce0 = grp_run_hybrid_lif_head_fu_28_logits_q_ce0;

assign logits_q_d0 = grp_run_hybrid_lif_head_fu_28_logits_q_d0;

assign logits_q_we0 = grp_run_hybrid_lif_head_fu_28_logits_q_we0;

assign spike_count_q_address0 = grp_run_hybrid_lif_head_fu_28_spike_count_q_address0;

assign spike_count_q_address1 = grp_run_hybrid_lif_head_fu_28_spike_count_q_address1;

assign spike_count_q_ce0 = grp_run_hybrid_lif_head_fu_28_spike_count_q_ce0;

assign spike_count_q_ce1 = grp_run_hybrid_lif_head_fu_28_spike_count_q_ce1;

assign spike_count_q_d0 = grp_run_hybrid_lif_head_fu_28_spike_count_q_d0;

assign spike_count_q_we0 = grp_run_hybrid_lif_head_fu_28_spike_count_q_we0;

assign weight_q_address0 = grp_run_hybrid_lif_head_fu_28_weight_q_address0;

assign weight_q_address1 = grp_run_hybrid_lif_head_fu_28_weight_q_address1;

assign weight_q_ce0 = grp_run_hybrid_lif_head_fu_28_weight_q_ce0;

assign weight_q_ce1 = grp_run_hybrid_lif_head_fu_28_weight_q_ce1;

endmodule //hybrid_lif_head_q12_6
