"""Generate the deterministic C++ golden header used by the HLS testbench."""

from __future__ import annotations

import argparse
import json
from pathlib import Path
from typing import Any


TIME_STEPS = 48
FEATURE_CHANNELS = 32
NUM_CLASSES = 2


def _parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--input",
        type=Path,
        default=Path("hls/hybrid_lif_head/golden/vectors_q12_6.json"),
        help="HLS-1 golden JSON path (relative to the current directory by default)",
    )
    parser.add_argument(
        "--output",
        type=Path,
        default=Path("hls/hybrid_lif_head/tb/golden_vectors_q12_6.hpp"),
        help="generated C++ header path",
    )
    return parser.parse_args()


def _expect_matrix(case: dict[str, Any], key: str, rows: int, columns: int) -> list[list[int]]:
    value = case[key]
    if len(value) != rows or any(len(row) != columns for row in value):
        raise ValueError(f"{case['case_name']}.{key} must be {rows}x{columns}")
    return value


def _expect_vector(case: dict[str, Any], key: str, length: int) -> list[int]:
    value = case[key]
    if len(value) != length:
        raise ValueError(f"{case['case_name']}.{key} must have length {length}")
    return value


def _format_matrix(value: list[list[int]], indent: str = "        ") -> str:
    rows = []
    for row in value:
        rows.append(indent + "{" + ", ".join(str(item) for item in row) + "}")
    return "{\n" + ",\n".join(rows) + "\n    " + "}"


def _format_vector(value: list[int]) -> str:
    return "{" + ", ".join(str(item) for item in value) + "}"


def _case_text(case: dict[str, Any]) -> str:
    currents = _expect_matrix(case, "feature_current_q", TIME_STEPS, FEATURE_CHANNELS)
    weights = _expect_matrix(case, "weight_q", NUM_CLASSES, FEATURE_CHANNELS)
    spikes = _expect_matrix(case, "spikes", TIME_STEPS, FEATURE_CHANNELS)
    membranes = _expect_matrix(
        case, "membrane_after_reset", TIME_STEPS, FEATURE_CHANNELS
    )
    bias = _expect_vector(case, "bias_q", NUM_CLASSES)
    counts = _expect_vector(case, "spike_count", FEATURE_CHANNELS)
    rates = _expect_vector(case, "rate_q", FEATURE_CHANNELS)
    logits = _expect_vector(case, "logits_q", NUM_CLASSES)

    fields = [
        "    {",
        f'        "{case["case_name"]}",',
        f"        {_format_matrix(currents)},",
        f"        {_format_matrix(weights)},",
        f"        {_format_vector(bias)},",
        f"        {_format_matrix(spikes)},",
        f"        {_format_matrix(membranes)},",
        f"        {_format_vector(counts)},",
        f"        {_format_vector(rates)},",
        f"        {_format_vector(logits)}",
        "    }",
    ]
    return "\n".join(fields)


def generate(input_path: Path, output_path: Path) -> None:
    document = json.loads(input_path.read_text(encoding="utf-8"))
    metadata = document["contract_metadata"]
    if metadata["schema_version"] != "hls-q12.6-golden-v1":
        raise ValueError("unsupported HLS golden schema")
    if metadata["time_steps"] != TIME_STEPS or metadata["feature_channels"] != FEATURE_CHANNELS:
        raise ValueError("unexpected HLS dimensions")
    if metadata["classes"] != NUM_CLASSES:
        raise ValueError("unexpected HLS class count")
    cases = document["cases"]
    if len(cases) != 3:
        raise ValueError(f"expected three golden cases, got {len(cases)}")

    case_blocks = ",\n".join(_case_text(case) for case in cases)
    output = f"""// Generated by scripts/generate_hls_golden_header.py; do not edit manually.
#ifndef GOLDEN_VECTORS_Q12_6_HPP
#define GOLDEN_VECTORS_Q12_6_HPP

namespace hls_golden {{

struct GoldenCase {{
    const char* case_name;
    int feature_current_q[48][32];
    int weight_q[2][32];
    int bias_q[2];
    int spikes[48][32];
    int membrane_after_reset[48][32];
    int spike_count[32];
    int rate_q[32];
    int logits_q[2];
}};

static const GoldenCase cases[3] = {{
{case_blocks}
}};

}}  // namespace hls_golden

#endif
"""
    output_path.parent.mkdir(parents=True, exist_ok=True)
    output_path.write_text(output, encoding="utf-8", newline="\n")


def main() -> int:
    arguments = _parse_args()
    generate(arguments.input, arguments.output)
    print(f"generated {arguments.output} from {arguments.input}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
